(function () {
  'use strict';

  const OLD_HOST = 'mindword.dpdns.org';
  const NEW_APP_URL = 'https://mindword.timikays.us.kg/app';
  const DB_NAME = 'mindword_storage';
  const IMAGE_STORE = 'images';
  const DOCUMENT_KEYS = ['mw_documents', 'mindword_docs'];
  const SAFE_SNAPSHOT_KEYS = [
    'mw_documents',
    'mindword_docs',
    'mw_active_doc',
    'mindword_markdown_data',
    'mindword_nodetree_data',
    'myPromptTemplates',
    'promptTemplates'
  ];

  let latestSnapshot = null;

  function safeJsonParse(raw, fallback) {
    if (!raw || typeof raw !== 'string') return fallback;
    try {
      return JSON.parse(raw);
    } catch (_) {
      return fallback;
    }
  }

  function storageValue(storage, key) {
    try {
      return storage.getItem(key);
    } catch (_) {
      return null;
    }
  }

  function hashText(value) {
    let hash = 2166136261;
    const text = String(value || '');
    for (let i = 0; i < text.length; i += 1) {
      hash ^= text.charCodeAt(i);
      hash = Math.imul(hash, 16777619);
    }
    return (hash >>> 0).toString(36);
  }

  function documentName(markdown, fallback) {
    const firstHeading = String(markdown || '').split(/\r?\n/).find(function (line) {
      return /^#{1,6}\s+\S/.test(line.trim());
    });
    if (firstHeading) return firstHeading.replace(/^#{1,6}\s+/, '').trim().slice(0, 80);
    return fallback || '恢复的文档';
  }

  function normalizeDocument(raw, index, sourceKey) {
    if (!raw || typeof raw !== 'object') return null;
    const markdown = typeof raw.md === 'string'
      ? raw.md
      : (typeof raw.markdown === 'string' ? raw.markdown : (typeof raw.content === 'string' ? raw.content : ''));
    const originalId = raw.id ? String(raw.id) : 'legacy_' + hashText(sourceKey + '|' + index + '|' + markdown);
    return {
      id: originalId,
      name: String(raw.name || raw.title || documentName(markdown, '恢复的文档')).slice(0, 120),
      md: markdown,
      images: Array.isArray(raw.images) ? raw.images : [],
      createdAt: Number(raw.createdAt || 0),
      updatedAt: Number(raw.updatedAt || raw.modifiedAt || 0),
      version: Number(raw.version || 1),
      deletedAt: raw.deletedAt || null,
      sourceKey
    };
  }

  function isAutoGeneratedEmptyDocument(doc) {
    return doc && doc.name === '未命名文档' && String(doc.md || '').trim() === '# 未命名文档' && !doc.images.length;
  }

  function chooseDocument(existing, candidate) {
    if (!existing) return candidate;
    if (candidate.updatedAt > existing.updatedAt) return candidate;
    if (candidate.updatedAt === existing.updatedAt && candidate.md.length > existing.md.length) return candidate;
    return existing;
  }

  function collectDocuments(storage, now) {
    const byId = new Map();
    const sourceCounts = {};
    let deletedCount = 0;

    DOCUMENT_KEYS.forEach(function (key) {
      const parsed = safeJsonParse(storageValue(storage, key), []);
      const list = Array.isArray(parsed) ? parsed : (parsed && Array.isArray(parsed.docs) ? parsed.docs : []);
      sourceCounts[key] = list.length;
      list.forEach(function (raw, index) {
        const doc = normalizeDocument(raw, index, key);
        if (!doc) return;
        if (doc.deletedAt) {
          deletedCount += 1;
          return;
        }
        if (isAutoGeneratedEmptyDocument(doc)) return;
        byId.set(doc.id, chooseDocument(byId.get(doc.id), doc));
      });
    });

    const docs = Array.from(byId.values());
    const draft = storageValue(storage, 'mindword_markdown_data');
    let draftCount = 0;
    if (draft && draft.trim() && !docs.some(function (doc) { return doc.md === draft; })) {
      const timestamp = Number(now || Date.now());
      docs.push({
        id: 'unfiled_draft_' + hashText(draft),
        name: documentName(draft, '未归档草稿'),
        md: draft,
        images: [],
        createdAt: timestamp,
        updatedAt: timestamp,
        version: 1,
        deletedAt: null,
        sourceKey: 'mindword_markdown_data',
        isDraft: true
      });
      draftCount = 1;
    }

    docs.sort(function (a, b) { return Number(b.updatedAt || 0) - Number(a.updatedAt || 0); });
    return { docs, draftCount, deletedCount, sourceCounts };
  }

  function readLegacyImages(storage) {
    const parsed = safeJsonParse(storageValue(storage, 'markdown-images'), []);
    if (!Array.isArray(parsed)) return [];
    return parsed.map(function (entry) {
      if (!Array.isArray(entry) || entry.length < 2 || !entry[0]) return null;
      const value = entry[1] || {};
      return {
        id: String(entry[0]),
        documentId: value.documentId || null,
        name: value.name || '',
        type: value.type || 'image/png',
        dataUrl: value.data || value.dataUrl || null,
        source: 'localStorage'
      };
    }).filter(Boolean);
  }

  async function readIndexedDbImages(indexedDb) {
    if (!indexedDb || typeof indexedDb.open !== 'function') return [];

    if (typeof indexedDb.databases === 'function') {
      try {
        const databases = await indexedDb.databases();
        if (Array.isArray(databases) && !databases.some(function (item) { return item && item.name === DB_NAME; })) {
          return [];
        }
      } catch (_) { }
    }

    return new Promise(function (resolve) {
      let settled = false;
      function done(images) {
        if (settled) return;
        settled = true;
        resolve(Array.isArray(images) ? images : []);
      }

      let request;
      try {
        request = indexedDb.open(DB_NAME);
      } catch (_) {
        done([]);
        return;
      }

      request.onupgradeneeded = function () {
        try { request.transaction.abort(); } catch (_) { }
        done([]);
      };
      request.onerror = function () { done([]); };
      request.onsuccess = function () {
        const db = request.result;
        if (!db.objectStoreNames.contains(IMAGE_STORE)) {
          db.close();
          done([]);
          return;
        }
        try {
          const transaction = db.transaction([IMAGE_STORE], 'readonly');
          const getAllRequest = transaction.objectStore(IMAGE_STORE).getAll();
          getAllRequest.onsuccess = function () {
            const images = (getAllRequest.result || []).map(function (image) {
              return Object.assign({}, image, { source: 'indexedDB' });
            });
            db.close();
            done(images);
          };
          getAllRequest.onerror = function () {
            db.close();
            done([]);
          };
        } catch (_) {
          db.close();
          done([]);
        }
      };
    });
  }

  function mergeImages(indexedImages, legacyImages) {
    const byId = new Map();
    (legacyImages || []).forEach(function (image) {
      if (image && image.id) byId.set(String(image.id), image);
    });
    (indexedImages || []).forEach(function (image) {
      if (image && image.id) byId.set(String(image.id), image);
    });
    return Array.from(byId.values());
  }

  function hasRawRecoveryData(storage) {
    return SAFE_SNAPSHOT_KEYS.some(function (key) {
      const value = storageValue(storage, key);
      return typeof value === 'string' && value.length > 0;
    }) || Boolean(storageValue(storage, 'markdown-images'));
  }

  async function scanLocalData(storage, indexedDb, now) {
    const documentState = collectDocuments(storage, now);
    const indexedImages = await readIndexedDbImages(indexedDb);
    const legacyImages = readLegacyImages(storage);
    return {
      documents: documentState.docs,
      draftCount: documentState.draftCount,
      deletedCount: documentState.deletedCount,
      sourceCounts: documentState.sourceCounts,
      images: mergeImages(indexedImages, legacyImages),
      hasRawData: hasRawRecoveryData(storage)
    };
  }

  function extractImageIds(doc) {
    const ids = new Set();
    (doc.images || []).forEach(function (image) {
      if (image && image.id) ids.add(String(image.id));
    });
    const regex = /!\[[^\]]*\]\(([^)]+)\)/g;
    let match;
    while ((match = regex.exec(String(doc.md || ''))) !== null) {
      const id = match[1];
      if (id && !/^(https?:\/\/|data:)/i.test(id)) ids.add(id);
    }
    return ids;
  }

  function safeFilePart(value, fallback) {
    const safe = String(value || '').replace(/[\\/:*?"<>|\u0000-\u001f]+/g, '_').trim();
    return (safe || fallback || 'item').slice(0, 80);
  }

  function extensionForImage(image) {
    const type = String(image.type || (image.blob && image.blob.type) || '').toLowerCase();
    if (type.includes('jpeg')) return 'jpg';
    if (type.includes('gif')) return 'gif';
    if (type.includes('webp')) return 'webp';
    if (type.includes('svg')) return 'svg';
    if (type.includes('bmp')) return 'bmp';
    return 'png';
  }

  function dataUrlToBlob(dataUrl) {
    const parts = String(dataUrl || '').split(',');
    if (parts.length < 2) throw new Error('图片数据格式无效');
    const mimeMatch = parts[0].match(/data:([^;]+)/);
    const mime = mimeMatch ? mimeMatch[1] : 'application/octet-stream';
    const binary = parts[0].includes(';base64') ? atob(parts[1]) : decodeURIComponent(parts[1]);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
    return new Blob([bytes], { type: mime });
  }

  function blobForImage(image) {
    if (image.blob instanceof Blob) return image.blob;
    if (image.dataUrl) return dataUrlToBlob(image.dataUrl);
    if (image.data) return dataUrlToBlob(image.data);
    return null;
  }

  function collectInlineImages(doc, knownImages) {
    const knownIds = new Set(knownImages.map(function (image) { return String(image.id); }));
    return (doc.images || []).map(function (image) {
      if (!image || !image.id || knownIds.has(String(image.id))) return null;
      const dataUrl = image.dataUrl || image.data;
      if (!dataUrl) return null;
      return {
        id: String(image.id),
        documentId: doc.id,
        name: image.name || '',
        type: image.mime || image.type || 'image/png',
        dataUrl,
        source: 'document'
      };
    }).filter(Boolean);
  }

  function rawLocalSnapshot(storage, includeAiConfig) {
    const values = {};
    SAFE_SNAPSHOT_KEYS.forEach(function (key) {
      const value = storageValue(storage, key);
      if (value !== null) values[key] = value;
    });
    if (includeAiConfig) {
      const aiConfig = storageValue(storage, 'allAIPlatformConfigs');
      if (aiConfig !== null) values.allAIPlatformConfigs = aiConfig;
    }
    return values;
  }

  function addOptionalJson(zipFolder, name, raw) {
    if (!raw) return false;
    const parsed = safeJsonParse(raw, null);
    if (parsed === null) return false;
    zipFolder.file(name, JSON.stringify(parsed, null, 2));
    return true;
  }

  async function buildRecoveryZip(snapshot, storage, options) {
    if (!window.JSZip) throw new Error('ZIP 组件加载失败，请刷新页面后重试');
    const settings = options || {};
    const zip = new window.JSZip();
    const exportedImageIds = new Set();
    const manifestDocuments = [];
    const allImages = snapshot.images.slice();

    snapshot.documents.forEach(function (doc) {
      collectInlineImages(doc, allImages).forEach(function (image) { allImages.push(image); });
    });

    for (let index = 0; index < snapshot.documents.length; index += 1) {
      const doc = snapshot.documents[index];
      const recoveryId = 'recovered_' + safeFilePart(doc.id, hashText(doc.md));
      const folderName = String(index + 1).padStart(3, '0') + '_' + safeFilePart(doc.name, 'document') + '_' + hashText(doc.id);
      const folder = zip.folder(folderName);
      folder.file('index.md', String(doc.md || ''));
      folder.file('meta.json', JSON.stringify({
        id: recoveryId,
        originalId: doc.id,
        name: doc.name,
        version: doc.version || 1,
        createdAt: doc.createdAt || null,
        updatedAt: doc.updatedAt || null,
        recoveredAt: Date.now(),
        recoveredFrom: window.location.origin
      }, null, 2));

      const referencedIds = extractImageIds(doc);
      const relatedImages = allImages.filter(function (image) {
        return String(image.documentId || '') === String(doc.id) || referencedIds.has(String(image.id));
      });
      let exportedForDocument = 0;
      if (relatedImages.length) {
        const imageFolder = folder.folder('images');
        for (const image of relatedImages) {
          const blob = blobForImage(image);
          if (!blob) continue;
          const fileName = safeFilePart(image.id, 'image_' + exportedForDocument) + '.' + extensionForImage(image);
          imageFolder.file(fileName, blob);
          exportedImageIds.add(String(image.id));
          exportedForDocument += 1;
        }
      }
      manifestDocuments.push({
        originalId: doc.id,
        recoveryId,
        name: doc.name,
        sourceKey: doc.sourceKey,
        isDraft: Boolean(doc.isDraft),
        imageCount: exportedForDocument
      });
    }

    const recoveryFolder = zip.folder('recovery');
    const orphanFolder = recoveryFolder.folder('orphan-images');
    let orphanImageCount = 0;
    for (const image of allImages) {
      if (exportedImageIds.has(String(image.id))) continue;
      const blob = blobForImage(image);
      if (!blob) continue;
      const fileName = safeFilePart(image.id, 'orphan_' + orphanImageCount) + '.' + extensionForImage(image);
      orphanFolder.file(fileName, blob);
      orphanImageCount += 1;
    }

    const includeAiConfig = Boolean(settings.includeAiConfig);
    const aiFolder = zip.folder('ai');
    addOptionalJson(aiFolder, 'my-prompt-templates.json', storageValue(storage, 'myPromptTemplates'));
    if (includeAiConfig) {
      addOptionalJson(aiFolder, 'platform-configs.json', storageValue(storage, 'allAIPlatformConfigs'));
    }

    recoveryFolder.file('local-data.json', JSON.stringify({
      format: 'mindword-local-recovery-v1',
      exportedAt: new Date().toISOString(),
      origin: window.location.origin,
      values: rawLocalSnapshot(storage, includeAiConfig)
    }, null, 2));
    recoveryFolder.file('manifest.json', JSON.stringify({
      format: 'mindword-recovery-zip-v1',
      exportedAt: new Date().toISOString(),
      origin: window.location.origin,
      documentCount: manifestDocuments.length,
      imageCount: exportedImageIds.size,
      orphanImageCount,
      deletedDocumentCount: snapshot.deletedCount,
      includedAiConfig: includeAiConfig,
      documents: manifestDocuments
    }, null, 2));

    return zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    }, function (metadata) {
      if (typeof settings.onProgress === 'function') settings.onProgress(metadata.percent || 0);
    });
  }

  function formattedTimestamp(date) {
    const value = date || new Date();
    const pad = function (number) { return String(number).padStart(2, '0'); };
    return value.getFullYear() + '-' + pad(value.getMonth() + 1) + '-' + pad(value.getDate()) + '_' + pad(value.getHours()) + '-' + pad(value.getMinutes());
  }

  function downloadBlob(blob, fileName) {
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
  }

  function setMessage(message, isError) {
    const element = document.getElementById('recovery-scan-message');
    if (!element) return;
    element.textContent = message;
    element.classList.toggle('error', Boolean(isError));
  }

  function updateOriginNotice() {
    const notice = document.getElementById('origin-notice');
    const download = document.getElementById('recovery-download');
    if (!notice || !download) return;

    const hostname = window.location.hostname;
    const isDevelopment = hostname === 'localhost' || hostname === '127.0.0.1';
    if (hostname === OLD_HOST || isDevelopment) {
      notice.textContent = isDevelopment
        ? '当前为本地测试环境。线上恢复必须从旧域名 recovery 地址进入。'
        : '已进入旧域名恢复环境。请勿清理浏览器网站数据，先下载恢复包。';
      return;
    }

    notice.textContent = '当前页面不在旧域名下，无法读取旧地址保存的数据。请点击下方按钮，从旧地址重新打开恢复页。';
    notice.classList.add('error');
    download.dataset.wrongOrigin = 'true';
    const openOld = document.createElement('a');
    openOld.href = 'https://' + OLD_HOST + '/recovery/';
    openOld.textContent = '从旧地址打开恢复页';
    openOld.className = 'topbar-link';
    openOld.style.display = 'inline-block';
    openOld.style.marginTop = '8px';
    notice.appendChild(document.createElement('br'));
    notice.appendChild(openOld);
  }

  function renderSnapshot(snapshot) {
    document.getElementById('recovery-doc-count').textContent = String(snapshot.documents.length);
    document.getElementById('recovery-image-count').textContent = String(snapshot.images.length);
    document.getElementById('recovery-draft-count').textContent = String(snapshot.draftCount);

    const download = document.getElementById('recovery-download');
    const recoverable = snapshot.documents.length > 0 || snapshot.images.length > 0 || snapshot.hasRawData;
    download.disabled = !recoverable || download.dataset.wrongOrigin === 'true';

    if (!recoverable) {
      setMessage('没有在这个浏览器账号中找到可恢复数据。请确认设备、浏览器和浏览器账号与以前一致。', true);
      return;
    }

    const sourceText = '当前文档库 ' + Number(snapshot.sourceCounts.mw_documents || 0) + ' 项，旧版文档库 ' + Number(snapshot.sourceCounts.mindword_docs || 0) + ' 项。';
    setMessage('检测完成。' + sourceText + ' 下载恢复包前请保持本页打开。', false);
  }

  async function scanAndRender() {
    try {
      latestSnapshot = await scanLocalData(window.localStorage, window.indexedDB, Date.now());
      renderSnapshot(latestSnapshot);
    } catch (error) {
      setMessage('扫描失败：' + (error && error.message ? error.message : '未知错误'), true);
    }
  }

  async function handleDownload() {
    const button = document.getElementById('recovery-download');
    const progress = document.getElementById('recovery-progress');
    const progressBar = document.getElementById('recovery-progress-bar');
    const includeAiConfig = document.getElementById('recovery-include-ai').checked;
    const originalText = button.innerHTML;

    button.disabled = true;
    button.textContent = '正在打包本地数据...';
    progress.classList.add('active');
    progress.setAttribute('aria-hidden', 'false');
    progressBar.style.width = '4%';

    try {
      if (!latestSnapshot) latestSnapshot = await scanLocalData(window.localStorage, window.indexedDB, Date.now());
      const blob = await buildRecoveryZip(latestSnapshot, window.localStorage, {
        includeAiConfig,
        onProgress: function (percent) {
          progressBar.style.width = Math.max(4, Math.min(100, percent)) + '%';
        }
      });
      downloadBlob(blob, 'MindWord_Recovery_' + formattedTimestamp(new Date()) + '.zip');
      progressBar.style.width = '100%';
      setMessage('恢复包已下载。现在可以前往新地址，在“我的文档”中选择“导入 ZIP”。', false);
      document.getElementById('recovery-go-new').hidden = false;
    } catch (error) {
      setMessage('恢复包生成失败：' + (error && error.message ? error.message : '未知错误'), true);
      button.disabled = false;
    } finally {
      button.innerHTML = originalText;
      if (button.dataset.wrongOrigin !== 'true' && latestSnapshot) button.disabled = false;
    }
  }

  window.MW_RECOVERY = {
    safeJsonParse,
    collectDocuments,
    readLegacyImages,
    mergeImages,
    scanLocalData,
    buildRecoveryZip,
    oldHost: OLD_HOST,
    newAppUrl: NEW_APP_URL
  };

  function init() {
    updateOriginNotice();
    const button = document.getElementById('recovery-download');
    if (button) button.addEventListener('click', handleDownload);
    scanAndRender();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
  } else {
    init();
  }
})();
