/**
 * MindWord - 树心 | 像画图一样写文档的思维导图写作工具
 * GitHub: https://github.com/TimiKays/MindWord
 * 
 * Copyright 2025 Timi Kays
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// =============== 文档库与侧栏 ===============
/*
## 🏠 文档库管理功能
### 1. 文档存储与加载
- localStorage 存储 ：使用 mw_documents 和 mw_active_doc 两个 key 存储文档数据和当前活动文档
- 基础 CRUD 操作 ：提供 mw_loadDocs() 、 mw_saveDocs() 、 mw_setActive() 、 mw_getActive() 等基础函数
### 2. 文档列表渲染 (mw_renderList)
- 智能过滤 ：自动清理已删除文档和自动生成的空文档
- 拖拽排序 ：支持通过拖拽重新排序文档（仅在非批量模式下）
- 双模式显示 ：
  - 正常模式：显示文档名称和操作按钮
  - 批量模式：显示复选框，支持多选操作
### 3. 文档操作功能
- 新建文档 ： mw_newDoc() → mw_showNewDocDialog() → mw_confirmNewDoc()
  - 支持 AI 自动生成初始内容
  - 创建后自动同步到三个面板（编辑器、预览、思维导图）
- 打开文档 ： mw_openDoc()
  - 设置活动文档
  - 同步通知所有面板加载内容
  - 自动关闭侧边栏
- 删除文档 ： mw_deleteDoc() → mw_showDeleteConfirm() → mw_confirmDeleteDoc()
  - 软删除机制（标记 deletedAt 时间戳）
  - 支持批量删除
  - 删除后自动切换到下一个可用文档
### 4. 高级功能
- 自动清理 ： mw_cleanAutoGeneratedEmptyDocs() 清理系统自动生成的空文档
- 排序保存 ： mw_saveDocOrder() 保存用户拖拽后的文档顺序
- 跨设备同步 ：删除操作会同步到所有设备

*/

const MW_STORAGE_KEYS = {
  docs: 'mw_documents',
  active: 'mw_active_doc'
};

function mw_loadDocs() {
  try { return JSON.parse(localStorage.getItem(MW_STORAGE_KEYS.docs) || '[]'); } catch (_) { return []; }
}
function mw_saveDocs(docs) {
  localStorage.setItem(MW_STORAGE_KEYS.docs, JSON.stringify(docs));
}
function mw_setActive(docId) {
  localStorage.setItem(MW_STORAGE_KEYS.active, docId || '');
}
function mw_getActive() {
  return localStorage.getItem(MW_STORAGE_KEYS.active) || '';
}

function mw_cleanAutoGeneratedEmptyDocs() {
  const docs = mw_loadDocs();
  const hasRealDocs = docs.some(doc => !doc.deletedAt && !isAutoGeneratedEmptyDoc(doc));

  if (hasRealDocs) {
    // 如果有真实文档，删除所有自动生成的空文档
    const cleanedDocs = docs.filter(doc => !isAutoGeneratedEmptyDoc(doc));
    if (cleanedDocs.length !== docs.length) {
      mw_saveDocs(cleanedDocs);
      console.log('自动清理了', docs.length - cleanedDocs.length, '个自动生成的空文档');
      return true;
    }
  }
  return false;
}

function mw_saveDocOrder(orderedIds) {
  const docs = mw_loadDocs();
  const orderedDocs = [];

  // 按照新的顺序重新排列文档
  orderedIds.forEach(id => {
    const doc = docs.find(d => d.id === id);
    if (doc) {
      orderedDocs.push(doc);
    }
  });

  // 添加剩余的文档（未拖拽排序的）
  docs.forEach(doc => {
    if (!orderedIds.includes(doc.id)) {
      orderedDocs.push(doc);
    }
  });

  mw_saveDocs(orderedDocs);
}

function mw_renderList() {
  const list = document.getElementById('doc-list');

  // 先清理自动生成的空文档
  const cleaned = mw_cleanAutoGeneratedEmptyDocs();

  const docs = mw_loadDocs();
  const active = mw_getActive();
  const batchMode = document.getElementById('batch-actions').classList.contains('show');
  list.innerHTML = '';

  // 过滤掉已删除的文档和自动生成的空文档
  const visibleDocs = docs.filter(doc => !doc.deletedAt && !isAutoGeneratedEmptyDoc(doc));

  if (!visibleDocs.length) {
    list.innerHTML = '<div style="padding:12px;color:#64748b;font-size:12px;">暂无文档，点击"新增"创建</div>';
    return;
  }

  // 添加拖拽排序功能（仅在非批量模式下）
  if (!batchMode) {
    list.style.cursor = 'grab';
    let draggedElement = null;
    let draggedId = null;

    list.addEventListener('dragstart', (e) => {
      if (e.target.classList.contains('doc-item')) {
        draggedElement = e.target;
        draggedId = e.target.dataset.docId;
        e.target.style.opacity = '0.5';
        e.dataTransfer.effectAllowed = 'move';
      }
    });

    list.addEventListener('dragend', (e) => {
      if (e.target.classList.contains('doc-item')) {
        e.target.style.opacity = '';
        draggedElement = null;
        draggedId = null;
      }
    });

    list.addEventListener('dragover', (e) => {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'move';

      const afterElement = getDragAfterElement(list, e.clientY);
      if (afterElement == null) {
        list.appendChild(draggedElement);
      } else {
        list.insertBefore(draggedElement, afterElement);
      }
    });

    list.addEventListener('drop', (e) => {
      e.preventDefault();
      if (draggedElement && draggedId) {
        // 获取新的排序
        const docItems = Array.from(list.querySelectorAll('.doc-item'));
        const orderedIds = docItems.map(item => item.dataset.docId);

        // 保存新的排序
        mw_saveDocOrder(orderedIds);

        // 重新渲染列表以保持状态
        mw_renderList();

        console.log('文档排序已更新');
      }
    });

    function getDragAfterElement(container, y) {
      const draggableElements = [...container.querySelectorAll('.doc-item:not(.dragging)')];

      return draggableElements.reduce((closest, child) => {
        const box = child.getBoundingClientRect();
        const offset = y - box.top - box.height / 2;

        if (offset < 0 && offset > closest.offset) {
          return { offset: offset, element: child };
        } else {
          return closest;
        }
      }, { offset: Number.NEGATIVE_INFINITY }).element;
    }
  }

  visibleDocs.forEach(doc => {
    const row = document.createElement('div');
    row.className = 'doc-item' + (active === doc.id ? ' active' : '') + (batchMode ? ' batch-mode' : '');
    row.draggable = !batchMode; // 仅在非批量模式下可拖拽
    row.dataset.docId = doc.id; // 添加文档ID用于拖拽排序

    if (batchMode) {
      // 批量模式：显示复选框
      row.innerHTML = `
                        <input type="checkbox" class="doc-checkbox" data-doc-id="${doc.id}" title="选择文档">
                        <div class="doc-name" title="${doc.name}">${doc.name}</div>
                        <div class="doc-buttons">
                            <button data-act="export" data-i18n="app.toolbar.export">导出</button>
                            <button data-act="copy" data-i18n="app.toolbar.copy" title="复制新建">复制</button>
                            <button data-act="del" data-i18n="app.node.delete" style="color:#b91c1c;border-color:#fecaca;">删除</button>
                        </div>
                    `;
    } else {
      // 正常模式：不显示复选框
      row.innerHTML = `
                        <div class="doc-name" title="${doc.name}">${doc.name}</div>
                        <div class="doc-buttons">
                            <button data-act="export" data-i18n="app.toolbar.export">导出</button>
                            <button data-act="copy" data-i18n="app.toolbar.copy" title="复制新建">复制</button>
                            <button data-act="del" data-i18n="app.node.delete" style="color:#b91c1c;border-color:#fecaca;">删除</button>
                        </div>
                    `;
    }

    row.onclick = (e) => {
      // 如果点击的是按钮或复选框，不触发整行点击
      if (e.target.tagName === 'BUTTON' || e.target.type === 'checkbox') return;
      if (batchMode) {
        // 批量模式下，点击行切换复选框状态
        const checkbox = row.querySelector('.doc-checkbox');
        if (checkbox) {
          checkbox.checked = !checkbox.checked;
        }
      } else {
        mw_openDoc(doc.id);
      }
    };

    if (!batchMode) {
      row.querySelector('[data-act="export"]').onclick = () => mw_exportDocZip(doc.id);
      row.querySelector('[data-act="copy"]').onclick = () => mw_copyNewDoc(doc.id);
      row.querySelector('[data-act="del"]').onclick = () => mw_deleteDoc(doc.id);
    } else {
      // 批量模式下也需要绑定复制按钮事件
      row.querySelector('[data-act="copy"]').onclick = () => mw_copyNewDoc(doc.id);
    }

    list.appendChild(row);
  });

  // 对新创建的按钮应用国际化翻译
  if (window.i18nManager) {
    window.i18nManager.updatePageTranslations();
  }
}

function mw_toggleSidebar(open) {
  const el = document.getElementById('doc-sidebar');
  if (open === true) el.classList.add('open');
  else if (open === false) el.classList.remove('open');
  else el.classList.toggle('open');
  el.setAttribute('aria-hidden', el.classList.contains('open') ? 'false' : 'true');
}

function mw_newDoc() {
  mw_showNewDocDialog();
}

// 显示新建文档对话框
function mw_showNewDocDialog() {
  const overlay = document.getElementById('new-doc-overlay');
  const dialog = document.getElementById('new-doc-dialog');
  const input = document.getElementById('new-doc-name');

  // 设置默认值
  input.value = '未命名文档';

  // 显示对话框和遮罩
  overlay.style.display = 'block';
  dialog.style.display = 'block';

  // 聚焦输入框
  setTimeout(() => {
    input.focus();
    input.select();
  }, 100);
}

// 隐藏新建文档对话框
function mw_hideNewDocDialog() {
  const overlay = document.getElementById('new-doc-overlay');
  const dialog = document.getElementById('new-doc-dialog');

  overlay.style.display = 'none';
  dialog.style.display = 'none';
}

// 确认创建新文档
function mw_confirmNewDoc(useAIGenerate) {
  const input = document.getElementById('new-doc-name');
  const name = input.value.trim();

  if (!name) {
    alert('请输入文档名称');
    return;
  }

  mw_hideNewDocDialog();

  const id = 'doc_' + Date.now();
  const doc = {
    id, name,
    md: '# ' + name + '\n',
    images: [], // {id, name, mime}
    createdAt: Date.now(),
    updatedAt: Date.now(),
    version: 1
  };
  const docs = mw_loadDocs();
  docs.push(doc);
  mw_saveDocs(docs);
  mw_setActive(id);
  mw_renderList();
  mw_notifyEditorLoad(doc);
  mw_notifyMindmapLoad(doc); // 通知思维导图面板加载新文档

  // 如果使用AI生成，立即隐藏侧边栏并激活思维导图页面的AI功能
  if (useAIGenerate) {
    // 立即隐藏文档侧边栏
    mw_toggleSidebar(false);

    setTimeout(() => {
      const mindmapFrame = document.querySelector('iframe[data-panel="mindmap"], iframe#iframe-mindmap, iframe[src*="jsmind/mindmap.html"]');
      if (mindmapFrame && mindmapFrame.contentWindow && mindmapFrame.contentWindow.aiGenerateInitialTreeMini) {
        mindmapFrame.contentWindow.aiGenerateInitialTreeMini({
          placeholders: {
            name: { value: name }
          },
          autoRun: true
        });
      } else {
        console.warn('[AI] 无法找到思维导图iframe或aiGenerateInitialTreeMini函数');
      }
    }, 500); // 延迟确保思维导图加载完成
  }

  try { showSuccess && showSuccess('已创建并打开'); } catch (_) { }
}

// 切换文档
function mw_openDoc(id) {
  console.log('[DOC] mw_openDoc starting for doc id:', id);
  const docs = mw_loadDocs();
  const doc = docs.find(d => d.id === id);
  if (!doc) {
    console.warn('[DOC] mw_openDoc failed: document not found for id:', id);
    return alert('文档不存在');
  }
  console.log('[DOC] mw_openDoc found document:', doc.name, 'id:', doc.id, 'version:', doc.version);

  mw_setActive(id);
  console.log('[DOC] mw_openDoc set active document to:', id);

  mw_renderList();
  console.log('[DOC] mw_openDoc rendered document list');

  // 打开时以 Markdown 为准同步三面板
  console.log('[DOC] mw_openDoc starting panel notifications...');
  mw_notifyEditorLoad(doc);
  console.log('[DOC] mw_openDoc notified editor panel');

  mw_notifyPreviewLoad(doc);
  console.log('[DOC] mw_openDoc notified preview panel');

  mw_notifyMindmapLoad(doc);
  console.log('[DOC] mw_openDoc completed mindmap notification');

  // 立即关闭侧栏并确保编辑器面板显示（避免 handleTabClick 在非专注模式下把编辑器切换为隐藏）
  try {
    mw_toggleSidebar(false);
    console.log('[DOC] mw_openDoc toggled sidebar');
  } catch (e) {
    console.warn('[DOC] mw_openDoc failed to toggle sidebar:', e);
  }

  try {
    // panels.editor = true;
    saveStateToStorage();
    updateLayout();
    updateTabs();
    console.log('[DOC] mw_openDoc updated layout and tabs');
  } catch (e) {
    console.warn('[DOC] mw_openDoc failed to update layout/tabs:', e);
  }

  console.log('[DOC] mw_openDoc completed successfully for doc:', doc.name);
}

// 删除文档（显示确认对话框）
function mw_deleteDoc(docId) {
  const docs = mw_loadDocs();
  const doc = docs.find(d => d.id === docId);
  if (!doc) return;

  // 显示删除确认对话框
  mw_showDeleteConfirm(docId, doc.name);
}

// 显示删除确认对话框（侧边栏内嵌版本）
function mw_showDeleteConfirm(docId, docName) {
  const overlay = document.getElementById('delete-confirm-overlay');
  const dialog = document.getElementById('delete-confirm-dialog');
  const message = document.getElementById('delete-confirm-message');

  // 设置确认消息
  message.textContent = `确定要删除文档 "${docName}"？此操作会在所有设备上同步删除`;

  // 存储文档ID用于确认删除
  dialog.dataset.docId = docId;

  // 显示对话框和遮罩
  overlay.style.display = 'block';
  dialog.style.display = 'block';
}

// 显示批量删除确认对话框（侧边栏内嵌版本）
function mw_showBatchDeleteConfirm() {
  const checkboxes = document.querySelectorAll('.doc-checkbox:checked');
  if (checkboxes.length === 0) {
    alert('请先选择要删除的文档');
    return;
  }

  const overlay = document.getElementById('delete-confirm-overlay');
  const dialog = document.getElementById('delete-confirm-dialog');
  const message = document.getElementById('delete-confirm-message');

  // 清除文档ID，确保这是批量删除模式
  dialog.removeAttribute('data-doc-id');

  // 设置确认消息
  message.textContent = `确定要删除选中的 ${checkboxes.length} 个文档？此操作会在所有设备上同步删除`;

  // 显示对话框和遮罩
  overlay.style.display = 'block';
  dialog.style.display = 'block';
}

// 确认批量删除
async function mw_confirmBatchDelete() {
  mw_hideDeleteConfirm();

  const checkboxes = document.querySelectorAll('.doc-checkbox:checked');
  let docs = mw_loadDocs();
  const selectedIds = Array.from(checkboxes).map(cb => cb.dataset.docId);

  // 标记选中文档为已删除
  let deletedCount = 0;
  selectedIds.forEach(id => {
    const idx = docs.findIndex(d => d.id === id);
    if (idx >= 0) {
      docs[idx] = {
        id: docs[idx].id,
        name: docs[idx].name,
        deletedAt: Date.now(),
        updatedAt: Date.now()
      };
      deletedCount++;
    }
  });

  mw_saveDocs(docs);

  // 删除关联的图片
  if (window.imageStorage) {
    let totalDeletedImages = 0;
    for (const docId of selectedIds) {
      try {
        const deletedImagesCount = await window.imageStorage.deleteImagesByDocumentId(docId);
        totalDeletedImages += deletedImagesCount;
        console.log(`删除了文档 ${docId} 的 ${deletedImagesCount} 张图片`);
      } catch (error) {
        console.error(`删除文档 ${docId} 关联图片失败:`, error);
      }
    }
    if (totalDeletedImages > 0) {
      console.log(`批量删除文档时总共删除了 ${totalDeletedImages} 张图片`);
    }
  }

  // 如果删除的文档中包含当前活动文档
  const activeId = mw_getActive();
  if (selectedIds.includes(activeId)) {
    // 清空当前活动文档
    mw_setActive('');

    // 找到第一个未删除的文档
    const activeDoc = docs.find(d => !d.deletedAt);
    if (activeDoc) {
      mw_setActive(activeDoc.id);
      // 通知各个面板加载第一个未删除文档
      mw_notifyEditorLoad(activeDoc);
      mw_notifyPreviewLoad(activeDoc);
      mw_notifyMindmapLoad(activeDoc);
    } else {
      // 没有剩余未删除文档，不再自动生成空文档
      // 清空活动文档，让用户手动创建新文档
      console.log('没有剩余文档，等待用户手动创建');
    }
  }

  // 退出批量模式
  mw_exitBatchMode();
  mw_renderList();
  try { showSuccess && showSuccess(`已删除 ${deletedCount} 个文档，将在所有设备同步`); } catch (_) { }
}

// 隐藏删除确认对话框
function mw_hideDeleteConfirm() {
  const overlay = document.getElementById('delete-confirm-overlay');
  const dialog = document.getElementById('delete-confirm-dialog');

  overlay.style.display = 'none';
  dialog.style.display = 'none';
  dialog.removeAttribute('data-doc-id');
}

// 确认删除单个文档
async function mw_confirmDeleteDoc() {
  const dialog = document.getElementById('delete-confirm-dialog');
  const docId = dialog.dataset.docId;

  if (!docId) return;

  mw_hideDeleteConfirm();

  let docs = mw_loadDocs();
  const idx = docs.findIndex(d => d.id === docId);
  if (idx >= 0) {
    docs[idx] = {
      id: docs[idx].id,
      name: docs[idx].name,
      deletedAt: Date.now(),
      updatedAt: Date.now()
    };
    mw_saveDocs(docs);

    // 删除关联的图片
    if (window.imageStorage) {
      try {
        const deletedImagesCount = await window.imageStorage.deleteImagesByDocumentId(docId);
        console.log(`删除了文档 ${docId} 的 ${deletedImagesCount} 张图片`);
      } catch (error) {
        console.error(`删除文档 ${docId} 关联图片失败:`, error);
      }
    }

    // 如果删除的是当前活动文档
    const activeId = mw_getActive();
    if (docId === activeId) {
      // 清空当前活动文档
      mw_setActive('');

      // 找到第一个未删除的文档
      const activeDoc = docs.find(d => !d.deletedAt);
      if (activeDoc) {
        mw_setActive(activeDoc.id);
        // 通知各个面板加载第一个未删除文档
        mw_notifyEditorLoad(activeDoc);
        mw_notifyPreviewLoad(activeDoc);
        mw_notifyMindmapLoad(activeDoc);
      } else {
        // 没有剩余未删除文档，不再自动生成未命名文档，等待用户手动创建
        console.log('没有剩余文档，等待用户手动创建');
        // 清空当前活动文档
        mw_setActive(null);
        mw_renderList();
        // 通知各个面板清空内容
        mw_notifyEditorLoad({ id: null, name: '', md: '', images: [] });
        mw_notifyPreviewLoad({ md: '', images: [] });
        mw_notifyMindmapLoad({ md: '', images: [] });
      }
    }

    mw_renderList();
    try { showSuccess && showSuccess('文档已删除，将在所有设备同步'); } catch (_) { }
  }
}

// 批量删除功能
function mw_batchDeleteDocs() {
  mw_showBatchDeleteConfirm();
}

// 进入批量模式
function mw_enterBatchMode() {
  document.getElementById('batch-actions').classList.add('show');
  mw_renderList();
}

// 退出批量模式
function mw_exitBatchMode() {
  document.getElementById('batch-actions').classList.remove('show');
  mw_renderList();
}

// 全选文档
function mw_selectAllDocs() {
  document.querySelectorAll('.doc-checkbox').forEach(cb => cb.checked = true);
}

// 全不选文档
function mw_selectNoneDocs() {
  document.querySelectorAll('.doc-checkbox').forEach(cb => cb.checked = false);
}

function mw_notifyEditorLoad(doc) {
  const editorIframe = document.querySelector('iframe[data-panel="editor"], iframe#iframe-editor, iframe[src*="editor/editor.html"]');
  // 确保图片数据格式正确传递给编辑器
  const images = doc.images || [];
  const payload = {
    id: doc.id,
    name: doc.name,
    md: doc.md,
    images: images,
    rev: doc.version || doc.updatedAt || Date.now(),
    origin: 'index'
  };
  if (editorIframe && editorIframe.contentWindow) {
    try {
      editorIframe.contentWindow.postMessage({ type: 'mw_load_document', payload }, '*');
      console.log('[DOC] -> editor mw_load_document', payload.id, 'rev=', payload.rev);
    } catch (e) { console.warn('postMessage to editor failed', e); }
  } else {
    // iframe 未就绪，缓存待发内容，onload 立即派发
    try { window.__mw_pendingEditorDocument = payload; } catch (_) { }
  }
}

function mw_notifyPreviewLoad(doc) {
  const previewIframe = document.querySelector('iframe[data-panel="preview"], iframe#iframe-preview, iframe[src*="md2word/md2word.html"], iframe[src*="preview"]');
  const payload = { md: doc.md, images: doc.images || [], rev: doc.version || doc.updatedAt || Date.now(), origin: 'index' };
  if (previewIframe && previewIframe.contentWindow) {
    try {
      previewIframe.contentWindow.postMessage({ type: 'mw_load_markdown', payload }, '*');
      console.log('[DOC] -> preview mw_load_markdown', (doc.id || ''), 'rev=', payload.rev);
    } catch (e) { console.warn('postMessage to preview failed', e); }
  } else {
    // iframe 尚未就绪，缓存待发送数据，待 onload 时立即发送
    try { window.__mw_pendingPreviewMarkdown = payload; } catch (_) { }
  }
}

function mw_notifyMindmapLoad(doc) {
  console.log('[DOC] mw_notifyMindmapLoad starting for doc:', (doc.name || 'unnamed'), 'id:', (doc.id || 'none'));

  const mmIframe = document.querySelector('iframe[data-panel="mindmap"], iframe#iframe-mindmap, iframe[src*="jsmind/mindmap.html"]');
  console.log('[DOC] mw_notifyMindmapLoad found iframe:', !!mmIframe);

  if (mmIframe) {
    console.log('[DOC] mw_notifyMindmapLoad iframe details - src:', (mmIframe.src || 'none'));
    console.log('[DOC] mw_notifyMindmapLoad iframe details - contentWindow exists:', !!mmIframe.contentWindow);
    console.log('[DOC] mw_notifyMindmapLoad iframe details - readyState:', (mmIframe.readyState || 'unknown'));
  }

  const payload = {
    md: doc.md,
    images: doc.images || [],
    rev: doc.version || doc.updatedAt || Date.now(),
    origin: 'index',
    docId: doc.id
  };

  console.log('[DOC] mw_notifyMindmapLoad prepared payload - rev:', payload.rev, 'md length:', (doc.md ? doc.md.length : 0));

  if (mmIframe && mmIframe.contentWindow) {
    console.log('[DOC] mw_notifyMindmapLoad attempting to send message to mindmap iframe...');
    try {
      mmIframe.contentWindow.postMessage({ type: 'mw_load_markdown', payload }, '*');
      console.log('[DOC] -> mindmap mw_load_markdown SUCCESS', (doc.id || ''), 'rev=', payload.rev);
    } catch (e) {
      console.error('[DOC] -> mindmap mw_load_markdown FAILED', (doc.id || ''), 'error:', e);
      console.warn('postMessage to mindmap failed', e);
    }
  } else {
    console.warn('[DOC] mw_notifyMindmapLoad iframe not ready, caching payload for later');
    try {
      window.__mw_pendingMindmapMarkdown = payload;
      console.log('[DOC] mw_notifyMindmapLoad cached payload for iframe onload');
    } catch (e) {
      console.error('[DOC] mw_notifyMindmapLoad failed to cache payload:', e);
    }
  }

  console.log('[DOC] mw_notifyMindmapLoad completed');
}

// ===== 导出为ZIP（单文档/全部） =====
async function mw_exportDocZip(id) {
  const docs = mw_loadDocs();
  const doc = docs.find(d => d.id === id);
  if (!doc) return alert('文档不存在');
  const zip = new JSZip();
  const safeName = (doc.name || 'document').replace(/[\\/:*?"<>|]+/g, '_');
  const root = zip.folder(safeName);

  // md
  root.file('index.md', doc.md || '');

  // images
  if (doc.images && doc.images.length) {
    const imgFolder = root.folder('images');

    // 从IndexedDB获取图片数据
    let imagesMap;
    if (window.imageStorage) {
      try {
        imagesMap = await window.imageStorage.getImagesMap();
      } catch (error) {
        console.warn('从IndexedDB获取图片失败:', error);
        imagesMap = new Map();
      }
    } else {
      imagesMap = new Map();
    }

    for (let i = 0; i < doc.images.length; i++) {
      const img = doc.images[i];

      // 优先从IndexedDB获取图片数据，如果没有则使用文档中的数据
      let imageData = imagesMap.get(img.id);
      if (!imageData && img.dataUrl) {
        imageData = img;
      }

      if (!imageData || !imageData.dataUrl) {
        console.warn(`导出图片失败: 图片 ${img.id} 数据不可用`);
        continue;
      }

      // 生成唯一的文件名，优先使用图片ID，确保与markdown引用保持一致
      let fname;
      if (img.id) {
        // 如果有ID，直接使用ID作为文件名，保持与markdown引用一致
        fname = img.id + '.png';
      } else if (img.name) {
        // 如果有名字，使用名字
        fname = img.name;
      } else {
        // 如果都没有，生成带索引的唯一名称
        fname = 'img_' + i + '_' + Date.now() + '.png';
      }

      // 确保文件名唯一（防止多个图片同名）
      const baseName = fname.replace(/\.[^.]+$/, '');
      const ext = fname.match(/\.[^.]+$/) ? fname.match(/\.[^.]+$/)[0] : '.png';
      let finalName = fname;
      let counter = 1;

      // 检查文件名是否已存在，如果存在则添加序号
      while (imgFolder.file(finalName)) {
        finalName = baseName + '_' + counter + ext;
        counter++;
      }

      // 将 dataURL 转为二进制
      const blob = await window.imageStorage.dataUrlToBlob(imageData.dataUrl);
      const ab = await blob.arrayBuffer();
      imgFolder.file(finalName, ab);

      console.log('mw_exportDocZip: 导出图片', finalName, '原ID:', img.id, '原name:', img.name);
    }
  }



  // meta
  root.file('meta.json', JSON.stringify({
    id: doc.id,
    name: doc.name,
    version: doc.version || 1,
    exportedAt: Date.now()
  }, null, 2));

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, safeName + '.zip');
  try { showSuccess && showSuccess('ZIP 导出完成'); } catch (_) { }
}

// 导出全部为 ZIP
async function mw_exportAllZip() {
  const docs = mw_loadDocs();
  if (!docs.length) return alert('没有文档可导出');

  const loadingMsg = "正在打包 " + docs.length + " 个文档...";
  try { showInfo && showInfo(loadingMsg, 2000); } catch (_) { }

  const zip = new JSZip();

  // 1. 导出 AI 辅助配置
  const aiFolder = zip.folder('ai');
  const aiCfg = mw_fetchAIPlatformConfigsSnapshot();
  if (aiCfg) aiFolder.file('platform-configs.json', JSON.stringify(aiCfg, null, 2));

  let myPromptTemplates = [];
  try {
    const stored = localStorage.getItem('myPromptTemplates');
    if (stored) myPromptTemplates = JSON.parse(stored);
  } catch (e) { console.warn('Export templates warning:', e); }

  if (myPromptTemplates && myPromptTemplates.length > 0) {
    aiFolder.file('my-prompt-templates.json', JSON.stringify(myPromptTemplates, null, 2));
  }

  // 2. 循环导出每个文档
  for (const doc of docs) {
    // 安全的文件名处理
    let safeName = (doc.name || 'document').replace(/[\\/:*?"<>|]+/g, '_').trim();
    if (!safeName) safeName = "Untitled_" + doc.id;

    // 为每个文档创建一个文件夹
    const root = zip.folder(safeName);
    root.file('index.md', doc.md || '');

    // 获取该文档的完整图片数据
    let imagesMap = {};
    if (window.imageStorage && window.imageStorage.getImagesMap) {
      try {
        const mapResult = await window.imageStorage.getImagesMap(doc.id);
        console.log('mw_exportAllZip: 获取到的imagesMap', {
          docId: doc.id,
          isMap: mapResult instanceof Map,
          size: mapResult.size || Object.keys(mapResult).length,
          firstKey: mapResult.keys ? mapResult.keys().next().value : Object.keys(mapResult)[0],
          firstImage: mapResult.get ? mapResult.get(mapResult.keys().next().value) : mapResult[Object.keys(mapResult)[0]]
        });

        // 如果是Map对象，转换为普通对象
        if (mapResult instanceof Map) {
          imagesMap = {};
          for (const [key, value] of mapResult.entries()) {
            imagesMap[key] = value;
          }
        } else {
          imagesMap = mapResult;
        }
      } catch (err) {
        console.error('获取图片数据失败:', err);
      }
    }

    // 处理图片导出
    if (doc.images && Array.isArray(doc.images) && doc.images.length > 0) {
      const imgFolder = root.folder('images');
      for (let i = 0; i < doc.images.length; i++) {
        const img = doc.images[i];
        // 生成唯一的文件名，优先使用图片ID，确保与markdown引用保持一致
        let fname;
        if (img.id) {
          // 如果有ID，直接使用ID作为文件名，保持与markdown引用一致
          fname = img.id + '.png';
        } else if (img.name) {
          // 如果有名字，使用名字
          fname = img.name;
        } else {
          // 如果都没有，生成带索引的唯一名称
          fname = 'img_' + i + '_' + Date.now() + '.png';
        }

        // 确保文件名唯一（防止多个图片同名）
        const baseName = fname.replace(/\.[^.]+$/, '');
        const ext = fname.match(/\.[^.]+$/) ? fname.match(/\.[^.]+$/)[0] : '.png';
        let finalName = fname;
        let counter = 1;

        // 检查文件名是否已存在，如果存在则添加序号
        while (imgFolder.file(finalName)) {
          finalName = baseName + '_' + counter + ext;
          counter++;
        }

        try {
          // 从imagesMap获取完整的图片数据
          const imageData = imagesMap[img.id] || img;
          console.log('mw_exportAllZip: 图片数据', {
            id: img.id,
            hasDataUrl: !!imageData.dataUrl,
            dataUrlLength: imageData.dataUrl ? imageData.dataUrl.length : 0,
            dataUrlPrefix: imageData.dataUrl ? imageData.dataUrl.substring(0, 50) + '...' : 'null'
          });

          // dataUrl 转 Blob 再转 ArrayBuffer
          const blob = await window.imageStorage.dataUrlToBlob(imageData.dataUrl || '');
          console.log('mw_exportAllZip: 转换后的Blob', {
            size: blob.size,
            type: blob.type
          });

          const ab = await blob.arrayBuffer();
          console.log('mw_exportAllZip: 转换后的ArrayBuffer', {
            byteLength: ab.byteLength
          });

          imgFolder.file(finalName, ab);
          console.log('mw_exportAllZip: 导出图片', finalName, '文档:', safeName, '原ID:', img.id, '原name:', img.name);
        } catch (err) {
          console.error(`导出图片 ${finalName} 失败:`, err);
        }
      }
    }

    // 导出元数据
    root.file('meta.json', JSON.stringify({
      id: doc.id,
      name: doc.name,
      version: doc.version || 1,
      updatedAt: doc.updatedAt
    }, null, 2));
  }

  // 生成并下载
  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, 'MindWord_AllDocs.zip');
  try { showSuccess && showSuccess('全部 ZIP 导出完成'); } catch (_) { }
}

// ===== 导入ZIP（支持多文档） =====
async function mw_importZip(file) {
  if (!file) return;
  const zip = await JSZip.loadAsync(file);

  // 兼容多种压缩器的路径格式：收集 zip.files 中的所有顶级文件夹（去重）
  const topFolderSet = new Set();
  Object.keys(zip.files).forEach(name => {
    if (!name) return;
    const parts = name.split('/');
    if (parts.length > 1 && parts[0].trim()) {
      topFolderSet.add(parts[0].trim() + '/');
    } else if (name.endsWith('/') && !name.slice(0, -1).includes('/')) {
      // 兼容只有目录条目的情况（例如某些工具会仅保留目录 entry）
      topFolderSet.add(name);
    }
  });
  const topFolders = Array.from(topFolderSet);
  const docs = mw_loadDocs();

  // 新增：ID冲突处理相关变量
  let conflictResolution = null; // 用户选择的冲突处理方式: 'keep_latest', 'replace', 'create_new'
  const conflicts = []; // 存储检测到的冲突信息

  // 读取根级 ai 配置（若存在），并供所有文档复用。
  // 说明：导出的 AI 配置现在放在 ZIP 根目录的 ai/ 文件夹下（与各文档文件夹平级）。
  let rootAiCfg = null, rootTpl = null;
  try {
    const rootAiFolder = zip.folder('ai');
    if (rootAiFolder) {
      const cfg = rootAiFolder.file('platform-configs.json');
      const tpf = rootAiFolder.file('prompt-templates.json');
      const myTpf = rootAiFolder.file('my-prompt-templates.json');
      if (cfg) try { rootAiCfg = JSON.parse(await cfg.async('string')); } catch (_) { console.warn('mw_importZip: parse root platform-configs.json failed'); }
      if (tpf) try { rootTpl = JSON.parse(await tpf.async('string')); } catch (_) { console.warn('mw_importZip: parse root prompt-templates.json failed'); }
      if (myTpf) {
        try {
          const myTemplates = JSON.parse(await myTpf.async('string'));
          if (myTemplates && myTemplates.length > 0) {
            // 将myPromptTemplates保存到localStorage
            localStorage.setItem('myPromptTemplates', JSON.stringify(myTemplates));
            console.log('mw_importZip: 成功导入my-prompt-templates.json');
          }
        } catch (_) {
          console.warn('mw_importZip: parse root my-prompt-templates.json failed');
        }
      }
    }
  } catch (err) {
    console.warn('mw_importZip: read root ai folder failed', err);
  }

  // 若没有顶级文件夹，尝试单文档（直接 index.md）
  const processOne = async (folderName) => {
    const folder = zip.folder(folderName);
    const mdFile = folder.file('index.md');
    if (!mdFile) return;
    const md = await mdFile.async('string');

    // 尝试读取meta.json获取原始ID
    let originalId = null;
    let originalName = null;
    let originalVersion = 1;
    let originalUpdatedAt = null;
    try {
      const metaFile = folder.file('meta.json');
      if (metaFile) {
        const metaContent = await metaFile.async('string');
        const meta = JSON.parse(metaContent);
        originalId = meta.id;
        originalName = meta.name;
        originalVersion = meta.version || 1;
        originalUpdatedAt = meta.updatedAt;
        console.log('mw_importZip: 从meta.json读取到原始ID:', originalId, '名称:', originalName, '更新时间:', originalUpdatedAt);
      }
    } catch (err) {
      console.warn('mw_importZip: 读取meta.json失败，将使用新ID:', err);
    }

    // 只在有图片文件时才处理图片相关逻辑
    let images = [];

    // 从markdown内容中提取图片引用，建立图片ID到图片ID的映射（用于后续查找）
    const imageIdMap = new Map();
    const imageRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
    let match;
    while ((match = imageRegex.exec(md)) !== null) {
      const imageName = match[1]; // 图片名称
      const imageId = match[2]; // 图片ID
      if (imageId && !imageId.match(/^(https?:\/\/|data:)/)) {
        // 建立图片ID到自身的映射，用于后续通过文件名（不含扩展名）查找
        imageIdMap.set(imageId, imageId);
        console.log('mw_importZip: 发现图片引用', imageName, '->', imageId);
      }
    }

    // 检查是否有图片文件（不依赖folder方法，直接扫描所有文件）
    const imageFiles = [];
    const folderPrefix = folderName ? folderName : '';
    const imagesPrefix = folderPrefix + (folderPrefix.endsWith('/') ? '' : '/') + 'images/';

    // 遍历zip中的所有文件，找到属于当前文档的图片文件
    Object.values(zip.files).forEach(file => {
      if (file.dir) return;
      const fileName = file.name;
      if (fileName.startsWith(imagesPrefix)) {
        imageFiles.push(file);
        console.log('mw_importZip: 发现图片文件', fileName);
      }
    });

    // 如果有图片文件，才进行处理
    if (imageFiles.length > 0) {
      for (const entry of imageFiles) {
        try {
          const fullName = entry.name || '';
          const mime = mw_guessMime(fullName);

          // 只处理图片文件，过滤掉非图片文件（如meta.json、index.md等）
          if (!mime.startsWith('image/')) {
            console.log('mw_importZip: 跳过非图片文件', fullName);
            continue;
          }

          // entry 本身就是 JSZip 的 file 对象 —— 直接调用其 async 方法更稳健
          const ab = await entry.async('arraybuffer');
          // 将arrayBuffer转换为DataURL
          const dataUrl = await window.imageStorage.blobToDataUrl(new Blob([ab], { type: mime }));
          // 只保留文件名，不带路径
          const fname = fullName.split('/').pop() || fullName;

          // 优先使用markdown中已有的图片ID，通过文件名（不含扩展名）匹配
          const fileNameWithoutExt = fname.replace(/\.[^.]+$/, ''); // 移除扩展名
          let imageId = imageIdMap.get(fileNameWithoutExt);
          if (!imageId) {
            imageId = 'img_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
            console.log('mw_importZip: 生成新图片ID', fname, '->', imageId);
          } else {
            console.log('mw_importZip: 使用现有图片ID', fname, '->', imageId);
          }

          // 将图片保存到IndexedDB，只在文档中保存基本信息
          if (window.imageStorage) {
            try {
              // 将dataUrl转换为Blob
              const blob = await window.imageStorage.dataUrlToBlob(dataUrl);

              // 获取当前文档ID
              const docId = originalId || ('doc_' + Date.now() + '_' + Math.floor(Math.random() * 1000));

              await window.imageStorage.saveImage(imageId, blob, {
                name: fname,
                type: mime,
                documentId: docId
              });
              console.log('mw_importZip: 图片已保存到IndexedDB', imageId);
            } catch (error) {
              console.warn('mw_importZip: 保存图片到IndexedDB失败', imageId, error);
            }
          }

          // 只在文档中保存图片基本信息，不保存dataUrl
          images.push({ id: imageId, name: fname, mime });
        } catch (err) {
          console.warn('mw_importZip: 读取图片条目失败，已跳过', entry && entry.name, err);
        }
      }
    }
    // AI配置信息不应该存储在单个文档中，它们是全局配置
    // 从上层预读取的 rootAiCfg / rootTpl 直接复用（避免查找已被移除的子文件夹）
    let aiCfg = rootAiCfg;
    let tpl = rootTpl;
    // 说明：旧的子文件夹兼容逻辑已弃用，故不再尝试 folder.folder('ai')，以避免覆盖或读取失败。
    const safeName = originalName || folderName.replace(/\/$/, '').replace(/[\\/:*?"<>|]+/g, '_');

    // ID冲突检测和处理
    let finalId = originalId || ('doc_' + Date.now() + '_' + Math.floor(Math.random() * 1000));
    let finalName = safeName || '导入文档';
    let finalUpdatedAt = Date.now();

    if (originalId) {
      // 检查本地是否已存在相同ID的文档
      const existingDoc = docs.find(d => d.id === originalId);
      if (existingDoc) {
        // 发现ID冲突
        if (conflictResolution === null) {
          // 第一次发现冲突，显示选择对话框
          conflicts.push({
            id: originalId,
            localName: existingDoc.name,
            importName: safeName,
            localTime: existingDoc.updatedAt || 0,
            importTime: originalUpdatedAt || Date.now()
          });
          conflictResolution = await showImportConflictDialog(conflicts);
        }

        // 根据用户选择处理冲突
        switch (conflictResolution) {
          case 'keep_latest':
            // 保留最新的（比较updatedAt）
            const existingTime = existingDoc.updatedAt || 0;
            const importTime = originalUpdatedAt || Date.now();
            if (importTime > existingTime) {
              // 导入的文档更新，替换现有文档
              console.log('mw_importZip: 保留最新文档，替换现有文档:', originalId);
              // 移除现有文档，使用导入的文档
              docs.splice(docs.indexOf(existingDoc), 1);
            } else {
              // 现有文档更新，跳过导入
              console.log('mw_importZip: 现有文档更新，跳过导入:', originalId);
              return;
            }
            break;

          case 'replace':
            // 替换为导入的文档
            console.log('mw_importZip: 替换为导入文档:', originalId);
            docs.splice(docs.indexOf(existingDoc), 1);
            break;

          case 'create_new':
            // 创建新ID
            finalId = 'doc_' + Date.now() + '_' + Math.floor(Math.random() * 1000);
            finalName = (safeName || '导入文档') + '_副本';
            console.log('mw_importZip: 创建新ID文档:', finalId, '名称:', finalName);
            break;

          default:
            // 默认跳过
            console.log('mw_importZip: 默认跳过冲突文档:', originalId);
            return;
        }
      }
    }

    // 创建文档对象，不再包含AI配置信息（它们应该存储在独立的localStorage键中）
    const newDoc = {
      id: finalId,
      name: finalName,
      md,
      images,
      createdAt: Date.now(),
      updatedAt: finalUpdatedAt,
      version: originalVersion
    };
    docs.push(newDoc);
  };

  if (topFolders.length) {
    for (const folderName of topFolders) { await processOne(folderName); }
  } else {
    // 尝试根级 index.md
    const mdFile = zip.file('index.md');
    if (mdFile) await processOne('');
  }

  mw_saveDocs(docs);
  mw_renderList();
  try { showSuccess && showSuccess('ZIP 导入完成'); } catch (_) { }

  // 如果解析到了根级 AI 配置，则写入面板期望的 localStorage 并尝试刷新 AI 面板
  try {
    if (rootAiCfg) {
      try { localStorage.setItem('allAIPlatformConfigs', JSON.stringify(rootAiCfg)); } catch (e) { console.warn('[mw_importZip] write allAIPlatformConfigs failed', e); }
    }
    // 不再导入旧的prompt-templates.json，只导入用户自定义的my-prompt-templates.json
    // if (rootTpl) {
    //     try { localStorage.setItem('promptTemplates', JSON.stringify(rootTpl)); } catch (e) { console.warn('[mw_importZip] write promptTemplates failed', e); }
    // }

    // 尝试刷新同源的 aiModalFrame（如果可访问）
    try {
      var af = document.getElementById('aiModalFrame');
      if (af && af.contentWindow) {
        try {
          af.contentWindow.populateSavedPlatformsList && af.contentWindow.populateSavedPlatformsList();
          af.contentWindow.populateUsagePlatforms && af.contentWindow.populateUsagePlatforms();
          af.contentWindow.populateTemplateSelect && af.contentWindow.populateTemplateSelect();
        } catch (e) { console.warn('[mw_importZip] refresh aiModalFrame failed', e); }
      } else {
        // 回退：发送 postMessage，由 AI 面板监听并自行写入/刷新（若已实现监听）
        // 不再发送旧的templates数据，只发送configs
        window.postMessage({ type: 'IMPORT_AI_FROM_ZIP', payload: { configs: rootAiCfg, templates: null } }, '*');
      }
    } catch (e) { console.warn('[mw_importZip] notify ai panel failed', e); }
  } catch (e) {
    console.warn('[mw_importZip] write ai configs failed', e);
  }
}

// ===== 辅助函数 =====
// 判断文档是否是自动生成的空文档（没有真实子节点）
function isAutoGeneratedEmptyDoc(doc) {
  if (!doc) return false;

  // 检查名称是否为默认的"未命名文档"
  const name = doc.name || '';
  if (name !== '未命名文档') return false;

  // 检查内容是否为默认的"# 未命名文档\n"
  const md = doc.md || '';
  if (md.trim() !== '# 未命名文档') return false;

  // 检查是否有图片（空文档不应该有图片）
  if (doc.images && doc.images.length > 0) return false;

  return true;
}

function mw_extractTitleFromMd(md) {
  try {
    const lines = String(md || '').split(/\r?\n/);
    const first = (lines.find(l => l.trim().length > 0) || '').trim();
    if (!first) return '未命名文档';
    const cleaned = first
      .replace(/^#{1,6}\s*/, '')
      .replace(/^[-*+]\s+/, '')
      .replace(/^\d+\.\s+/, '')
      .trim();
    return cleaned || '未命名文档';
  } catch (_) { return '未命名文档'; }
}
function mw_guessMime(name) {
  const lower = (name || '').toLowerCase();
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.gif')) return 'image/gif';
  if (lower.endsWith('.webp')) return 'image/webp';
  return 'application/octet-stream';
}
function mw_fetchAIPlatformConfigsSnapshot() {
  try {
    const frame = document.getElementById('aiModalFrame');
    const ls = frame && frame.contentWindow && frame.contentWindow.localStorage;
    if (!ls) return null;
    const raw = ls.getItem('allAIPlatformConfigs');
    if (!raw) return null;
    const json = JSON.parse(raw);
    return json;
  } catch (_) { return null; }
}
function mw_fetchAIPromptTemplatesSnapshot() {
  try {
    return window.__prompt_templates || null;
  } catch (_) { return null; }
}

// ===== ZIP导入冲突处理相关函数 =====
// 显示ID冲突选择对话框
async function showImportConflictDialog(conflicts) {
  if (!conflicts || conflicts.length === 0) return 'keep_latest';

  return new Promise((resolve) => {
    const conflictList = conflicts.map(conflict =>
      `文档：${conflict.importName}\n` +
      `文档ID：${conflict.id}\n` +
      `本地修改时间：${new Date(conflict.localTime).toLocaleString()}\n` +
      `导入修改时间：${new Date(conflict.importTime).toLocaleString()}\n`
    ).join('\n---\n\n');

    const message = `检测到文档冲突：\n\n${conflictList}\n` +
      '请选择处理方式：\n\n' +
      '【保留最新的】保留修改时间较新的文档（推荐）\n' +
      '【替换为导入的】用导入的文档完全替换现有文档\n' +
      '【另外创建】为导入的文档生成新ID，保留两份文档\n\n' +
      '注意：您的选择将应用于本次导入的所有冲突文档。';

    // 创建自定义对话框
    const dialog = document.createElement('div');
    dialog.style.cssText = `
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    background: rgba(0,0,0,0.5);
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    z-index: 10000;
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                `;

    const content = document.createElement('div');
    content.style.cssText = `
                    background: white;
                    border-radius: 8px;
                    padding: 24px;
                    max-width: 600px;
                    max-height: 80vh;
                    overflow-y: auto;
                    box-shadow: 0 10px 25px rgba(0,0,0,0.2);
                    border: 1px solid #e5e7eb;
                `;

    const title = document.createElement('h3');
    title.textContent = '文档导入冲突处理';
    title.style.cssText = `
                    margin: 0 0 16px 0;
                    color: #1f2937;
                    font-size: 18px;
                    font-weight: 600;
                `;

    const messageDiv = document.createElement('div');
    messageDiv.style.cssText = `
                    white-space: pre-line;
                    margin-bottom: 24px;
                    color: #4b5563;
                    font-size: 14px;
                    line-height: 1.5;
                `;
    messageDiv.textContent = message;

    const buttonContainer = document.createElement('div');
    buttonContainer.style.cssText = `
                    display: flex;
                    gap: 12px;
                    justify-content: flex-end;
                    margin-top: 20px;
                `;

    const createButton = (text, value, isPrimary = false) => {
      const btn = document.createElement('button');
      btn.textContent = text;
      btn.style.cssText = `
                        padding: 8px 16px;
                        border: 1px solid ${isPrimary ? '#3b82f6' : '#d1d5db'};
                        background: ${isPrimary ? '#3b82f6' : 'white'};
                        color: ${isPrimary ? 'white' : '#374151'};
                        border-radius: 6px;
                        font-size: 14px;
                        cursor: pointer;
                        transition: all 0.2s;
                        font-weight: 500;
                    `;
      btn.onmouseover = () => {
        btn.style.background = isPrimary ? '#2563eb' : '#f9fafb';
        btn.style.borderColor = isPrimary ? '#2563eb' : '#9ca3af';
      };
      btn.onmouseout = () => {
        btn.style.background = isPrimary ? '#3b82f6' : 'white';
        btn.style.borderColor = isPrimary ? '#3b82f6' : '#d1d5db';
      };
      btn.onclick = () => {
        document.body.removeChild(dialog);
        resolve(value);
      };
      return btn;
    };

    // 创建三个按钮
    const keepLatestBtn = createButton('保留最新的', 'keep_latest', true);
    const replaceBtn = createButton('替换为导入的', 'replace');
    const createNewBtn = createButton('另外创建', 'create_new');

    buttonContainer.appendChild(createNewBtn);
    buttonContainer.appendChild(replaceBtn);
    buttonContainer.appendChild(keepLatestBtn);

    content.appendChild(title);
    content.appendChild(messageDiv);
    content.appendChild(buttonContainer);
    dialog.appendChild(content);

    document.body.appendChild(dialog);

    // 点击背景关闭对话框（默认选择保留最新的）
    dialog.onclick = (e) => {
      if (e.target === dialog) {
        document.body.removeChild(dialog);
        resolve('keep_latest');
      }
    };

    // ESC键关闭对话框
    const handleEscape = (e) => {
      if (e.key === 'Escape') {
        document.body.removeChild(dialog);
        document.removeEventListener('keydown', handleEscape);
        resolve('keep_latest');
      }
    };
    document.addEventListener('keydown', handleEscape);
  });
}

// 处理单个文档的ID冲突
function resolveDocIdConflict(existingDoc, importDoc, resolution) {
  switch (resolution) {
    case 'keep_latest':
      // 保留修改时间较新的文档
      if (Number(existingDoc.updatedAt) >= Number(importDoc.updatedAt)) {
        return { action: 'skip', doc: existingDoc };
      } else {
        return { action: 'replace', doc: importDoc };
      }
    case 'replace':
      // 总是用导入的文档替换
      return { action: 'replace', doc: importDoc };
    case 'create_new':
      // 为导入文档生成新ID
      const newDoc = { ...importDoc };
      newDoc.id = 'doc_' + Date.now() + '_' + Math.floor(Math.random() * 1000);
      return { action: 'create', doc: newDoc };
    default:
      return { action: 'skip', doc: existingDoc };
  }
}

// ===== 清空所有本地数据 =====
async function mw_clearAllData() {
  if (confirm('⚠️ 警告：此操作将永久删除所有本地数据！\n\n确认要清空以下数据吗？\n• 所有文档数据\n• AI平台配置\n• 提示词模板\n• 编辑器设置\n• 所有图片数据\n\n此操作不可恢复，建议先导出备份。')) {
    try {
      // 清空所有localStorage数据
      localStorage.clear();

      // 清空IndexedDB中的所有图片
      if (window.imageStorage) {
        await window.imageStorage.clearAllImages();
      }

      // 重新初始化必要的数据结构
      localStorage.setItem('mindword_docs', '[]');
      localStorage.setItem('mw_active_doc', '');

      // 刷新界面
      mw_renderList();

      // 通知编辑器清空内容
      window.postMessage({ type: 'mw_apply_markdown', payload: { md: '', images: [] } }, '*');

      // 显示成功消息
      try { showSuccess && showSuccess('所有本地数据已清空'); } catch (_) { }

      console.log('所有本地数据已清空');
    } catch (error) {
      console.error('清空数据失败:', error);
      try { showError && showError('清空数据失败: ' + error.message); } catch (_) { }
    }
  }
}

// ===== 事件绑定 =====
(function initDocSidebar() {
  const btn = document.getElementById('doc-menu-btn');
  const closeBtn = document.getElementById('btn-close-sidebar');
  const newBtn = document.getElementById('btn-new-doc');
  const exportAllBtn = document.getElementById('btn-export-all');
  const importInput = document.getElementById('import-zip-input');
  const importBtn = document.getElementById('btn-import-zip');
  const clearDataBtn = document.getElementById('btn-clear-data');
  const batchModeBtn = document.getElementById('btn-batch-mode');
  const batchSelectAllBtn = document.getElementById('btn-batch-select-all');
  const batchSelectNoneBtn = document.getElementById('btn-batch-select-none');
  const batchDeleteBtn = document.getElementById('btn-batch-delete');
  const batchCancelBtn = document.getElementById('btn-batch-cancel');
  const sidebar = document.getElementById('doc-sidebar');

  btn && (btn.onclick = () => { mw_toggleSidebar(); mw_renderList(); });
  closeBtn && (closeBtn.onclick = () => mw_toggleSidebar(false));
  newBtn && (newBtn.onclick = () => mw_newDoc());
  exportAllBtn && (exportAllBtn.onclick = () => mw_exportAllZip());
  importBtn && (importBtn.onclick = () => importInput && importInput.click());
  importInput && importInput.addEventListener('change', (e) => {
    const f = e.target.files && e.target.files[0];
    if (f) mw_importZip(f);
    e.target.value = '';
  });
  clearDataBtn && (clearDataBtn.onclick = () => mw_clearAllData());
  batchModeBtn && (batchModeBtn.onclick = () => mw_enterBatchMode());
  batchSelectAllBtn && (batchSelectAllBtn.onclick = () => mw_selectAllDocs());
  batchSelectNoneBtn && (batchSelectNoneBtn.onclick = () => mw_selectNoneDocs());
  batchDeleteBtn && (batchDeleteBtn.onclick = () => mw_batchDeleteDocs());
  batchCancelBtn && (batchCancelBtn.onclick = () => mw_exitBatchMode());

  // 侧滑栏失去焦点时自动收起
  if (sidebar) {
    sidebar.addEventListener('blur', function (e) {
      // 检查新的焦点元素是否在侧滑栏内部
      setTimeout(() => {
        const activeElement = document.activeElement;
        const isFocusInsideSidebar = sidebar.contains(activeElement);
        const isFocusOnMenuBtn = activeElement === btn;

        // 如果焦点不在侧滑栏内且不在菜单按钮上，则收起侧滑栏
        if (!isFocusInsideSidebar && !isFocusOnMenuBtn) {
          mw_toggleSidebar(false);
        }
      }, 0);
    });

    // 为侧滑栏内的可交互元素添加焦点管理
    sidebar.addEventListener('focusin', function (e) {
      // 当侧滑栏内获得焦点时，确保侧滑栏保持打开状态
      if (!sidebar.classList.contains('open')) {
        mw_toggleSidebar(true);
      }
    });
  }

  // 点击外部区域（包括iframe）自动收起侧滑栏
  function setupClickOutsideHandler() {
    let isProcessingClick = false;

    // 处理点击事件
    function handleClickOutside(event) {
      if (isProcessingClick) return;

      const sidebar = document.getElementById('doc-sidebar');
      const menuBtn = document.getElementById('doc-menu-btn');

      if (!sidebar || !sidebar.classList.contains('open')) return;

      // 检查点击是否在侧滑栏内部或菜单按钮上
      const isClickInsideSidebar = sidebar.contains(event.target);
      const isClickOnMenuBtn = menuBtn && (event.target === menuBtn || menuBtn.contains(event.target));

      if (!isClickInsideSidebar && !isClickOnMenuBtn) {
        isProcessingClick = true;
        mw_toggleSidebar(false);
        setTimeout(() => { isProcessingClick = false; }, 100);
      }
    }

    // 处理窗口失焦事件（处理iframe点击）
    function handleWindowBlur() {
      const sidebar = document.getElementById('doc-sidebar');
      if (sidebar && sidebar.classList.contains('open')) {
        // 延迟检查，确保iframe点击被捕获
        setTimeout(() => {
          mw_toggleSidebar(false);
        }, 50);
      }
    }

    // 绑定事件
    document.addEventListener('click', handleClickOutside, true);
    window.addEventListener('blur', handleWindowBlur);

    // 返回清理函数
    return function cleanup() {
      document.removeEventListener('click', handleClickOutside, true);
      window.removeEventListener('blur', handleWindowBlur);
    };
  }

  // 初始化点击外部区域处理
  const cleanupClickHandler = setupClickOutsideHandler();

  // 页面卸载时清理事件监听
  window.addEventListener('beforeunload', cleanupClickHandler);

  // 初始渲染一次（不强制打开）
  mw_renderList();
})();

// 监听来自编辑器的文档更新消息
window.addEventListener('message', function (e) {
  const msg = e && e.data;
  if (!msg || typeof msg !== 'object') return;

  // 1. 编辑器内容变更同步 (修复图片丢失和导出无图片的核心)
  // 当 editor.html 执行 saveToStorage 时会发送此消息
  if (msg.type === 'mw_document_changed') {
    const payload = msg.payload || {};
    // 获取目标文档ID，优先使用payload里的ID，否则使用当前活动ID
    const targetId = payload.id || mw_getActive();

    if (targetId) {
      const docs = mw_loadDocs();
      const idx = docs.findIndex(d => d.id === targetId);

      if (idx >= 0) {
        // 更新主数据库中的文档数据
        docs[idx].md = payload.md;

        // 关键：同步图片数据到IndexedDB
        if (window.imageStorage && Array.isArray(payload.images)) {
          // 将图片数据保存到IndexedDB
          const imagesMap = new Map();
          payload.images.forEach(img => {
            if (img.id && img.dataUrl) {
              imagesMap.set(img.id, {
                id: img.id,
                name: img.name,
                mime: img.mime,
                dataUrl: img.dataUrl
              });
            }
          });

          if (imagesMap.size > 0) {
            // 为每个图片添加文档ID并转换数据格式
            const imagesWithDocId = new Map();
            for (const [id, imageData] of imagesMap.entries()) {
              imagesWithDocId.set(id, {
                id: imageData.id,
                name: imageData.name,
                type: imageData.mime,  // 将 mime 转换为 type
                data: imageData.dataUrl, // 将 dataUrl 转换为 data
                documentId: targetId
              });
            }
            window.imageStorage.saveImages(imagesWithDocId).catch(error => {
              console.warn('保存图片到IndexedDB失败:', error);
            });
          }
        }

        // 更新文档中的图片引用（只保留基本信息，不存储dataUrl）
        docs[idx].images = Array.isArray(payload.images) ? payload.images.map(img => ({
          id: img.id,
          name: img.name,
          mime: img.mime
        })) : [];

        docs[idx].updatedAt = Date.now();

        // 如果版本号存在则更新
        if (payload.rev) {
          docs[idx].version = payload.rev;
        }

        // 尝试更新文档标题（如果内容变了）
        const newName = mw_extractTitleFromMd(payload.md);
        if (newName && docs[idx].name !== newName) {
          docs[idx].name = newName;
        }

        mw_saveDocs(docs);

        // 如果处于非批量模式，刷新列表以更新标题或选中状态
        const isBatchMode = document.getElementById('batch-actions').classList.contains('show');
        if (!isBatchMode) {
          mw_renderList();
        }

        console.log(`[SYNC] 文档 ${targetId} 已同步至主数据库 (含 ${docs[idx].images.length} 张图片)`);
      }
    }
    return;
  }

  // 2. 编辑器请求当前活动文档（如编辑器iframe刷新后）
  if (msg.type === 'mw_request_active') {
    const activeId = mw_getActive();
    if (!activeId) return;
    const docs = mw_loadDocs();
    const doc = docs.find(d => d.id === activeId);
    if (doc) mw_notifyEditorLoad(doc);
    return;
  }

  // 3. 来自 AI 或其他插件的 "应用 Markdown" 请求
  // 效果：立即更新本地文档库并同时广播给 editor / preview / mindmap
  if (msg.type === 'mw_apply_markdown') {
    try {
      const payload = msg.payload || {};
      const md = typeof payload.md === 'string' ? payload.md : '';
      const images = Array.isArray(payload.images) ? payload.images : [];
      let docs = mw_loadDocs();
      const activeId = mw_getActive();

      if (activeId) {
        const idx = docs.findIndex(d => d.id === activeId);
        if (idx >= 0) {
          // 覆盖当前活动文档
          docs[idx].md = md;

          // 同步图片数据到IndexedDB
          if (window.imageStorage && Array.isArray(images)) {
            const imagesMap = new Map();
            images.forEach(img => {
              if (img.id && img.dataUrl) {
                imagesMap.set(img.id, {
                  id: img.id,
                  name: img.name,
                  mime: img.mime,
                  dataUrl: img.dataUrl
                });
              }
            });

            if (imagesMap.size > 0) {
              // 为每个图片添加文档ID
              const imagesWithDocId = new Map();
              for (const [id, imageData] of imagesMap.entries()) {
                imagesWithDocId.set(id, {
                  id: imageData.id,
                  name: imageData.name,
                  type: imageData.mime,  // 将 mime 转换为 type
                  data: imageData.dataUrl, // 将 dataUrl 转换为 data
                  documentId: docs[idx].id
                });
              }
              window.imageStorage.saveImages(imagesWithDocId).catch(error => {
                console.warn('保存图片到IndexedDB失败:', error);
              });
            }
          }

          // 更新文档中的图片引用（只保留基本信息）
          docs[idx].images = Array.isArray(images) ? images.map(img => ({
            id: img.id,
            name: img.name,
            mime: img.mime
          })) : [];

          docs[idx].updatedAt = Date.now();
          docs[idx].version = (Number(docs[idx].version || 1) + 1);

          const newName = mw_extractTitleFromMd(md);
          if (newName && docs[idx].name !== newName) docs[idx].name = newName;

          mw_saveDocs(docs);
          mw_renderList();

          const doc = docs[idx];
          // 广播到三端
          mw_notifyEditorLoad(doc);
          mw_notifyPreviewLoad(doc);
          mw_notifyMindmapLoad(doc);
          try { showSuccess && showSuccess('文档已更新'); } catch (_) { }
          return;
        }
      }

      // 无活动文档：创建新文档
      const newId = 'doc_' + Date.now();
      const name = mw_extractTitleFromMd(md || '');

      // 同步图片数据到IndexedDB
      if (window.imageStorage && Array.isArray(images)) {
        const imagesMap = new Map();
        images.forEach(img => {
          if (img.id && img.dataUrl) {
            imagesMap.set(img.id, {
              id: img.id,
              name: img.name,
              mime: img.mime,
              dataUrl: img.dataUrl
            });
          }
        });

        if (imagesMap.size > 0) {
          // 为每个图片添加新文档ID
          const imagesWithDocId = new Map();
          for (const [id, imageData] of imagesMap.entries()) {
            imagesWithDocId.set(id, {
              id: imageData.id,
              name: imageData.name,
              type: imageData.mime,  // 将 mime 转换为 type
              data: imageData.dataUrl, // 将 dataUrl 转换为 data
              documentId: newId
            });
          }
          window.imageStorage.saveImages(imagesWithDocId).catch(error => {
            console.warn('保存图片到IndexedDB失败:', error);
          });
        }
      }

      const doc = {
        id: newId,
        name,
        md: md || ('# ' + name + '\n'),
        images: Array.isArray(images) ? images.map(img => ({
          id: img.id,
          name: img.name,
          mime: img.mime
        })) : [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
        version: 1
      };
      docs.push(doc);
      mw_saveDocs(docs);
      mw_setActive(newId);
      mw_renderList();

      mw_notifyEditorLoad(doc);
      try { showSuccess && showSuccess('已创建新文档并应用'); } catch (_) { }
      return;
    } catch (err) {
      console.warn('[INDEX] mw_apply_markdown failed', err);
    }
  }

}, { passive: true });

// ===== 监听localStorage中markdown数据变化，自动更新文档标题 =====
let lastMarkdownData = localStorage.getItem('mindword_markdown_data');
let lastActiveDocId = mw_getActive();

// 检查markdown数据变化并更新文档标题
function checkMarkdownDataChange() {
  const currentMarkdownData = localStorage.getItem('mindword_markdown_data');
  const currentActiveId = mw_getActive();

  // 如果没有活动文档但有markdown数据，创建新文档
  if (!currentActiveId && currentMarkdownData && currentMarkdownData !== lastMarkdownData) {
    lastMarkdownData = currentMarkdownData;

    const docs = mw_loadDocs();
    const newId = 'doc_' + Date.now();
    const name = mw_extractTitleFromMd(currentMarkdownData) || '未命名文档';

    const doc = {
      id: newId,
      name,
      md: currentMarkdownData,
      images: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
      version: 1
    };

    docs.push(doc);
    mw_saveDocs(docs);
    mw_setActive(newId);
    mw_renderList();

    // 通知各面板加载新文档
    mw_notifyEditorLoad(doc);
    mw_notifyPreviewLoad(doc);
    mw_notifyMindmapLoad(doc);

    try { showSuccess && showSuccess('已创建新文档'); } catch (_) { }
    return;
  }

  // 检查是否有活动文档且markdown数据发生变化
  if (currentActiveId && currentMarkdownData !== lastMarkdownData) {
    lastMarkdownData = currentMarkdownData;

    const docs = mw_loadDocs();
    const idx = docs.findIndex(d => d.id === currentActiveId);

    if (idx >= 0 && currentMarkdownData) {
      // 更新md内容（核心修复）
      docs[idx].md = currentMarkdownData;
      docs[idx].updatedAt = Date.now();
      docs[idx].version = (Number(docs[idx].version || 1) + 1);

      // 提取新标题
      const newName = mw_extractTitleFromMd(currentMarkdownData);

      // 如果标题发生变化，更新文档信息
      if (newName && docs[idx].name !== newName) {
        docs[idx].name = newName;
      }

      // 保存文档列表并刷新显示
      mw_saveDocs(docs);
      mw_renderList();

      try { showSuccess && showSuccess('文档内容已更新'); } catch (_) { }
    }
  }

  // 检查活动文档是否发生变化
  if (currentActiveId !== lastActiveDocId) {
    lastActiveDocId = currentActiveId;
    lastMarkdownData = currentMarkdownData;
  }
}

// 设置localStorage监听器
window.addEventListener('storage', function (e) {
  if (e.key === 'mindword_markdown_data') {
    checkMarkdownDataChange();
  }
});

/**
 * 清理指定文档的未使用图片
 * @param {string} docId - 文档ID
 * @returns {Promise<Object>} 清理结果 {removed: number, message: string}
 */
async function mw_cleanupDocImages(docId) {
  if (!window.imageStorage) {
    throw new Error('图片存储管理器未初始化');
  }

  try {
    const docs = mw_loadDocs();
    const doc = docs.find(d => d.id === docId);
    if (!doc) {
      throw new Error('文档不存在');
    }

    // 从文档内容中提取所有图片ID
    const usedImageIds = new Set();
    const imageRegex = /!\[[^\]]*\]\(([^)]+)\)/g;
    let match;
    while ((match = imageRegex.exec(doc.md || '')) !== null) {
      const imageId = match[1];
      if (imageId && !imageId.match(/^(https?:\/\/|data:)/)) {
        usedImageIds.add(imageId);
      }
    }

    // 获取文档中存储的图片ID列表
    const docImageIds = new Set((doc.images || []).map(img => img.id));

    // 只获取当前文档的图片ID（通过documentId过滤）
    const allImagesMap = await window.imageStorage.getImagesMap(docId);
    const allImageIds = new Set(allImagesMap.keys());

    // 找出当前文档未使用的图片ID（在当前文档的IndexedDB中但不在文档内容中）
    const unusedImageIds = [];
    for (const imageId of allImageIds) {
      if (!usedImageIds.has(imageId)) {
        unusedImageIds.push(imageId);
      }
    }

    if (unusedImageIds.length === 0) {
      return { removed: 0, message: '没有需要清理的图片' };
    }

    // 删除未使用的图片
    let removedCount = 0;
    for (const imageId of unusedImageIds) {
      try {
        await window.imageStorage.deleteImage(imageId);
        removedCount++;
      } catch (error) {
        console.warn(`删除图片 ${imageId} 失败:`, error);
      }
    }

    // 更新文档中的图片列表，移除已删除的图片
    if (doc.images && doc.images.length > 0) {
      doc.images = doc.images.filter(img => !unusedImageIds.includes(img.id));
      doc.updatedAt = Date.now();
      doc.version = (Number(doc.version || 1) + 1);

      // 保存更新后的文档
      const docIndex = docs.findIndex(d => d.id === docId);
      if (docIndex >= 0) {
        docs[docIndex] = doc;
        mw_saveDocs(docs);
      }
    }

    const message = `已清理 ${removedCount} 张未使用图片`;
    try { showSuccess && showSuccess(message); } catch (_) { }

    return { removed: removedCount, message };
  } catch (error) {
    const errorMessage = `图片清理失败：${error.message}`;
    try { showError && showError(errorMessage); } catch (_) { }
    throw new Error(errorMessage);
  }
}

/**
 * 清理所有文档的未使用图片（跨文档清理）
 * @returns {Promise<Object>} 清理结果 {removed: number, message: string}
 */
async function mw_cleanupAllUnusedImages() {
  if (!window.imageStorage) {
    throw new Error('图片存储管理器未初始化');
  }

  try {
    const docs = mw_loadDocs();

    // 收集所有文档中使用的图片ID
    const allUsedImageIds = new Set();
    docs.forEach(doc => {
      if (doc.md) {
        const imageRegex = /!\[[^\]]*\]\(([^)]+)\)/g;
        let match;
        while ((match = imageRegex.exec(doc.md)) !== null) {
          const imageId = match[1];
          if (imageId && !imageId.match(/^(https?:\/\/|data:)/)) {
            allUsedImageIds.add(imageId);
          }
        }
      }
    });

    // 获取IndexedDB中的所有图片ID
    const allImagesMap = await window.imageStorage.getImagesMap();
    const allImageIds = new Set(allImagesMap.keys());

    // 找出完全未使用的图片ID（在所有文档中都不使用）
    const unusedImageIds = [];
    for (const imageId of allImageIds) {
      if (!allUsedImageIds.has(imageId)) {
        unusedImageIds.push(imageId);
      }
    }

    if (unusedImageIds.length === 0) {
      return { removed: 0, message: '没有需要清理的图片' };
    }

    // 删除未使用的图片
    let removedCount = 0;
    for (const imageId of unusedImageIds) {
      try {
        await window.imageStorage.deleteImage(imageId);
        removedCount++;
      } catch (error) {
        console.warn(`删除图片 ${imageId} 失败:`, error);
      }
    }

    const message = `已清理 ${removedCount} 张跨文档未使用图片`;
    try { showSuccess && showSuccess(message); } catch (_) { }

    return { removed: removedCount, message };
  } catch (error) {
    const errorMessage = `跨文档图片清理失败：${error.message}`;
    try { showError && showError(errorMessage); } catch (_) { }
    throw new Error(errorMessage);
  }
}

// 定期检查localStorage变化（用于同一页面内的变化）
setInterval(checkMarkdownDataChange, 1000);
