/**
 * MindWord - 树心 | 像画图一样写文档的思维导图写作工具
 * GitHub: https://github.com/TimiKays/MindWord
 * 
 * Copyright 2025 Timi Kays
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * LeanCloud Data 同步（中文模式）
 * 仅在语言为中文时启用 UI；提供：一键同步（智能分析）、清空云数据
 * 改进：支持文件大小检查（单图200KB，总量10M），分类型时间戳记录
 * 字段：docs(json), aiConfig(json), promptTemplates(json), 
 *       docUpdatedAt(number), configUpdatedAt(number), templateUpdatedAt(number)
 */
(function () {
  const LANG_KEY = 'mw_lang';
  const CLASS_NAME = 'MWData';
  let cachedCloudRaw = null;   // 缓存第一次 downloadCloud() 的原生对象

  // 文件大小限制
  const MAX_IMAGE_SIZE = 2 * 1024 * 1024; // 2MB
  const MAX_TOTAL_SIZE = 10 * 1024 * 1024; // 10M

  function getLang() {
    try { return localStorage.getItem(LANG_KEY) || 'zh'; } catch (_) { return 'zh'; }
  }

  // 新的合并算法：将云端数据合并到本地

  function isLoggedIn() {
    try { return !!(window.AV && AV.User && AV.User.current()); } catch (_) { return false; }
  }

  function getLocalDocs() { try { return (typeof mw_loadDocs === 'function') ? mw_loadDocs() : []; } catch (_) { return []; } }

  // 判断文档是否是自动生成的空文档（没有真实子节点）
  function isAutoGeneratedEmptyDoc(doc) {
    if (!doc) return false;

    // 检查名称是否为默认的"未命名文档"
    const name = doc.name || '';
    if (name !== '未命名文档') return false;

    // 检查内容是否为默认的"# 未命名文档\n"
    const md = doc.md || '';
    if (md.trim() !== '# 未命名文档') return false;

    // 检查是否有图片（空文档不应该有图片）
    if (doc.images && doc.images.length > 0) return false;

    return true;
  }

  /**
   * 比较两个图片数组是否相等
   * 只比较图片的基本信息（ID、名称、MIME类型），忽略dataUrl等可能变化的内容
   * @param {Array} localImages - 本地图片数组
   * @param {Array} cloudImages - 云端图片数组
   * @returns {boolean} 是否相等
   */
  function areImagesEqual(localImages, cloudImages) {
    // 如果数组长度不同，肯定不相等
    if (localImages.length !== cloudImages.length) {
      return false;
    }

    // 创建本地图片ID映射
    const localImageMap = new Map();
    for (const img of localImages) {
      if (img && img.id) {
        localImageMap.set(img.id, {
          id: img.id,
          name: img.name || '',
          mime: img.mime || ''
        });
      }
    }

    // 检查每个云端图片是否在本地存在且基本信息一致
    for (const cloudImg of cloudImages) {
      if (!cloudImg || !cloudImg.id) {
        return false; // 云端图片缺少ID，认为不相等
      }

      const localImg = localImageMap.get(cloudImg.id);
      if (!localImg) {
        return false; // 本地没有对应图片
      }

      // 比较基本信息（忽略dataUrl等可能变化的内容）
      if (localImg.name !== (cloudImg.name || '') ||
        localImg.mime !== (cloudImg.mime || '')) {
        return false; // 基本信息不一致
      }
    }

    return true; // 所有图片都匹配
  }

  /**
   * 比较两个文档是否相等
   * @param {Object} localDoc - 本地文档
   * @param {Object} cloudDoc - 云端文档
   * @returns {boolean} 是否相等
   */
  function areDocsEqual(localDoc, cloudDoc) {
    if (!localDoc || !cloudDoc) {
      return false; // 任一文档不存在，认为不相等
    }

    // 检查删除状态是否一致
    if (!!localDoc.deleted !== !!cloudDoc.deleted) {
      return false;
    }

    // 检查MD内容是否一致
    if (localDoc.md !== cloudDoc.md) {
      return false;
    }

    // 检查图片是否一致
    const localImages = localDoc.images || [];
    const cloudImages = cloudDoc.images || [];
    return areImagesEqual(localImages, cloudImages);
  }

  /**
   * 比较完整数据集是否相等
   * @param {Object} localData - 本地数据
   * @param {Object} cloudData - 云端数据
   * @returns {boolean} 是否相等
   */
  function areDataSetsEqual(localData, cloudData) {
    if (!localData || !cloudData) {
      return false;
    }

    // 检查配置哈希是否一致
    if (localData.aiConfigHash !== cloudData.aiConfigHash ||
      localData.promptTemplatesHash !== cloudData.promptTemplatesHash ||
      localData.myPromptTemplatesHash !== cloudData.myPromptTemplatesHash) {
      return false;
    }

    // 检查文档数量是否一致
    const localDocs = localData.docs || [];
    const cloudDocs = cloudData.docs || [];
    if (localDocs.length !== cloudDocs.length) {
      return false;
    }

    // 创建文档ID映射
    const localDocMap = new Map(localDocs.map(d => [d.id, d]));
    const cloudDocMap = new Map(cloudDocs.map(d => [d.id, d]));

    // 检查每个文档是否匹配
    for (const [docId, localDoc] of localDocMap) {
      const cloudDoc = cloudDocMap.get(docId);
      if (!areDocsEqual(localDoc, cloudDoc)) {
        return false;
      }
    }

    return true;
  }

  function saveLocalDocs(docs) { try { return (typeof mw_saveDocs === 'function') ? mw_saveDocs(docs) : null; } catch (_) { return null; } }

  // 获取AI配置和提示词模板
  function getLocalAIConfig() {
    try {
      const configStr = localStorage.getItem('allAIPlatformConfigs');
      return configStr ? JSON.parse(configStr) : {};
    } catch (_) {
      return {};
    }
  }

  function getLocalPromptTemplates() {
    try {
      const templatesStr = localStorage.getItem('promptTemplates');
      return templatesStr ? JSON.parse(templatesStr) : [];
    } catch (_) {
      return [];
    }
  }

  // 获取本地 myPromptTemplates 数据
  function getLocalMyPromptTemplates() {
    try {
      const templatesStr = localStorage.getItem('myPromptTemplates');
      return templatesStr ? JSON.parse(templatesStr) : [];
    } catch (_) {
      return [];
    }
  }

  // 保存AI配置和提示词模板
  function saveLocalAIConfig(config) {
    try {
      localStorage.setItem('allAIPlatformConfigs', JSON.stringify(config));
      localStorage.setItem('allAIPlatformConfigs_last_modified', Date.now().toString());
      return true;
    } catch (_) {
      return false;
    }
  }

  function saveLocalPromptTemplates(templates) {
    try {
      localStorage.setItem('promptTemplates', JSON.stringify(templates));
      localStorage.setItem('promptTemplates_last_modified', Date.now().toString());
      return true;
    } catch (_) {
      return false;
    }
  }

  // 直接读现成的 hash 与 last_modified，不再自己算
  function getDataHashAndTime(_data, storageKey) {
    const hash = localStorage.getItem(storageKey + '_hash') || '';
    const lastModified = parseInt(localStorage.getItem(storageKey + '_last_modified') || '0');
    return { hash, lastModified };
  }

  // 文件大小检查函数
  function checkFileSize(docs) {
    let totalSize = 0;
    const errors = [];

    for (const doc of (docs || [])) {
      if (!doc) continue;

      // 计算文档文本内容大小（UTF-8编码）
      if (doc.md) {
        const contentSize = new Blob([doc.md]).size;
        totalSize += contentSize;
      }

      // 计算标题大小
      if (doc.name) {
        const titleSize = new Blob([doc.name]).size;
        totalSize += titleSize;
      }

      // 计算备注大小
      if (doc.note) {
        const noteSize = new Blob([doc.note]).size;
        totalSize += noteSize;
      }

      // 检查文档中的图片
      if (doc.md) {
        const imgMatches = doc.md.match(/data:image\/[^;]+;base64,[^"']+/g) || [];
        for (const imgData of imgMatches) {
          const base64Data = imgData.split(',')[1];
          const imgSize = Math.ceil(base64Data.length * 0.75); // base64解码后的大小

          if (imgSize > MAX_IMAGE_SIZE) {
            errors.push(`文档"${doc.name || doc.id}"中的图片超过200KB限制`);
          }
          totalSize += imgSize;
        }
      }

      // 检查备注中的图片
      if (doc.note) {
        const noteImgMatches = doc.note.match(/data:image\/[^;]+;base64,[^"']+/g) || [];
        for (const imgData of noteImgMatches) {
          const base64Data = imgData.split(',')[1];
          const imgSize = Math.ceil(base64Data.length * 0.75);

          if (imgSize > MAX_IMAGE_SIZE) {
            errors.push(`文档"${doc.title || doc.id}"备注中的图片超过200KB限制`);
          }
          totalSize += imgSize;
        }
      }
    }

    if (totalSize > MAX_TOTAL_SIZE) {
      errors.push(`总文件大小超过10M限制（当前${Math.ceil(totalSize / 1024 / 1024)}M）`);
    }

    return {
      valid: errors.length === 0,
      errors: errors,
      totalSize: totalSize
    };
  }

  // 获取文档的时间戳映射表
  function getDocTimestamps(docs) {
    const timestamps = {};
    for (const doc of (docs || [])) {
      if (doc && doc.id) {
        // 对于已删除的文档，使用deletedAt作为时间戳，确保同步逻辑正确
        timestamps[doc.id] = Number(doc.updatedAt || doc.deletedAt || 0);
      }
    }
    return timestamps;
  }

  // ============= 新同步核心：同结构快照 + 三向合并 =============

  // 把云端原始 doc 转成本地格式，并补全缺失字段
  function normalizeCloudDoc(cDoc) {
    return {
      id: cDoc.id,
      name: cDoc.name || '',
      md: cDoc.md || '',
      images: cDoc.images || [], // 添加images数组字段
      updatedAt: Number(cDoc.updatedAt || 0),
      deletedAt: cDoc.deletedAt ? Number(cDoc.deletedAt) : undefined
    };
  }

  // 拉取并组装成与 localFullData 完全同构的对象
  async function fetchCloudFullData() {
    // 每次都重新拉取最新数据，避免缓存导致的数据不一致
    const cloudRaw = cachedCloudRaw || await downloadCloud();
    // 更新缓存，确保后续可以使用
    cachedCloudRaw = cloudRaw;
    return {
      docs: (cloudRaw.docs || []).map(normalizeCloudDoc),
      aiConfig: cloudRaw.aiConfig || {},
      aiConfigHash: cloudRaw.aiConfigHash,                // 直接取云端存的哈希
      aiConfigLastModified: Number(cloudRaw.configUpdatedAt || 0),
      promptTemplates: cloudRaw.promptTemplates || [],
      promptTemplatesHash: cloudRaw.promptTemplatesHash,    // 直接取云端存的哈希
      promptTemplatesLastModified: Number(cloudRaw.templateUpdatedAt || 0),
      myPromptTemplates: cloudRaw.myPromptTemplates || [],
      myPromptTemplatesHash: cloudRaw.myPromptTemplatesHash,    // 直接取云端存的哈希
      myPromptTemplatesLastModified: Number(cloudRaw.myPromptTemplateUpdatedAt || 0),
      lastSyncAt: 0                                         // 云端无此字段
    };
  }

  // 三向合并：本地 + 云端 → 目标结构
  async function mergeToTarget(local, cloud) {
    const target = {
      docs: [],
      aiConfig: {},
      promptTemplates: [],
      myPromptTemplates: [],
      aiConfigHash: undefined,
      aiConfigLastModified: 0,
      promptTemplatesHash: undefined,
      promptTemplatesLastModified: 0,
      myPromptTemplatesHash: undefined,
      myPromptTemplatesLastModified: 0,
      lastSyncAt: Date.now()
    };

    // 1. 文档数组：按 ID 三向合并（跳过已删除，哈希相同取云端，不同按时间戳）
    const hashDoc = d => {
      const str = (d.name || '') + '\n' + (d.md || '') + '\n' + JSON.stringify(d.images || []);
      let h = 5381;
      for (let i = 0; i < str.length; i++) h = (h << 5) + h + str.charCodeAt(i);
      return h >>> 0;          // 转成正 32 位整数
    };

    const localDocMap = new Map(local.docs.map(d => [d.id, d]));
    const cloudDocMap = new Map(cloud.docs.map(d => [d.id, d]));
    // 只排除云端已删除的 id；本地已删除仍要参与合并，以便把删除同步到云端
    const aliveIds = new Set([
      ...local.docs.map(d => d.id),                       // 本地全部保留
      ...cloud.docs.filter(d => !d.deletedAt).map(d => d.id) // 云端只留未删除
    ]);
    const allIds = aliveIds;

    for (const id of allIds) {
      const ld = localDocMap.get(id);
      const cd = cloudDocMap.get(id);

      if (!ld && cd) {           // 仅云端有
        target.docs.push(await cleanDocImagesArray(cd));
      } else if (ld && !cd) {    // 仅本地有
        target.docs.push(await cleanDocImagesArray(ld));
      } else {                   // 两边都有
        const hashL = hashDoc(ld);
        const hashC = hashDoc(cd);
        if (hashL === hashC) {   // 内容相同，用云端
          target.docs.push(await cleanDocImagesArray(cd));
        } else {                 // 内容不同，按时间戳决胜
          target.docs.push(await cleanDocImagesArray(Number(ld.updatedAt) >= Number(cd.updatedAt) ? ld : cd));
        }
      }
    }

    // 2. AI 配置：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.aiConfigLastModified && cloud.aiConfigLastModified) {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    } else if (local.aiConfigLastModified && !cloud.aiConfigLastModified) {
      target.aiConfig = local.aiConfig;
      target.aiConfigHash = local.aiConfigHash;
      target.aiConfigLastModified = local.aiConfigLastModified;
    } else if (local.aiConfigHash === cloud.aiConfigHash) {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    } else if (local.aiConfigLastModified >= cloud.aiConfigLastModified) {
      target.aiConfig = local.aiConfig;
      target.aiConfigHash = local.aiConfigHash;
      target.aiConfigLastModified = local.aiConfigLastModified;
    } else {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    }

    // 3. 提示词模板：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.promptTemplatesLastModified && cloud.promptTemplatesLastModified) {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    } else if (local.promptTemplatesLastModified && !cloud.promptTemplatesLastModified) {
      target.promptTemplates = local.promptTemplates;
      target.promptTemplatesHash = local.promptTemplatesHash;
      target.promptTemplatesLastModified = local.promptTemplatesLastModified;
    } else if (local.promptTemplatesHash === cloud.promptTemplatesHash) {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    } else if (local.promptTemplatesLastModified >= cloud.promptTemplatesLastModified) {
      target.promptTemplates = local.promptTemplates;
      target.promptTemplatesHash = local.promptTemplatesHash;
      target.promptTemplatesLastModified = local.promptTemplatesLastModified;
    } else {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    }

    // 4. 我的提示词模板：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.myPromptTemplatesLastModified && cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesLastModified && !cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = local.myPromptTemplates;
      target.myPromptTemplatesHash = local.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = local.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesHash === cloud.myPromptTemplatesHash) {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesLastModified >= cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = local.myPromptTemplates;
      target.myPromptTemplatesHash = local.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = local.myPromptTemplatesLastModified;
    } else {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    }

    console.log('合并后的目标结构:', target);
    return target;
  }

  // 落地：云端
  async function applyTargetToCloud(target, cloudFullData, cloudObj, localFullData) {
    console.log('[SYNC] 开始云端同步，用户状态:', AV.User.current() ? '已登录' : '未登录');
    const user = AV.User.current();
    if (!user) throw new Error('未登录');

    // 添加版本检查和防并发机制
    if (!cloudObj) {
      throw new Error('云端对象为空，无法同步');
    }

    // 获取当前云端对象的版本信息
    const currentVersion = cloudObj.get('updatedAtMs') || 0;
    console.log('[SYNC] 当前云端对象版本:', currentVersion);

    // 关键验证：确保target数据是用户选择的结果，而不是云端数据
    console.log('[SYNC] === 关键数据验证 ===');
    console.log('[SYNC] target数据来源检查:');
    console.log('[SYNC] - target.docs数量:', target.docs ? target.docs.length : 0);
    console.log('[SYNC] - target.aiConfig键数量:', target.aiConfig ? Object.keys(target.aiConfig).length : 0);
    console.log('[SYNC] - target.promptTemplates数量:', target.promptTemplates ? target.promptTemplates.length : 0);
    console.log('[SYNC] - target.myPromptTemplates数量:', target.myPromptTemplates ? target.myPromptTemplates.length : 0);

    console.log('[SYNC] cloudFullData数据来源检查:');
    console.log('[SYNC] - cloudFullData.docs数量:', cloudFullData.docs ? cloudFullData.docs.length : 0);
    console.log('[SYNC] - cloudFullData.aiConfig键数量:', cloudFullData.aiConfig ? Object.keys(cloudFullData.aiConfig).length : 0);
    console.log('[SYNC] - cloudFullData.promptTemplates数量:', cloudFullData.promptTemplates ? cloudFullData.promptTemplates.length : 0);
    console.log('[SYNC] - cloudFullData.myPromptTemplates数量:', cloudFullData.myPromptTemplates ? cloudFullData.myPromptTemplates.length : 0);

    // 验证target数据是否与云端数据完全相同（检查用户选择是否生效）
    if (target.docs && cloudFullData.docs) {
      const targetDocIds = new Set(target.docs.map(d => d.id));
      const cloudDocIds = new Set(cloudFullData.docs.map(d => d.id));
      const sameDocs = target.docs.length === cloudFullData.docs.length &&
        [...targetDocIds].every(id => cloudDocIds.has(id));

      if (sameDocs && target.docs.length > 0) {
        const firstTargetDoc = target.docs[0];
        const firstCloudDoc = cloudFullData.docs.find(d => d.id === firstTargetDoc.id);
        if (firstCloudDoc && firstTargetDoc.updatedAt === firstCloudDoc.updatedAt) {
          // 只有当用户明确做了选择，但数据仍然完全一致时才警告
          const hasUserChoices = target.modifiedDocIds && target.modifiedDocIds.length > 0;
          if (hasUserChoices) {
            console.warn('[SYNC] ⚠️ 注意：用户选择了修改文档，但目标数据与云端数据完全一致');
            console.warn('[SYNC] 这可能是正常的，用户可能选择了保留云端版本');
          } else {
            console.log('[SYNC] 目标数据与云端数据一致，使用系统推荐方案');
          }
        }
      }
    }

    // 0. 先补回云端已删除记录（本地可能已彻底剔除），得到完整目标
    const targetIds = new Set((target.docs || []).map(d => d.id));

    console.log('[SYNC] buildTargetFromChoices后的目标数据检查:');
    console.log('[SYNC] target.docs数量:', target.docs ? target.docs.length : 0);
    console.log('[SYNC] targetIds集合:', Array.from(targetIds));
    console.log('[SYNC] cloudFullData.docs数量:', cloudFullData && cloudFullData.docs ? cloudFullData.docs.length : 0);

    const mergedDocs = [...(target.docs || [])];
    console.log('[SYNC] 初始mergedDocs数量:', mergedDocs.length);

    for (const cd of (cloudFullData ? cloudFullData.docs : [])) {
      if (!targetIds.has(cd.id) && cd.deletedAt) {
        mergedDocs.push(cd);   // 云端独有且已标记删除
        console.log('[SYNC] 添加云端已删除文档:', cd.id, cd.title);
      }
    }

    console.log('[SYNC] 最终mergedDocs数量:', mergedDocs.length);

    // 1. 用补回后的完整目标与云端对比，若完全一致直接跳过
    // 注意：这里使用target.docs而不是mergedDocs，因为mergedDocs可能包含云端已删除的记录
    console.log('[SYNC] 数据比较前检查:');
    console.log('[SYNC] 本地文档数量:', target.docs ? target.docs.length : 0);
    console.log('[SYNC] 云端文档数量:', cloudFullData && cloudFullData.docs ? cloudFullData.docs.length : 0);

    const isEqual = areDataSetsEqual(target, cloudFullData);
    console.log('[SYNC] 数据比较结果:', isEqual);

    if (isEqual) {
      console.log('[SYNC] 云端与本地一致，无需同步');
      showSuccess('云端与本地一致，无需同步');
      return;   // 无需真正落库
    }

    console.log('[SYNC] 检测到数据差异，开始同步到云端');


    // 使用传入的云端对象，避免重复下载
    const obj = cloudObj || await fetchOrCreateRecord();
    if (!obj) {
      throw new Error('无法获取云端对象');
    }

    // 确保所有文档的images数组都已清理，只包含MD内容中实际引用的图片
    const cleanedDocs = await Promise.all(mergedDocs.map(doc => cleanDocImagesArray(doc)));

    console.log('[SYNC] 清理后的文档数据检查:');
    console.log('[SYNC] cleanedDocs数量:', cleanedDocs.length);

    // 验证关键文档数据是否正确
    if (cleanedDocs.length > 0) {
      const firstDoc = cleanedDocs[0];
      const originalFirstDoc = mergedDocs[0];
      console.log('[SYNC] 第一个文档验证:');
      console.log('[SYNC] - ID:', firstDoc.id);
      console.log('[SYNC] - 标题:', firstDoc.title);
      console.log('[SYNC] - 内容长度:', firstDoc.md ? firstDoc.md.length : 0);
      console.log('[SYNC] - 更新时间:', firstDoc.updatedAt);
      console.log('[SYNC] - 与原始数据一致:', firstDoc.id === originalFirstDoc.id);

      // 检查是否有用户明确选择的文档
      const userSelectedDocs = cleanedDocs.filter(doc => {
        // 这里应该检查用户的选择，但暂时通过更新时间判断
        const localDoc = localFullData.docs.find(d => d.id === doc.id);
        const cloudDoc = cloudFullData.docs.find(d => d.id === doc.id);
        if (localDoc && cloudDoc) {
          return localDoc.updatedAt >= cloudDoc.updatedAt; // 选择了较新的本地版本
        }
        return !!localDoc; // 只有本地有，说明是本地新增
      });
      console.log('[SYNC] 用户选择本地文档数量:', userSelectedDocs.length);
    }

    console.log('[SYNC] 准备保存到云端的文档数量:', cleanedDocs.length);
    if (cleanedDocs.length > 0) {
      console.log('[SYNC] 第一个要保存的文档示例:', {
        id: cleanedDocs[0].id,
        title: cleanedDocs[0].title,
        mdLength: cleanedDocs[0].md ? cleanedDocs[0].md.length : 0,
        updatedAt: cleanedDocs[0].updatedAt
      });
    }

    obj.set('docs', cleanedDocs);
    obj.set('aiConfig', target.aiConfig);
    obj.set('aiConfigHash', target.aiConfigHash);
    obj.set('configUpdatedAt', target.aiConfigLastModified);
    obj.set('promptTemplates', target.promptTemplates);
    obj.set('promptTemplatesHash', target.promptTemplatesHash);
    obj.set('templateUpdatedAt', target.promptTemplatesLastModified);
    obj.set('myPromptTemplates', target.myPromptTemplates);
    obj.set('myPromptTemplatesHash', target.myPromptTemplatesHash);
    obj.set('myPromptTemplateUpdatedAt', target.myPromptTemplateLastModified);
    obj.set('docUpdatedAt', Math.max(...mergedDocs.map(d => Number(d.updatedAt)), 0));
    obj.set('updatedAtMs', Date.now());   // 补上统一时间戳

    // 同步图片数据到云端
    // 注意：图片同步将在 bidirectionalSync 函数的末尾通过 syncAllImages 统一处理
    // 这里不再单独调用 syncImagesToCloud，避免重复同步导致的问题
    console.log('[SYNC] 图片数据将在后续统一同步');

    console.log('[SYNC] 开始保存数据到云端...');
    console.log('[SYNC] 准备保存的文档数量:', cleanedDocs.length);
    if (cleanedDocs.length > 0) {
      console.log('[SYNC] 第一个准备保存的文档:', {
        id: cleanedDocs[0].id,
        title: cleanedDocs[0].title,
        mdLength: cleanedDocs[0].md ? cleanedDocs[0].md.length : 0,
        updatedAt: cleanedDocs[0].updatedAt
      });
    }

    // 添加保存重试机制，避免网络问题导致同步失败
    let retryCount = 0;
    const maxRetries = 3;

    while (retryCount < maxRetries) {
      try {
        await obj.save();
        console.log('[SYNC] 第', retryCount + 1, '次保存成功');
        break;
      } catch (saveError) {
        retryCount++;
        console.error('[SYNC] 第', retryCount, '次保存失败:', saveError.message);

        if (retryCount >= maxRetries) {
          throw new Error(`云端保存失败，已重试${maxRetries}次: ${saveError.message}`);
        }

        // 等待一段时间后重试
        await new Promise(resolve => setTimeout(resolve, 1000 * retryCount));

        // 重新获取云端对象，避免版本冲突
        try {
          const freshCloudData = await downloadCloud();
          obj = freshCloudData.obj;
          console.log('[SYNC] 重新获取云端对象成功');
        } catch (refreshError) {
          console.error('[SYNC] 重新获取云端对象失败:', refreshError.message);
        }
      }
    }

    // 验证保存是否成功
    const savedDocs = obj.get('docs');
    console.log('[SYNC] 保存后验证云端文档数量:', savedDocs ? savedDocs.length : 0);
    if (savedDocs && savedDocs.length > 0) {
      console.log('[SYNC] 保存后验证第一个文档:', {
        id: savedDocs[0].id,
        title: savedDocs[0].title,
        mdLength: savedDocs[0].md ? savedDocs[0].md.length : 0,
        updatedAt: savedDocs[0].updatedAt
      });
    }

    console.log('[SYNC] 云端同步完成');
  }




  // 显示冲突确认对话框
  function showConflictDialog(conflicts) {
    if (!conflicts || conflicts.length === 0) return true;

    const conflictList = conflicts.map(conflict =>
      `文档：${conflict.title}\n` +
      `本地修改时间：${new Date(conflict.localTime).toLocaleString()}\n` +
      `云端修改时间：${new Date(conflict.cloudTime).toLocaleString()}\n`
    ).join('\n---\n\n');

    const message = `检测到 ${conflicts.length} 个潜在冲突：\n\n${conflictList}\n` +
      '这些文档在本地和云端都有修改，且时间很接近。\n' +
      '继续同步将按照"谁新用谁"的规则处理。\n\n' +
      '是否继续同步？';

    return confirm(message);
  }

  function showInfo(msg) {
    try {
      if (window.showInfo) {
        window.showInfo(msg);
      } else {
        console.info('[SYNC]', msg);
      }
    } catch (e) {
      console.error('[SYNC] showInfo error:', e);
      alert(msg);
    }
  }

  function showSuccess(msg) {
    try {
      if (window.showSuccess) {
        window.showSuccess(msg);
      } else {
        console.info('[SYNC]', msg);
      }
    } catch (e) {
      console.error('[SYNC] showSuccess error:', e);
      alert(msg);
    }
  }

  function showError(msg) {
    try {
      if (window.showError) {
        window.showError(msg);
      } else {
        console.error('[SYNC]', msg);
        alert(msg); // 确保即使通知系统未加载也能显示错误
      }
    } catch (e) {
      console.error('[SYNC] showError error:', e);
      alert(msg); // 确保即使通知系统出错也能显示错误
    }
  }
  function applyLangUIOnce() { try { if (typeof window.__mw_applyLangToUI === 'function') window.__mw_applyLangToUI(); } catch (_) { } }

  async function fetchOrCreateRecord() {
    const user = AV.User.current();
    if (!user) throw new Error('未登录');
    const MWData = AV.Object.extend(CLASS_NAME);
    try {
      const query = new AV.Query(MWData);
      query.equalTo('ownerId', user.id);
      const list = await query.find();
      if (list && list.length > 0) return list[0];
    } catch (e) {
      // Class 尚未创建或无 schema：忽略查询错误，直接创建
    }
    const obj = new MWData();
    obj.set('ownerId', user.id);
    obj.set('docs', []);
    obj.set('aiConfig', {});
    obj.set('promptTemplates', []);
    obj.set('myPromptTemplates', []);
    obj.set('docUpdatedAt', Date.now()); // 使用当前时间而不是0
    obj.set('configUpdatedAt', Date.now());
    obj.set('templateUpdatedAt', Date.now());
    obj.set('myPromptTemplateUpdatedAt', Date.now());
    return await obj.save();
  }


  async function downloadCloud() {
    const obj = await fetchOrCreateRecord();
    const docs = obj.get('docs') || [];
    const docUpdatedAt = obj.get('docUpdatedAt') || 0;
    const aiConfig = obj.get('aiConfig') || {};
    const promptTemplates = obj.get('promptTemplates') || [];
    const myPromptTemplates = obj.get('myPromptTemplates') || [];

    const configUpdatedAt = obj.get('configUpdatedAt') || 0;
    const templateUpdatedAt = obj.get('templateUpdatedAt') || 0;
    const myPromptTemplateUpdatedAt = obj.get('myPromptTemplateUpdatedAt') || 0;

    // 新增：补齐上行时会写入的哈希与统一时间戳
    const aiConfigHash = obj.get('aiConfigHash') || undefined;
    const promptTemplatesHash = obj.get('promptTemplatesHash') || undefined;
    const myPromptTemplatesHash = obj.get('myPromptTemplatesHash') || undefined;

    const updatedAtMs = obj.get('updatedAtMs') || 0;

    return {
      obj,
      docs,
      aiConfig,
      promptTemplates,
      myPromptTemplates,
      docUpdatedAt,
      configUpdatedAt,
      templateUpdatedAt,
      myPromptTemplateUpdatedAt,
      aiConfigHash,        // 新增
      promptTemplatesHash, // 新增
      myPromptTemplatesHash, // 新增
      updatedAtMs          // 新增
    };
  }

  // 落地：本地（同步后物理删除已标记文档）
  function applyTargetToLocal(target) {
    // 物理剔除已删除文档
    const aliveDocs = target.docs.filter(d => !d.deletedAt);
    localStorage.setItem('mw_documents', JSON.stringify(aliveDocs));
    // AI 配置
    localStorage.setItem('allAIPlatformConfigs', JSON.stringify(target.aiConfig));
    localStorage.setItem('allAIPlatformConfigs_hash', target.aiConfigHash);
    localStorage.setItem('allAIPlatformConfigs_last_modified', String(target.aiConfigLastModified));
    // 提示词模板
    localStorage.setItem('promptTemplates', JSON.stringify(target.promptTemplates));
    localStorage.setItem('promptTemplates_hash', target.promptTemplatesHash);
    localStorage.setItem('promptTemplates_last_modified', String(target.promptTemplatesLastModified));
    // 我的提示词模板
    localStorage.setItem('myPromptTemplates', JSON.stringify(target.myPromptTemplates));
    localStorage.setItem('myPromptTemplates_hash', target.myPromptTemplatesHash);
    localStorage.setItem('myPromptTemplates_last_modified', String(target.myPromptTemplatesLastModified));
    // 同步时间戳
    localStorage.setItem('mindword_last_sync_at', String(Date.now()));

    // 触发图片数据同步，只同步有修改的文档中的图片
    // 注意：数据将在后续统一同步到云端，这里跳过云端保存避免重复
    syncImagesAfterDataSync(aliveDocs, target.modifiedDocIds, true);
  }

  // 数据同步后同步图片
  async function syncImagesAfterDataSync(docs, modifiedDocIds = null, skipCloudSave = false) {
    if (!isLoggedIn() || !window.imageStorage) {
      console.log('[SYNC] 跳过图片同步：未登录或图片存储未初始化');
      return;
    }

    try {
      console.log('[SYNC] 开始同步图片数据...');

      // 检查文档是否已经包含base64图片数据
      const hasBase64Images = docs.some(doc => {
        if (!doc || !doc.images || !Array.isArray(doc.images)) return false;
        return doc.images.some(img => img && img.dataUrl);
      });

      if (hasBase64Images) {
        console.log('[SYNC] 文档已包含base64图片数据，跳过单独图片同步');
        console.log('[SYNC] base64图片详情:', docs.map(doc => ({
          id: doc.id,
          name: doc.name,
          hasImages: !!(doc.images && doc.images.length),
          base64Images: doc.images ? doc.images.filter(img => img && img.dataUrl).length : 0
        })).filter(doc => doc.base64Images > 0));
        return { uploaded: 0, downloaded: 0, message: '文档已包含base64图片数据' };
      }

      const result = await syncAllImages(docs, null, modifiedDocIds, skipCloudSave);
      console.log('[SYNC] 图片同步结果:', result);
    } catch (error) {
      console.error('[SYNC] 图片同步失败:', error);
      // 不抛出错误，避免影响主要数据同步
    }
  }

  // async function uploadCloud(obj, docs) {
  //   obj.set('docs', docs);
  //   obj.set('updatedAtMs', Date.now());
  //   return await obj.save();
  // }

  // 显示同步预览对话框
  async function showSyncPreviewDialog(localFullData, cloudFullData, targetFullData) {
    return new Promise((resolve) => {
      // 创建对话框HTML
      const dialog = document.createElement('div');
      dialog.id = 'sync-preview-dialog';
      dialog.innerHTML = `
        <div style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); z-index: 10000; display: flex; align-items: center; justify-content: center;">
          <div style="background: white; border-radius: 12px; padding: 24px; width: 90%; max-width: 1000px; max-height: 80vh; overflow: hidden; display: flex; flex-direction: column; box-shadow: 0 20px 40px rgba(0,0,0,0.3);">
            <div style="display: flex; align-items: center; margin-bottom: 20px;">
              <h3 style="margin: 0; color: #333; font-size: 20px; font-weight: 600;"><span data-i18n="cloud.syncPreview">🔄 同步预览</span></h3>
              <div style="margin-left: auto; font-size: 12px; color: #666; background: #f8f9fa; padding: 4px 8px; border-radius: 4px;">
                <span data-i18n="cloud.selectDataToKeep">选择要保留的数据</span>
              </div>
            </div>
            <div style="flex: 1; overflow-y: auto; border: 1px solid #e0e0e0; border-radius: 8px; background: #fafafa;">
              <table style="width: 100%; border-collapse: collapse;">
                <thead style="background: #f5f5f5; position: sticky; top: 0; z-index: 10;">
                  <tr>
                    <th style="padding: 16px; text-align: center; border-bottom: 1px solid #ddd; width: 50%; color: #333; font-weight: 600; font-size: 14px;">
                      <span style="display: inline-flex; align-items: center; gap: 8px;">
                        <span>📁</span>
                        <span data-i18n="cloud.localData">本地数据</span>
                      </span>
                    </th>
                    <th style="padding: 16px; text-align: center; border-bottom: 1px solid #ddd; width: 50%; color: #333; font-weight: 600; font-size: 14px;">
                      <span style="display: inline-flex; align-items: center; gap: 8px;">
                        <span>☁️</span>
                        <span data-i18n="cloud.cloudData">云端数据</span>
                      </span>
                    </th>
                  </tr>
                </thead>
                <tbody id="sync-preview-tbody">
                </tbody>
              </table>
            </div>
            <div style="margin-top: 20px; text-align: right; display: flex; justify-content: flex-end; align-items: center;">
              <div>
                <button id="sync-preview-cancel" style="margin-right: 12px; padding: 10px 20px; border: 1px solid #ddd; background: white; border-radius: 6px; cursor: pointer; font-weight: 500; transition: all 0.2s;" data-i18n="docs.cancel">取消</button>
                <button id="sync-preview-confirm" style="padding: 10px 24px; background: linear-gradient(135deg, #28a745, #20c997); color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: 600; transition: all 0.2s; box-shadow: 0 2px 8px rgba(40, 167, 69, 0.3);"><span data-i18n="cloud.confirmSync">🔄 确定同步</span></button>
              </div>
            </div>
          </div>
        </div>
      `;

      document.body.appendChild(dialog);

      // 应用国际化翻译
      if (window.i18nManager && window.i18nManager.updatePageTranslations) {
        window.i18nManager.updatePageTranslations();
      }

      // 生成对比数据
      const tbody = document.getElementById('sync-preview-tbody');
      const comparisons = generateSyncComparisons(localFullData, cloudFullData, targetFullData);

      comparisons.forEach((item, index) => {
        const row = document.createElement('tr');
        row.style.borderBottom = '1px solid #eee';

        // 如果内容一致，使用统一的淡灰色背景，禁用选择功能
        if (item.isContentSame) {
          row.style.backgroundColor = '#f0f0f0';
          row.style.opacity = '0.8';
        }

        // 状态管理 - 使用数据属性存储当前选择
        row.dataset.choice = item.recommendLocal ? 'local' : 'cloud';

        // 本地数据列
        const localCell = document.createElement('td');
        localCell.style.padding = '8px';
        localCell.style.verticalAlign = 'top';
        localCell.style.position = 'relative';
        localCell.style.cursor = 'pointer';
        localCell.style.transition = 'all 0.2s ease';
        localCell.style.width = '50%';

        const updateLocalCellStyle = () => {
          if (item.isContentSame) {
            // 内容一致时使用统一的淡灰色样式
            localCell.style.backgroundColor = '#e8e8e8';
            localCell.style.border = '1px solid #ccc';
            localCell.style.borderRadius = '6px';
            localCell.style.margin = '2px';
          } else {
            const isSelected = row.dataset.choice === 'local';
            localCell.style.backgroundColor = isSelected ? '#f0f8f0' : '#fafafa';
            localCell.style.border = isSelected ? '2px solid #28a745' : '1px solid #eee';
            localCell.style.borderRadius = '6px';
            localCell.style.margin = '2px';

            // 更新勾选图标显示状态
            const checkMark = localCell.querySelector('.check-mark');
            const cloudCheckMark = cloudCell.querySelector('.check-mark');
            if (checkMark && cloudCheckMark) {
              checkMark.style.display = isSelected ? 'block' : 'none';
              cloudCheckMark.style.display = !isSelected ? 'block' : 'none';
            }
          }
        };

        localCell.innerHTML = `
          <div style="font-weight: bold; color: #333; margin-bottom: 2px; display: flex; align-items: center; justify-content: space-between;">
            <span>${item.local.name}</span>
            <span class="check-mark" style="color: #28a745; font-size: 16px; display: ${item.isContentSame ? 'none' : (row.dataset.choice === 'local' ? 'block' : 'none')};">✓</span>
          </div>
          <div style="font-size: 11px; color: #666; line-height: 1.3;">${item.local.description}</div>
          <div style="font-size: 11px; color: #999; margin-top: 2px;"><span data-i18n="cloud.updatedAt">更新时间</span>: ${item.local.updatedAt}</div>
        `;

        // 点击本地列选择本地 - 内容一致时禁用点击
        localCell.addEventListener('click', () => {
          if (item.isContentSame) return; // 内容一致时不允许切换
          row.dataset.choice = 'local';
          updateLocalCellStyle();
          updateCloudCellStyle();
        });

        // 云端数据列
        const cloudCell = document.createElement('td');
        cloudCell.style.padding = '8px';
        cloudCell.style.verticalAlign = 'top';
        cloudCell.style.position = 'relative';
        cloudCell.style.cursor = 'pointer';
        cloudCell.style.transition = 'all 0.2s ease';
        cloudCell.style.width = '50%';

        const updateCloudCellStyle = () => {
          if (item.isContentSame) {
            // 内容一致时使用统一的淡灰色样式
            cloudCell.style.backgroundColor = '#e8e8e8';
            cloudCell.style.border = '1px solid #ccc';
            cloudCell.style.borderRadius = '6px';
            cloudCell.style.margin = '2px';
          } else {
            const isSelected = row.dataset.choice === 'cloud';
            cloudCell.style.backgroundColor = isSelected ? '#f0f8f0' : '#fafafa';
            cloudCell.style.border = isSelected ? '2px solid #28a745' : '1px solid #eee';
            cloudCell.style.borderRadius = '6px';
            cloudCell.style.margin = '2px';

            // 更新勾选图标显示状态
            const checkMark = cloudCell.querySelector('.check-mark');
            const localCheckMark = localCell.querySelector('.check-mark');
            if (checkMark && localCheckMark) {
              checkMark.style.display = isSelected ? 'block' : 'none';
              localCheckMark.style.display = !isSelected ? 'block' : 'none';
            }
          }
        };

        cloudCell.innerHTML = `
          <div style="font-weight: bold; color: #333; margin-bottom: 2px; display: flex; align-items: center; justify-content: space-between;">
            <span>${item.cloud.name}</span>
            <span class="check-mark" style="color: #28a745; font-size: 16px; display: ${item.isContentSame ? 'none' : (row.dataset.choice === 'cloud' ? 'block' : 'none')};">✓</span>
          </div>
          <div style="font-size: 11px; color: #666; line-height: 1.3;">${item.cloud.description}</div>
          <div style="font-size: 11px; color: #999; margin-top: 2px;"><span data-i18n="cloud.updatedAt">更新时间</span>: ${item.cloud.updatedAt}</div>
        `;

        // 点击云端列选择云端 - 内容一致时禁用点击
        cloudCell.addEventListener('click', () => {
          if (item.isContentSame) return; // 内容一致时不允许切换
          row.dataset.choice = 'cloud';
          updateLocalCellStyle();
          updateCloudCellStyle();
        });

        // 初始化样式
        updateLocalCellStyle();
        updateCloudCellStyle();

        row.appendChild(localCell);
        row.appendChild(cloudCell);
        tbody.appendChild(row);
      });

      // 绑定按钮事件
      document.getElementById('sync-preview-cancel').addEventListener('click', () => {
        document.body.removeChild(dialog);
        resolve(null); // 用户取消
      });

      document.getElementById('sync-preview-confirm').addEventListener('click', () => {
        const choices = {};
        comparisons.forEach((item, index) => {
          // 直接从行数据属性获取选择状态
          const row = document.querySelectorAll('#sync-preview-tbody tr')[index];
          choices[item.key] = row.dataset.choice || (item.recommendLocal ? 'local' : 'cloud');
        });

        document.body.removeChild(dialog);
        resolve(choices); // 返回用户选择
      });
    });
  }

  // 生成同步对比数据
  function generateSyncComparisons(localFullData, cloudFullData, targetFullData) {
    const comparisons = [];

    // 文档对比
    const localDocs = localFullData.docs || [];
    const cloudDocs = cloudFullData.docs || [];

    // 过滤掉自动生成的空文档
    const filteredLocalDocs = localDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));
    const filteredCloudDocs = cloudDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));

    const localDocMap = new Map(filteredLocalDocs.map(d => [d.id, d]));
    const cloudDocMap = new Map(filteredCloudDocs.map(d => [d.id, d]));

    // 找出所有文档ID（只包含过滤后的文档）
    const allDocIds = new Set([...filteredLocalDocs.map(d => d.id), ...filteredCloudDocs.map(d => d.id)]);

    allDocIds.forEach(docId => {
      const localDoc = localDocMap.get(docId);
      const cloudDoc = cloudDocMap.get(docId);

      if (localDoc && cloudDoc) {
        // 两边都有 - 检查内容是否一致（包含图片数据）
        const isContentSame = areDocsEqual(localDoc, cloudDoc);

        // 为了生成详细的描述信息，单独检查MD和图片
        const localImages = localDoc.images || [];
        const cloudImages = cloudDoc.images || [];
        const imagesEqual = areImagesEqual(localImages, cloudImages);
        const mdEqual = localDoc.md === cloudDoc.md;

        let description = '';

        if (isContentSame) {
          description = '<span style="color: #28a745;">内容一致 ✓</span>';
        } else {
          if (mdEqual && !imagesEqual) {
            description = '<span style="color: #ffc107;">图片已变更</span>';
          } else if (!mdEqual && imagesEqual) {
            description = '<span style="color: #dc3545;">内容不一致</span>';
          } else {
            description = '<span style="color: #dc3545;">内容和图片都已变更</span>';
          }
        }
        const localTime = new Date(Number(localDoc.updatedAt)).toLocaleString();
        const cloudTime = new Date(Number(cloudDoc.updatedAt)).toLocaleString();
        const recommendLocal = localDoc.updatedAt >= cloudDoc.updatedAt;

        // 检查是否有文档被删除
        const localDeleted = localDoc.deletedAt;
        const cloudDeleted = cloudDoc.deletedAt;

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: localDoc.name || '未命名文档',
            description: localDeleted ? '<span style="color: #dc3545;">本地已删除文档</span>' : description,
            updatedAt: localTime
          },
          cloud: {
            name: cloudDoc.name || '未命名文档',
            description: cloudDeleted ? '<span style="color: #dc3545;">云端已删除文档</span>' : description,
            updatedAt: cloudTime
          },
          recommendLocal: recommendLocal,
          isContentSame: isContentSame && !localDeleted && !cloudDeleted
        });
      } else if (localDoc && !cloudDoc) {
        // 只有本地有 - 判断是新增还是删除
        // 如果本地文档已删除，则跳过这个对比（空对空没有意义）
        if (localDoc.deletedAt) {
          return; // 跳过本地已删除文档
        }

        const isRecentlyUpdated = localDoc.updatedAt > Date.now() - 24 * 60 * 60 * 1000; // 24小时内更新过
        let description = '';

        if (isRecentlyUpdated) {
          description = '<span style="color: #28a745;">本地新增文档</span>';
        } else {
          description = '<span style="color: #28a745;">本地独有文档</span>';
        }

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: localDoc.name || '未命名文档',
            description: description,
            updatedAt: new Date(Number(localDoc.updatedAt)).toLocaleString()
          },
          cloud: {
            name: '(无)',
            description: '云端不存在',
            updatedAt: '-'
          },
          recommendLocal: true
        });
      } else if (!localDoc && cloudDoc) {
        // 只有云端有 - 判断是新增还是删除
        // 如果云端文档已删除，则跳过这个对比（空对空没有意义）
        if (cloudDoc.deletedAt) {
          return; // 跳过云端已删除文档
        }

        const isRecentlyUpdated = cloudDoc.updatedAt > Date.now() - 24 * 60 * 60 * 1000; // 24小时内更新过
        let description = '';

        if (isRecentlyUpdated) {
          description = '<span style="color: #28a745;">云端新增文档</span>';
        } else {
          description = '<span style="color: #28a745;">云端独有文档</span>';
        }

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: '(无)',
            description: '本地不存在',
            updatedAt: '-'
          },
          cloud: {
            name: cloudDoc.name || '未命名文档',
            description: description,
            updatedAt: new Date(Number(cloudDoc.updatedAt)).toLocaleString()
          },
          recommendLocal: false
        });
      }
    });

    // AI配置对比
    const localAIConfig = localFullData.aiConfig || {};
    const cloudAIConfig = cloudFullData.aiConfig || {};
    const localAIConfigTime = new Date(localFullData.aiConfigLastModified).toLocaleString();
    const cloudAIConfigTime = new Date(cloudFullData.aiConfigLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isAIConfigSame = localFullData.aiConfigHash === cloudFullData.aiConfigHash;

    // 判断配置是否为空
    const localConfigEmpty = Object.keys(localAIConfig).length === 0;
    const cloudConfigEmpty = Object.keys(cloudAIConfig).length === 0;

    comparisons.push({
      key: 'ai_config',
      local: {
        name: 'AI平台配置',
        description: isAIConfigSame ? `配置一致 ✓ (平台数量: ${Object.keys(localAIConfig).length}个)` :
          localConfigEmpty ? '本地无配置' : `平台数量: ${Object.keys(localAIConfig).length}个`,
        updatedAt: localAIConfigTime
      },
      cloud: {
        name: 'AI平台配置',
        description: isAIConfigSame ? `配置一致 ✓ (平台数量: ${Object.keys(cloudAIConfig).length}个)` :
          cloudConfigEmpty ? '云端无配置' : `平台数量: ${Object.keys(cloudAIConfig).length}个`,
        updatedAt: cloudAIConfigTime
      },
      recommendLocal: localFullData.aiConfigLastModified >= cloudFullData.aiConfigLastModified,
      isContentSame: isAIConfigSame
    });

    // 提示词模板对比
    const localPromptTemplates = localFullData.promptTemplates || [];
    const cloudPromptTemplates = cloudFullData.promptTemplates || [];
    const localPromptTime = new Date(localFullData.promptTemplatesLastModified).toLocaleString();
    const cloudPromptTime = new Date(cloudFullData.promptTemplatesLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isPromptTemplatesSame = localFullData.promptTemplatesHash === cloudFullData.promptTemplatesHash;

    // 判断模板是否为空
    const localTemplatesEmpty = localPromptTemplates.length === 0;
    const cloudTemplatesEmpty = cloudPromptTemplates.length === 0;

    comparisons.push({
      key: 'prompt_templates',
      local: {
        name: '提示词模板',
        description: isPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${localPromptTemplates.length}个)` :
          localTemplatesEmpty ? '本地无模板' : `模板数量: ${localPromptTemplates.length}个`,
        updatedAt: localPromptTime
      },
      cloud: {
        name: '提示词模板',
        description: isPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${cloudPromptTemplates.length}个)` :
          cloudTemplatesEmpty ? '云端无模板' : `模板数量: ${cloudPromptTemplates.length}个`,
        updatedAt: cloudPromptTime
      },
      recommendLocal: localFullData.promptTemplatesLastModified >= cloudFullData.promptTemplatesLastModified,
      isContentSame: isPromptTemplatesSame
    });

    // 我的提示词模板对比
    const localMyPromptTemplates = localFullData.myPromptTemplates || [];
    const cloudMyPromptTemplates = cloudFullData.myPromptTemplates || [];
    const localMyPromptTime = new Date(localFullData.myPromptTemplatesLastModified).toLocaleString();
    const cloudMyPromptTime = new Date(cloudFullData.myPromptTemplatesLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isMyPromptTemplatesSame = localFullData.myPromptTemplatesHash === cloudFullData.myPromptTemplatesHash;

    // 判断模板是否为空
    const localMyTemplatesEmpty = localMyPromptTemplates.length === 0;
    const cloudMyTemplatesEmpty = cloudMyPromptTemplates.length === 0;

    comparisons.push({
      key: 'my_prompt_templates',
      local: {
        name: '我的提示词模板',
        description: isMyPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${localMyPromptTemplates.length}个)` :
          localMyTemplatesEmpty ? '本地无模板' : `模板数量: ${localMyPromptTemplates.length}个`,
        updatedAt: localMyPromptTime
      },
      cloud: {
        name: '我的提示词模板',
        description: isMyPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${cloudMyPromptTemplates.length}个)` :
          cloudMyTemplatesEmpty ? '云端无模板' : `模板数量: ${cloudMyPromptTemplates.length}个`,
        updatedAt: cloudMyPromptTime
      },
      recommendLocal: localFullData.myPromptTemplatesLastModified >= cloudFullData.myPromptTemplatesLastModified,
      isContentSame: isMyPromptTemplatesSame
    });

    return comparisons;
  }

  // 根据用户选择重新构建目标数据
  async function buildTargetFromChoices(localFullData, cloudFullData, choices) {
    const target = {
      docs: [],
      aiConfig: {},
      promptTemplates: [],
      myPromptTemplates: [],
      aiConfigHash: undefined,
      aiConfigLastModified: 0,
      promptTemplatesHash: undefined,
      promptTemplatesLastModified: 0,
      myPromptTemplatesHash: undefined,
      myPromptTemplatesLastModified: 0,
      lastSyncAt: Date.now(),
      modifiedDocIds: [] // 记录有修改的文档ID
    };

    // 处理文档选择
    const localDocs = localFullData.docs || [];
    const cloudDocs = cloudFullData.docs || [];
    const filteredLocalDocs = localDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));
    const filteredCloudDocs = cloudDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));
    const localDocMap = new Map(filteredLocalDocs.map(d => [d.id, d]));
    const cloudDocMap = new Map(filteredCloudDocs.map(d => [d.id, d]));
    const allDocIds = new Set([...filteredLocalDocs.map(d => d.id), ...filteredCloudDocs.map(d => d.id)]);

    for (const docId of allDocIds) {
      const choice = choices[`doc_${docId}`];
      let docToAdd = null;
      let isModified = false;

      // 用户明确选择了本地版本
      if (choice === 'local') {
        if (localDocMap.has(docId)) {
          docToAdd = localDocMap.get(docId);
          isModified = true; // 用户明确选择，视为有修改
        }
        // 如果用户选择本地但本地不存在该文档，则不添加（即删除）
      }
      // 用户明确选择了云端版本
      else if (choice === 'cloud') {
        if (cloudDocMap.has(docId)) {
          docToAdd = cloudDocMap.get(docId);
          isModified = true; // 用户明确选择，视为有修改
        }
        // 如果用户选择云端但云端不存在该文档，则不添加（即删除）
      }
      // 用户没有选择，使用推荐逻辑
      else {
        if (localDocMap.has(docId) && cloudDocMap.has(docId)) {
          // 两边都有，选择更新时间较新的
          const localDoc = localDocMap.get(docId);
          const cloudDoc = cloudDocMap.get(docId);
          const useLocal = localDoc.updatedAt >= cloudDoc.updatedAt;
          docToAdd = useLocal ? localDoc : cloudDoc;

          // 如果选择了与云端不同的版本，则视为有修改
          if ((useLocal && localDoc.updatedAt !== cloudDoc.updatedAt) ||
            (!useLocal && localDoc.updatedAt !== cloudDoc.updatedAt)) {
            isModified = true;
          }
        } else if (localDocMap.has(docId)) {
          // 只有本地有，保留本地版本
          docToAdd = localDocMap.get(docId);
          isModified = true; // 新增文档，视为有修改
        } else if (cloudDocMap.has(docId)) {
          // 只有云端有，保留云端版本
          docToAdd = cloudDocMap.get(docId);
          isModified = true; // 新增文档，视为有修改
        }
      }

      // 添加文档并记录修改状态
      if (docToAdd) {
        target.docs.push(await cleanDocImagesArray(docToAdd));
        if (isModified) {
          target.modifiedDocIds.push(docId);
        }
      }
    }

    // 处理AI配置选择
    if (choices.ai_config === 'local') {
      target.aiConfig = localFullData.aiConfig || {};
      target.aiConfigHash = localFullData.aiConfigHash;
      target.aiConfigLastModified = localFullData.aiConfigLastModified;
    } else {
      target.aiConfig = cloudFullData.aiConfig || {};
      target.aiConfigHash = cloudFullData.aiConfigHash;
      target.aiConfigLastModified = cloudFullData.aiConfigLastModified;
    }

    // 处理提示词模板选择
    if (choices.prompt_templates === 'local') {
      target.promptTemplates = localFullData.promptTemplates || [];
      target.promptTemplatesHash = localFullData.promptTemplatesHash;
      target.promptTemplatesLastModified = localFullData.promptTemplatesLastModified;
    } else {
      target.promptTemplates = cloudFullData.promptTemplates || [];
      target.promptTemplatesHash = cloudFullData.promptTemplatesHash;
      target.promptTemplatesLastModified = cloudFullData.promptTemplatesLastModified;
    }

    // 处理我的提示词模板选择
    if (choices.my_prompt_templates === 'local') {
      target.myPromptTemplates = localFullData.myPromptTemplates || [];
      target.myPromptTemplatesHash = localFullData.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = localFullData.myPromptTemplatesLastModified;
    } else {
      target.myPromptTemplates = cloudFullData.myPromptTemplates || [];
      target.myPromptTemplatesHash = cloudFullData.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloudFullData.myPromptTemplatesLastModified;
    }

    return target;
  }

  // 新的同步逻辑：按照用户方案实现
  async function bidirectionalSync() {
    try {
      // 添加详细的登录状态检查
      if (!isLoggedIn()) {
        console.log('[SYNC] 用户未登录，跳过同步');
        return; // 未登录时不执行同步，直接返回
      }

      // 输出当前用户信息，便于调试
      const currentUser = AV.User.current();
      console.log('[SYNC] 开始同步，当前用户:', currentUser ? currentUser.id : 'null');
      console.log('[SYNC] LeanCloud应用ID:', AV.applicationId || '未初始化');

      showInfo('正在智能同步...');

      // 1. 组装本地完整快照
      const localDocs = getLocalDocs();
      console.log('[SYNC] 获取到本地文档数量:', localDocs.length);
      if (localDocs.length > 0) {
        console.log('[SYNC] 第一个本地文档示例:', {
          id: localDocs[0].id,
          title: localDocs[0].title,
          mdLength: localDocs[0].md ? localDocs[0].md.length : 0,
          updatedAt: localDocs[0].updatedAt
        });
      }

      const localAIConfig = getLocalAIConfig();
      const localPromptTemplates = getLocalPromptTemplates();
      const localMyPromptTemplates = getLocalMyPromptTemplates();
      const localFullData = {
        docs: localDocs,
        aiConfig: localAIConfig,
        aiConfigHash: localStorage.getItem('allAIPlatformConfigs_hash') || undefined,
        aiConfigLastModified: Number(localStorage.getItem('allAIPlatformConfigs_last_modified') || 0),
        promptTemplates: localPromptTemplates,
        promptTemplatesHash: localStorage.getItem('promptTemplates_hash') || undefined,
        promptTemplatesLastModified: Number(localStorage.getItem('promptTemplates_last_modified') || 0),
        myPromptTemplates: localMyPromptTemplates,
        myPromptTemplatesHash: localStorage.getItem('myPromptTemplates_hash') || undefined,
        myPromptTemplatesLastModified: Number(localStorage.getItem('myPromptTemplates_last_modified') || 0),
        lastSyncAt: Number(localStorage.getItem('mindword_last_sync_at') || 0)
      };

      console.log('[SYNC] 合并后的目标结构:', {
        docsCount: localFullData.docs.length,
        aiConfigKeys: Object.keys(localFullData.aiConfig || {}),
        promptTemplatesCount: localFullData.promptTemplates.length,
        myPromptTemplatesCount: localFullData.myPromptTemplates.length,
        aiConfigHash: localFullData.aiConfigHash
      });

      // 文件大小检查
      const sizeCheck = checkFileSize(localDocs);
      if (!sizeCheck.valid) {
        throw new Error('文件大小检查失败：' + sizeCheck.errors.join('；'));
      }

      // 2. 拉取云端同结构快照（每次都重新获取最新数据，避免缓存问题）
      cachedCloudRaw = null;  // 清除缓存，强制重新获取
      const cloudFullData = await fetchCloudFullData();

      // 保存云端对象引用，避免后续重复下载导致数据不一致
      const cloudObjRef = cachedCloudRaw;

      // 3. 三向合并 → 目标结构
      const targetFullData = await mergeToTarget(localFullData, cloudFullData);

      // 4. 显示同步预览对话框，让用户选择保留哪一侧的数据
      const userChoices = await showSyncPreviewDialog(localFullData, cloudFullData, targetFullData);

      // 用户取消同步
      if (!userChoices) {
        showInfo('同步已取消');
        return;
      }

      // 5. 根据用户选择重新构建目标数据
      const finalTargetFullData = await buildTargetFromChoices(localFullData, cloudFullData, userChoices);

      // 6. 落地：先写本地，再写云端（确保本地优先）
      console.log('[SYNC] 开始应用同步数据...');
      applyTargetToLocal(finalTargetFullData);

      // 使用之前保存的云端对象引用，避免重新下载导致数据不一致
      if (!cloudObjRef) {
        throw new Error('云端对象引用丢失，同步失败');
      }
      await applyTargetToCloud(finalTargetFullData, cloudFullData, cloudObjRef.obj, localFullData);
      console.log('[SYNC] 同步数据已成功应用到云端');

      // 6.5 同步图片数据 - 只同步有修改的文档中的图片
      // 使用之前保存的云端对象引用，避免数据不一致
      // 注意：数据已经在 applyTargetToCloud 中保存，这里跳过云端保存避免重复
      await syncAllImages(finalTargetFullData.docs, cloudObjRef, finalTargetFullData.modifiedDocIds, true);

      // 5. 刷新 UI
      if (typeof mw_renderList === 'function') mw_renderList();

      // 6. 如果当前有正在编辑的文档，刷新数据展示
      if (typeof mw_getActive === 'function' && typeof mw_notifyEditorLoad === 'function') {
        const activeId = mw_getActive();
        if (activeId && typeof mw_loadDocs === 'function') {
          const docs = mw_loadDocs();
          const currentDoc = docs.find(d => d.id === activeId);
          if (currentDoc) {
            // 刷新当前文档到各个面板
            mw_notifyEditorLoad(currentDoc);
            if (typeof mw_notifyPreviewLoad === 'function') mw_notifyPreviewLoad(currentDoc);
            if (typeof mw_notifyMindmapLoad === 'function') mw_notifyMindmapLoad(currentDoc);
            console.log('[SYNC] 已刷新当前编辑文档:', activeId);
          }
        }

        // 检查当前文档是否被删除，如果是则切换到第一个有效文档
        const currentActiveId = mw_getActive();
        if (currentActiveId) {
          const docs = getLocalDocs();
          const currentDoc = docs.find(d => d.id === currentActiveId);
          if (!currentDoc || currentDoc.deletedAt) {
            console.log('[SYNC] 当前文档已被删除，准备切换到第一个有效文档');
            // 切换到第一个未删除的文档
            const firstValidDoc = docs.find(d => !d.deletedAt);
            if (firstValidDoc) {
              mw_setActive(firstValidDoc.id);
              mw_notifyEditorLoad(firstValidDoc);
              mw_notifyPreviewLoad(firstValidDoc);
              mw_notifyMindmapLoad(firstValidDoc);
              console.log('[SYNC] 已切换到第一个有效文档:', firstValidDoc.id);
            } else {
              // 没有有效文档，不自动生成空文档，让用户手动创建
              console.log('[SYNC] 没有有效文档，等待用户手动创建');
            }
          }
        }
      }

      // 7. 同步完成后，如果当前是自动生成的空文档，切换到第一个有效文档
      setTimeout(() => {
        const currentActiveId = mw_getActive();
        if (currentActiveId && typeof mw_loadDocs === 'function') {
          const docs = mw_loadDocs();
          const currentDoc = docs.find(d => d.id === currentActiveId);

          // 如果当前文档是自动生成的空文档，切换到第一个有效文档
          if (currentDoc && isAutoGeneratedEmptyDoc(currentDoc)) {
            console.log('[SYNC] 当前文档是自动生成的空文档，准备切换到第一个有效文档');
            const validDocs = docs.filter(d => !d.deletedAt && !isAutoGeneratedEmptyDoc(d));
            if (validDocs.length > 0) {
              const firstValidDoc = validDocs[0];
              mw_setActive(firstValidDoc.id);
              mw_notifyEditorLoad(firstValidDoc);
              mw_notifyPreviewLoad(firstValidDoc);
              mw_notifyMindmapLoad(firstValidDoc);
              console.log('[SYNC] 已切换到第一个有效文档:', firstValidDoc.id);
            } else {
              console.log('[SYNC] 没有有效文档，保持当前空文档状态');
            }
          }
        }
      }, 200);
      // 缓存同步数据到本地（中文版使用独立缓存键）
      try {
        const docs = getLocalDocs();
        const fileCount = docs ? docs.length : 0;
        localStorage.setItem('mw_cloud_sync_cache_cn', JSON.stringify({
          fileCount: fileCount,
          sizeBytes: sizeCheck.totalSize,
          updatedAt: new Date().toISOString()
        }));
      } catch (_) { }

      showSuccess('同步完成');
      setTimeout(updateSyncStatus, 300);
    } catch (e) {
      // 增强错误处理，确保登录后第一次同步失败能够正确显示
      const errorMsg = e.message || '同步失败';
      console.error('[SYNC] 同步失败:', errorMsg, e);

      // 检查是否是登录后的第一次同步
      const isJustLoggedIn = localStorage.getItem('mw_just_logged_in') === 'true';
      if (isJustLoggedIn) {
        // 如果是登录后第一次同步失败，清除标记并显示更详细的错误信息
        localStorage.removeItem('mw_just_logged_in');
        const detailedErrorMsg = `登录后首次同步失败: ${errorMsg}`;
        showError(detailedErrorMsg);
      } else {
        showError(errorMsg);
      }

      // 确保错误信息能够被用户看到
      setTimeout(() => {
        // 如果通知系统仍未加载，使用原生alert确保用户看到错误
        if (!window.showError) {
          alert(`同步失败: ${errorMsg}`);
        }
      }, 1000);
    }
  }

  async function clearCloud() {
    try {
      if (!isLoggedIn()) { throw new Error('未登录'); }
      if (!confirm('确认清空云端数据？此操作不可撤销')) return;
      const { obj } = await downloadCloud();

      // 清空所有数据
      obj.set('docs', []);
      obj.set('aiConfig', {});
      obj.set('promptTemplates', []);
      obj.set('myPromptTemplates', []);
      obj.set('docUpdatedAt', Date.now());
      obj.set('configUpdatedAt', Date.now());
      obj.set('templateUpdatedAt', Date.now());
      obj.set('myPromptTemplateUpdatedAt', Date.now());

      await obj.save();
      showSuccess('云端数据已清空');
    } catch (e) {
      showError(e.message || '清空失败');
    }
  }

  function initUIBindings() {
    // 获取菜单中的同步控制区域
    const zhCtrls = document.getElementById('lc-sync-controls-menu');

    // 个人菜单中的按钮
    const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
    const menuClearBtn = document.getElementById('lc-clear-btn-menu');

    // 绑定个人菜单按钮 - 使用addEventListener确保函数可访问
    if (menuSyncBtn) {
      console.log('找到同步按钮，绑定点击事件');
      menuSyncBtn.addEventListener('click', function (e) {
        e.stopPropagation(); // 阻止事件冒泡到父元素
        console.log('同步按钮被点击');
        bidirectionalSync();
      });
    } else {
      console.error('未找到同步按钮 lc-sync-btn-menu');
    }

    if (menuClearBtn) {
      menuClearBtn.addEventListener('click', function (e) {
        e.stopPropagation(); // 阻止事件冒泡到父元素
        clearCloud();
      });
    }

    // 登录状态或语言变化时切换显示
    function refreshVisible() {
      const authUser = document.getElementById('auth-user');
      // 未登录：隐藏同步控制区域，避免初次闪现
      if (!authUser || authUser.style.display === 'none') {
        if (zhCtrls) zhCtrls.style.display = 'none';
        return;
      }
      // 始终显示中文同步控制区域，不受语言设置影响
      if (zhCtrls) zhCtrls.style.display = 'flex';
    }

    document.addEventListener('DOMContentLoaded', refreshVisible);
    window.addEventListener('storage', function (e) {
      if (e.key === LANG_KEY || (e.key && e.key.startsWith('AV/'))) setTimeout(refreshVisible, 50);
    });
    // 提供给外部在认证区变化后刷新
    window.__mw_refreshSyncLangUI = refreshVisible;

    // 初始化状态显示
    setTimeout(updateSyncStatus, 500);
  }

  // 页面就绪后初始化
  document.addEventListener('DOMContentLoaded', function () {
    initUIBindings();
    // 尝试在认证区刷新后应用一次
    setTimeout(applyLangUIOnce, 300);

    // 监听文档变化，自动更新状态
    if (typeof mw_getDocs === 'function') {
      // 监听本地存储变化
      window.addEventListener('storage', function (e) {
        if (e.key && e.key.includes('doc')) {
          setTimeout(updateSyncStatus, 100);
        }
      });

      // 定期更新状态（每30秒）
      setInterval(updateSyncStatus, 30000);
    }

    // 初始化个人菜单状态
    setTimeout(() => {
      updateSyncStatus();
      // 初始化个人菜单状态
      updateSyncStatus();
    }, 100);
  });

  // 额外的初始化尝试，确保按钮事件绑定成功
  setTimeout(function () {
    console.log('额外尝试绑定同步按钮事件');
    const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
    if (menuSyncBtn && !menuSyncBtn.hasAttribute('data-sync-bound')) {
      console.log('找到未绑定的同步按钮，进行绑定');
      menuSyncBtn.addEventListener('click', function (e) {
        e.stopPropagation();
        console.log('同步按钮被点击（额外绑定）');
        bidirectionalSync();
      });
      menuSyncBtn.setAttribute('data-sync-bound', 'true');
    }
  }, 2000);

  // 显示文件大小和同步状态
  function updateSyncStatus() {
    try {
      // 获取当前语言
      const currentLang = getLang();
      const t = window.i18nManager ? window.i18nManager.getTranslation : null;

      // 获取翻译文本的辅助函数
      function getText(key, fallback) {
        if (t && t.call) {
          return t.call(window.i18nManager, key) || fallback;
        }
        return fallback;
      }

      // 使用中文缓存键（保持不变）
      const cacheKey = 'mw_cloud_sync_cache_cn';

      // 首先尝试从本地缓存获取数据
      let cachedData = null;
      try {
        const cached = localStorage.getItem(cacheKey);
        if (cached) {
          cachedData = JSON.parse(cached);
        }
      } catch (_) { }

      // 如果有缓存数据，优先使用缓存数据
      if (cachedData && cachedData.fileCount !== undefined && cachedData.sizeBytes !== undefined) {
        const fileCount = cachedData.fileCount || 0;
        const sizeBytes = cachedData.sizeBytes || 0;
        const totalSizeKB = (sizeBytes / 1024).toFixed(1);
        const updatedAt = cachedData.updatedAt || cachedData.timestamp;

        // 计算相对时间
        let timeText = '';
        if (updatedAt) {
          const date = new Date(updatedAt);
          const now = new Date();
          const diffMs = now - date;
          const diffMins = Math.floor(diffMs / 60000);
          const diffHours = Math.floor(diffMs / 3600000);
          const diffDays = Math.floor(diffMs / 86400000);

          if (diffMins < 1) {
            timeText = getText('cloud.justNow', currentLang === 'en' ? 'Just now' : '刚刚');
          } else if (diffMins < 60) {
            if (currentLang === 'en') {
              timeText = `${diffMins} ${getText('cloud.minutesAgo', 'minutes ago')}`;
            } else {
              timeText = `${diffMins}${getText('cloud.minutesAgo', '分钟前')}`;
            }
          } else if (diffHours < 24) {
            if (currentLang === 'en') {
              timeText = `${diffHours} ${getText('cloud.hoursAgo', 'hours ago')}`;
            } else {
              timeText = `${diffHours}${getText('cloud.hoursAgo', '小时前')}`;
            }
          } else if (diffDays < 7) {
            if (currentLang === 'en') {
              timeText = `${diffDays} ${getText('cloud.daysAgo', 'days ago')}`;
            } else {
              timeText = `${diffDays}${getText('cloud.daysAgo', '天前')}`;
            }
          } else {
            timeText = date.toLocaleDateString(currentLang === 'zh' ? 'zh-CN' : 'en-US', { month: 'short', day: 'numeric' });
          }
        }

        // 更新状态显示（主界面）
        const statusElement = document.getElementById('lc-sync-status');
        if (statusElement) {
          if (currentLang === 'en') {
            // 英文环境下使用更简洁的格式
            statusElement.innerHTML = `
              <small style="color: #666; font-size: 11px;">
                ${fileCount} files<br>${totalSizeKB}KB / 10MB${timeText ? '<br>' + timeText : ''}
              </small>
            `;
          } else {
            // 中文环境下使用中文格式
            const filesText = getText('cloud.files', '文件');
            const backupText = getText('cloud.backupTime', '备份');
            const fileCountText = `${fileCount}${getText('cloud.fileCount', '个')}`;
            statusElement.innerHTML = `
              <small style="color: #666; font-size: 11px;">
                ${filesText}: ${fileCountText}<br>${totalSizeKB}KB / 10MB${timeText ? '<br>' + backupText + ': ' + timeText : ''}
              </small>
            `;
          }

          // 根据使用情况改变颜色
          if (sizeBytes > 8 * 1024 * 1024) { // 超过8MB
            statusElement.querySelector('small').style.color = '#e74c3c';
          } else if (sizeBytes > 5 * 1024 * 1024) { // 超过5MB
            statusElement.querySelector('small').style.color = '#f39c12';
          }
        }

        // 更新个人菜单中的状态显示
        const menuStatusElement = document.getElementById('lc-sync-status-menu');
        if (menuStatusElement) {
          if (currentLang === 'en') {
            // 英文环境下使用更简洁的格式
            menuStatusElement.innerHTML = `${fileCount} files<br>${totalSizeKB}KB / 10MB${timeText ? '<br>' + timeText : ''}`;
          } else {
            // 中文环境下使用中文格式
            const filesText = getText('cloud.files', '文件');
            const backupText = getText('cloud.backupTime', '备份');
            const fileCountText = `${fileCount}${getText('cloud.fileCount', '个')}`;
            menuStatusElement.innerHTML = `${filesText}: ${fileCountText}<br>${totalSizeKB}KB / 10MB${timeText ? '<br>' + backupText + ': ' + timeText : ''}`;
          }

          // 根据使用情况改变颜色
          if (sizeBytes > 8 * 1024 * 1024) { // 超过8MB
            menuStatusElement.style.color = '#e74c3c';
          } else if (sizeBytes > 5 * 1024 * 1024) { // 超过5MB
            menuStatusElement.style.color = '#f39c12';
          } else {
            menuStatusElement.style.color = '#9ca3af';
          }
        }

        // 更新按钮状态
        // 注意：主界面的同步按钮不存在，所以这部分代码被注释掉
        // const syncBtn = document.getElementById('lc-sync-btn');
        // if (syncBtn) {
        //   syncBtn.disabled = false;
        //   syncBtn.title = getText('cloud.oneClickSync', '一键同步');
        //   syncBtn.style.opacity = '1';
        // }

        // 更新个人菜单中的同步按钮状态
        const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
        if (menuSyncBtn) {
          menuSyncBtn.disabled = false;
          menuSyncBtn.title = getText('cloud.oneClickSync', '一键同步');
          menuSyncBtn.style.opacity = '1';
        }

        return;
      }

      // 如果没有缓存数据，使用原有的本地数据逻辑
      const docs = getLocalDocs();
      // 过滤掉已删除的文档，只统计有效文档
      const validDocs = docs ? docs.filter(doc => !doc.deletedAt) : [];
      const sizeCheck = checkFileSize(validDocs);

      // 更新状态显示（主界面）
      // 注意：主界面的状态显示元素不存在，所以这部分代码被注释掉
      // const statusElement = document.getElementById('lc-sync-status');
      // if (statusElement) {
      //   const totalSizeMB = (sizeCheck.totalSize / 1024).toFixed(1);
      //   const fileCount = validDocs.length;

      //   if (currentLang === 'en') {
      //     // 英文环境下使用更简洁的格式
      //     statusElement.innerHTML = `
      //       <small style="color: #666; font-size: 11px;">
      //         ${fileCount} files<br>${totalSizeMB}KB / 10MB
      //       </small>
      //     `;
      //   } else {
      //     // 中文环境下使用中文格式
      //     const filesText = getText('cloud.files', '文件');
      //     const fileCountText = `${fileCount}${getText('cloud.fileCount', '个')}`;
      //     statusElement.innerHTML = `
      //       <small style="color: #666; font-size: 11px;">
      //         ${filesText}: ${fileCountText}<br>${totalSizeMB}KB / 10MB
      //       </small>
      //     `;
      //   }

      //   // 根据使用情况改变颜色
      //   if (sizeCheck.totalSize > 8 * 1024 * 1024) { // 超过8MB
      //     statusElement.querySelector('small').style.color = '#e74c3c';
      //   } else if (sizeCheck.totalSize > 5 * 1024 * 1024) { // 超过5MB
      //     statusElement.querySelector('small').style.color = '#f39c12';
      //   }
      // }

      // 更新个人菜单中的状态显示
      const menuStatusElement = document.getElementById('lc-sync-status-menu');
      if (menuStatusElement) {
        const totalSizeMB = (sizeCheck.totalSize / 1024).toFixed(1);
        const fileCount = validDocs.length;

        if (currentLang === 'en') {
          // 英文环境下使用更简洁的格式
          menuStatusElement.innerHTML = `${fileCount} files<br>${totalSizeMB}KB / 10MB`;
        } else {
          // 中文环境下使用中文格式
          const filesText = getText('cloud.files', '文件');
          const fileCountText = `${fileCount}${getText('cloud.fileCount', '个')}`;
          menuStatusElement.innerHTML = `${filesText}: ${fileCountText}<br>${totalSizeMB}KB / 10MB`;
        }

        // 根据使用情况改变颜色
        if (sizeCheck.totalSize > 8 * 1024 * 1024) { // 超过8MB
          menuStatusElement.style.color = '#e74c3c';
        } else if (sizeCheck.totalSize > 5 * 1024 * 1024) { // 超过5MB
          menuStatusElement.style.color = '#f39c12';
        } else {
          menuStatusElement.style.color = '#9ca3af';
        }
      }

      // 更新按钮状态
      // 注意：主界面的同步按钮不存在，所以这部分代码被注释掉
      // const syncBtn = document.getElementById('lc-sync-btn');
      // if (syncBtn) {
      //   if (!sizeCheck.valid) {
      //     syncBtn.disabled = true;
      //     syncBtn.title = getText('cloud.fileSizeCheckFailed', '文件大小检查失败') + '：' + sizeCheck.errors.join('；');
      //     syncBtn.style.opacity = '0.6';
      //   } else {
      //     syncBtn.disabled = false;
      //     syncBtn.title = getText('cloud.oneClickSync', '一键同步');
      //     syncBtn.style.opacity = '1';
      //   }
      // }

      // 更新个人菜单中的同步按钮状态
      const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
      if (menuSyncBtn) {
        if (!sizeCheck.valid) {
          menuSyncBtn.disabled = true;
          menuSyncBtn.title = getText('cloud.fileSizeCheckFailed', '文件大小检查失败') + '：' + sizeCheck.errors.join('；');
          menuSyncBtn.style.opacity = '0.6';
        } else {
          menuSyncBtn.disabled = false;
          menuSyncBtn.title = getText('cloud.oneClickSync', '一键同步');
          menuSyncBtn.style.opacity = '1';
        }
      }

    } catch (error) {
      console.warn('更新同步状态失败:', error);
    }
  }

  // ======== 图片同步相关函数 ========

  /**
   * 同步指定文档的图片
   * @param {string} docId - 文档ID
   * @returns {Promise<Object>} 同步结果
   */
  async function syncImagesForDoc(docId) {
    if (!isLoggedIn()) {
      throw new Error('未登录，无法同步图片');
    }

    if (!window.imageStorage) {
      throw new Error('图片存储管理器未初始化');
    }

    try {
      showInfo('正在同步文档图片...');

      // 获取本地文档
      const docs = getLocalDocs();
      const doc = docs.find(d => d.id === docId);
      if (!doc) {
        throw new Error('文档不存在');
      }

      // 从文档内容中提取图片ID
      const imageIds = extractImageIdsFromDoc(doc);
      if (imageIds.length === 0) {
        return { uploaded: 0, downloaded: 0, message: '文档中没有图片需要同步' };
      }

      // 获取本地图片
      const localImagesMap = await window.imageStorage.getImagesMap();
      const localImageIds = Array.from(localImagesMap.keys());

      // 获取云端数据
      const cloudData = await downloadCloud();
      const cloudDocs = cloudData.docs || [];

      // 找到对应的云端文档
      const cloudDoc = cloudDocs.find(d => d.id === docId);
      if (!cloudDoc) {
        throw new Error('云端未找到对应文档');
      }

      // 获取云端文档中的图片
      const cloudDocImages = cloudDoc.images || [];
      const cloudImageIds = cloudDocImages.map(img => img && img.id).filter(Boolean);

      // 计算需要上传和下载的图片
      const imagesToUpload = imageIds.filter(id => !cloudImageIds.includes(id) && localImageIds.includes(id));
      const imagesToDownload = imageIds.filter(id => cloudImageIds.includes(id) && !localImageIds.includes(id));

      let uploaded = 0;
      let downloaded = 0;

      // 上传本地图片到云端
      if (imagesToUpload.length > 0) {
        const uploadResult = await uploadLocalImages(imagesToUpload);
        uploaded = uploadResult.uploaded;
      }

      // 从云端下载图片到本地
      if (imagesToDownload.length > 0) {
        const downloadResult = await downloadCloudImages(imagesToDownload);
        downloaded = downloadResult.downloaded;
      }

      showSuccess(`图片同步完成：上传${uploaded}张，下载${downloaded}张`);
      return { uploaded, downloaded, message: '图片同步完成' };
    } catch (error) {
      showError(`图片同步失败：${error.message}`);
      throw error;
    }
  }

  /**
   * 从文档内容中提取图片ID
   * @param {Object} doc - 文档对象
   * @returns {string[]} 图片ID数组
   */
  function extractImageIdsFromDoc(doc) {
    const imageIds = [];
    const content = (doc.md || '') + (doc.note || '');

    // 匹配图片语法 ![alt](imageId)
    const imageRegex = /!\[[^\]]*\]\(([^)]+)\)/g;
    let match;

    while ((match = imageRegex.exec(content)) !== null) {
      const imageId = match[1];
      // 现在包括base64图片ID，过滤掉外部链接
      if (!imageId.startsWith('http')) {
        imageIds.push(imageId);
      }
    }

    // 只从MD内容中提取图片ID，不再检查images数组字段
    // 这确保了images数组与MD内容中引用的图片保持一致

    return [...new Set(imageIds)]; // 去重
  }

  /**
   * 从文档内容中提取base64图片数据
   * @param {Object} doc - 文档对象
   * @returns {Array} base64图片对象数组
   */
  function extractBase64ImagesFromDoc(doc) {
    const base64Images = [];
    const content = (doc.md || '') + (doc.note || '');

    // 匹配图片语法 ![alt](data:image/...;base64,...)
    const imageRegex = /!\[[^\]]*\]\((data:image\/[^;]+;base64,[^)]+)\)/g;
    const altRegex = /!\[([^\]]*)\]\(/g;
    let match;
    let altMatch;

    while ((match = imageRegex.exec(content)) !== null) {
      const dataUrl = match[1];

      // 提取对应的alt文本
      altRegex.lastIndex = match.index;
      altMatch = altRegex.exec(content);
      const altText = altMatch ? altMatch[1] : '图片';

      // 生成图片ID（使用dataUrl的哈希值）
      const imageId = 'img_' + Math.abs(dataUrl.split(',')[1].split('').reduce((a, b) => {
        a = ((a << 5) - a) + b.charCodeAt(0);
        return a & a;
      }, 0)).toString(36);

      base64Images.push({
        id: imageId,
        dataUrl: dataUrl,
        alt: altText,
        name: altText || '图片'
      });
    }

    return base64Images;
  }

  /**
   * 清理文档的images数组，确保只包含MD内容中实际引用的图片
   * 现在主动从本地存储获取图片数据并嵌入base64，简化图片上传逻辑
   * @param {Object} doc - 文档对象
   * @returns {Object} 清理后的文档对象
   */
  async function cleanDocImagesArray(doc) {
    if (!doc) return doc;

    // 提取MD内容中实际引用的图片ID（包括base64图片）
    const referencedImageIds = extractImageIdsFromDoc(doc);

    // 同时提取文档内容中的base64图片数据
    const base64Images = extractBase64ImagesFromDoc(doc);

    // 如果文档没有images数组，先初始化为空数组
    let currentImages = [];
    if (doc.images && Array.isArray(doc.images)) {
      currentImages = [...doc.images];
    }

    // 尝试从本地存储获取图片数据并嵌入base64
    if (window.imageStorage && referencedImageIds.length > 0) {
      try {
        const localImagesMap = await window.imageStorage.getImagesMap();

        for (const imageId of referencedImageIds) {
          const localImageInfo = localImagesMap.get(imageId);
          if (localImageInfo) {
            // 查找当前images数组中是否已存在该图片
            let existingImage = currentImages.find(img => img && img.id === imageId);

            if (!existingImage) {
              // 如果images数组中没有该图片，创建新的图片对象
              existingImage = {
                id: imageId,
                name: localImageInfo.name || 'image.png',
                mime: localImageInfo.type || 'image/png'
              };
              currentImages.push(existingImage);
            }

            // 如果本地存储有dataUrl，直接嵌入
            if (localImageInfo.dataUrl) {
              existingImage.dataUrl = localImageInfo.dataUrl;
              console.log(`[SYNC] 为文档 ${doc.id} 的图片 ${imageId} 嵌入base64数据`);
            } else if (localImageInfo.blob) {
              // 如果有blob数据，转换为dataUrl
              try {
                existingImage.dataUrl = await window.imageStorage.blobToDataUrl(localImageInfo.blob);
                console.log(`[SYNC] 为文档 ${doc.id} 的图片 ${imageId} 转换blob为base64数据`);
              } catch (error) {
                console.warn(`[SYNC] 转换图片 ${imageId} blob失败:`, error);
              }
            }
          }
        }
      } catch (error) {
        console.warn('[SYNC] 从本地存储获取图片数据失败:', error);
      }
    }

    // 添加文档内容中的base64图片
    for (const base64Img of base64Images) {
      const existingIndex = currentImages.findIndex(img => img && img.id === base64Img.id);
      if (existingIndex >= 0) {
        // 更新已有的图片
        currentImages[existingIndex] = { ...currentImages[existingIndex], ...base64Img };
      } else {
        // 添加新图片
        currentImages.push(base64Img);
      }
    }

    // 过滤掉文档内容中没有引用的图片（保留有dataUrl的图片）
    const finalImages = currentImages.filter(img => {
      if (!img || !img.id) return false;
      // 保留被引用的图片或有base64数据的图片
      return referencedImageIds.includes(img.id) || img.dataUrl;
    });

    if (finalImages.length > 0) {
      const base64Count = finalImages.filter(img => img.dataUrl).length;
      console.log(`[SYNC] 文档 ${doc.id} 最终保留 ${finalImages.length} 张图片，其中 ${base64Count} 张包含base64数据`);
    }

    // 返回清理后的文档对象，包含嵌入的base64数据
    return {
      ...doc,
      images: finalImages
    };
  }

  /**
   * 批量上传本地图片到云端
   * @param {string[]} imageIds - 要上传的图片ID数组
   * @returns {Promise<Object>} 上传结果
   */
  async function uploadLocalImages(imageIds, cloudObj = null) {
    if (!isLoggedIn()) {
      throw new Error('未登录，无法上传图片');
    }

    if (!window.imageStorage) {
      throw new Error('图片存储管理器未初始化');
    }

    try {
      const imagesMap = await window.imageStorage.getImagesMap();
      console.log(`[SYNC] 获取到 ${imagesMap.size} 张本地图片`);

      // 调试：检查前几个图片的数据结构
      let debugCount = 0;
      for (const [id, info] of imagesMap) {
        console.log(`[SYNC] 图片 ${id} 数据结构:`, {
          hasDataUrl: !!info.dataUrl,
          hasBlob: !!info.blob,
          type: info.type,
          name: info.name
        });
        debugCount++;
        if (debugCount >= 3) break; // 只显示前3个避免日志过多
      }

      let uploaded = 0;

      // 获取云端数据
      const cloudData = cloudObj ? { obj: cloudObj, docs: cloudObj.get('docs') || [] } : await downloadCloud();
      const cloudDocs = cloudData.docs || [];

      // 创建云端文档的映射，方便查找
      const cloudDocsMap = new Map();
      for (const doc of cloudDocs) {
        if (doc && doc.id) {
          cloudDocsMap.set(doc.id, doc);
        }
      }

      // 处理每个要上传的图片
      for (const imageId of imageIds) {
        const imageInfo = imagesMap.get(imageId);
        if (!imageInfo) {
          console.warn(`本地未找到图片 ${imageId} 数据，跳过上传`);
          continue;
        }

        // 检查是否有有效的图片数据（支持 dataUrl 或 blob 格式）
        let imageData = null;
        let imgSize = 0;

        if (imageInfo.dataUrl) {
          // 使用现有的 dataUrl
          const base64Data = imageInfo.dataUrl.split(',')[1];
          if (!base64Data) {
            console.warn(`图片 ${imageId} 数据格式无效，跳过上传`);
            continue;
          }
          imgSize = Math.ceil(base64Data.length * 0.75); // base64解码后的大小
          imageData = imageInfo.dataUrl;
        } else if (imageInfo.blob) {
          // 如果有 blob 数据，转换为 dataUrl
          try {
            imageData = await window.imageStorage.blobToDataUrl(imageInfo.blob);
            imgSize = imageInfo.blob.size;
          } catch (error) {
            console.warn(`图片 ${imageId} blob转换失败，跳过上传:`, error);
            continue;
          }
        } else {
          console.warn(`图片 ${imageId} 没有有效的数据（缺少dataUrl或blob），跳过上传`);
          continue;
        }

        if (imgSize > MAX_IMAGE_SIZE) {
          console.warn(`图片 ${imageId} 超过大小限制(${imgSize} > ${MAX_IMAGE_SIZE})，跳过上传`);
          continue;
        }

        // 查找包含此图片的云端文档
        let foundDoc = null;
        for (const [docId, doc] of cloudDocsMap) {
          if (doc.images && Array.isArray(doc.images)) {
            const imgIndex = doc.images.findIndex(img => img && img.id === imageId);
            if (imgIndex !== -1) {
              foundDoc = doc;
              // 更新文档中的图片数据
              if (!foundDoc.images[imgIndex].dataUrl) {
                foundDoc.images[imgIndex].dataUrl = imageData;
                uploaded++;
                console.log(`图片 ${imageId} 已添加到文档 ${docId}`);
              }
              break;
            }
          }
        }

        if (!foundDoc) {
          console.warn(`未找到包含图片 ${imageId} 的文档，跳过上传`);
        }
      }

      // 如果有图片被上传，更新云端数据
      if (uploaded > 0) {
        const obj = cloudData.obj || await fetchOrCreateRecord();
        // 确保所有文档的images数组都已清理
        const cleanedDocs = await Promise.all(cloudDocs.map(doc => cleanDocImagesArray(doc)));
        obj.set('docs', cleanedDocs);

        // 如果没有传入云端对象，则立即保存；否则由调用方保存
        if (!cloudObj) {
          await obj.save();
        }
      }

      console.log(`成功上传 ${uploaded} 张图片到云端`);
      return { uploaded, message: '图片上传成功' };
    } catch (error) {
      console.error('上传图片失败:', error);
      throw new Error(`上传图片失败：${error.message}`);
    }
  }

  /**
   * 批量下载云端图片到本地
   * @param {string[]} imageIds - 要下载的图片ID数组
   * @returns {Promise<Object>} 下载结果
   */
  async function downloadCloudImages(imageIds) {
    if (!window.imageStorage) {
      throw new Error('图片存储管理器未初始化');
    }

    try {
      const downloaded = [];

      // 获取云端数据
      const cloudData = await downloadCloud();
      const cloudDocs = cloudData.docs || [];

      // 创建云端文档的映射，方便查找
      const cloudDocsMap = new Map();
      for (const doc of cloudDocs) {
        if (doc && doc.id) {
          cloudDocsMap.set(doc.id, doc);
        }
      }

      // 处理每个要下载的图片
      for (const imageId of imageIds) {
        try {
          let imageDataUrl = null;
          let documentId = null;

          // 在所有云端文档中查找包含此图片的文档
          for (const [docId, doc] of cloudDocsMap) {
            if (doc.images && Array.isArray(doc.images)) {
              const img = doc.images.find(img => img && img.id === imageId);
              if (img && img.dataUrl) {
                imageDataUrl = img.dataUrl;
                documentId = docId;
                break;
              }
            }
          }

          if (!imageDataUrl) {
            console.warn(`云端未找到图片数据: ${imageId}`);
            continue;
          }

          // 将DataURL转换为Blob
          const blob = await window.imageStorage.dataUrlToBlob(imageDataUrl);

          // 保存到IndexedDB，提供正确的documentId元数据
          await window.imageStorage.saveImage(imageId, blob, {
            name: imageId,
            documentId: documentId
          });
          downloaded.push(imageId);
          console.log(`成功下载图片 ${imageId} (文档: ${documentId})`);
        } catch (error) {
          console.error(`下载图片 ${imageId} 失败:`, error);
        }
      }

      console.log(`成功下载 ${downloaded.length} 张图片到本地`);
      return { downloaded: downloaded.length, message: '图片下载成功' };
    } catch (error) {
      console.error('下载图片失败:', error);
      throw new Error(`下载图片失败：${error.message}`);
    }
  }

  /**
   * 从URL中提取图片ID
   * @param {string} url - 图片URL
   * @returns {string|null} 图片ID
   */
  function extractImageIdFromUrl(url) {
    // 假设URL格式为: https://example.com/images/{imageId}
    const match = url.match(/\/images\/([^/?]+)/);
    return match ? match[1] : null;
  }

  /**
   * 获取图片数据
   * @param {string} url - 图片URL
   * @returns {Promise<string|null>} 图片base64数据
   */
  async function fetchImageData(url) {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const blob = await response.blob();
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error(`获取图片数据失败: ${url}`, error);
      return null;
    }
  }

  /**
   * 同步所有文档的图片数据
   * @param {Array} docs - 文档数组
   * @param {Object} cloudDataCache - 云端数据缓存（可选）
   * @param {Array} modifiedDocIds - 有修改的文档ID列表，如果提供则只同步这些文档的图片
   * @param {boolean} skipCloudSave - 是否跳过云端保存（当数据已经在其他地方保存时）
   * @returns {Promise<Object>} 同步结果
   */
  async function syncAllImages(docs, cloudDataCache = null, modifiedDocIds = null, skipCloudSave = false) {
    if (!isLoggedIn()) {
      console.log('[SYNC] 未登录，跳过图片同步');
      return { uploaded: 0, downloaded: 0, message: '未登录，跳过图片同步' };
    }

    if (!window.imageStorage) {
      console.warn('[SYNC] 图片存储管理器未初始化，跳过图片同步');
      return { uploaded: 0, downloaded: 0, message: '图片存储管理器未初始化' };
    }

    try {
      console.log('[SYNC] 开始同步图片...');

      // 使用传入的云端数据缓存，如果没有则重新下载
      const cloudData = cloudDataCache || await downloadCloud();
      const cloudDocs = cloudData.docs || [];

      // 创建云端文档的映射，方便查找
      const cloudDocsMap = new Map();
      for (const doc of cloudDocs) {
        if (doc && doc.id) {
          cloudDocsMap.set(doc.id, doc);
        }
      }

      // 获取本地图片数据
      const localImagesMap = await window.imageStorage.getImagesMap();

      let totalUploaded = 0;
      let totalDownloaded = 0;

      // 收集所有需要同步的图片ID，包括文档中引用的和存储中的图片
      const allImageIds = new Set();

      // 确定要处理的文档列表
      let docsToProcess = docs;
      if (modifiedDocIds && modifiedDocIds.length > 0) {
        // 如果有指定修改的文档，只处理这些文档
        docsToProcess = docs.filter(doc => doc && modifiedDocIds.includes(doc.id));
        console.log(`[SYNC] 只处理有修改的文档，共${docsToProcess.length}个`);
      } else {
        console.log(`[SYNC] 处理所有文档，共${docsToProcess.length}个`);
      }

      // 1. 从文档内容中提取图片引用
      for (const doc of docsToProcess) {
        if (!doc || !doc.id) continue;

        // 从文档内容中提取图片ID
        const imageIds = extractImageIdsFromDoc(doc);
        imageIds.forEach(id => allImageIds.add(id));

        // 同时检查文档的images数组
        if (doc.images && Array.isArray(doc.images)) {
          doc.images.forEach(img => {
            if (img && img.id) {
              allImageIds.add(img.id);
            }
          });
        }
      }

      // 2. 添加本地存储中的所有图片ID，确保不遗漏任何图片
      for (const [imageId, imageData] of localImagesMap) {
        allImageIds.add(imageId);
      }

      // 3. 添加云端存储中的所有图片ID，确保不遗漏云端图片
      for (const [docId, doc] of cloudDocsMap) {
        if (doc.images && Array.isArray(doc.images)) {
          doc.images.forEach(img => {
            if (img && img.id) {
              allImageIds.add(img.id);
            }
          });
        }
      }

      console.log(`[SYNC] 收集到${allImageIds.size}个图片ID需要同步检查`);

      // 处理每个图片
      for (const imageId of allImageIds) {
        if (!imageId) continue;

        // 检查本地是否有图片数据
        const localImageData = localImagesMap.get(imageId);
        const hasLocalData = localImageData && localImageData.dataUrl;

        // 查找包含此图片的文档（本地和云端）
        const localDocContainingImage = docs.find(doc => {
          if (!doc || !doc.id) return false;
          const docImageIds = extractImageIdsFromDoc(doc);
          if (docImageIds.includes(imageId)) return true;

          // 检查images数组
          if (doc.images && Array.isArray(doc.images)) {
            return doc.images.some(img => img && img.id === imageId);
          }
          return false;
        });

        const cloudDocContainingImage = Array.from(cloudDocsMap.values()).find(doc => {
          if (!doc || !doc.id) return false;

          // 检查images数组
          if (doc.images && Array.isArray(doc.images)) {
            return doc.images.some(img => img && img.id === imageId);
          }
          return false;
        });

        // 获取云端图片数据
        let cloudImageData = null;
        if (cloudDocContainingImage && cloudDocContainingImage.images) {
          const cloudImg = cloudDocContainingImage.images.find(img => img && img.id === imageId);
          if (cloudImg && cloudImg.dataUrl) {
            cloudImageData = cloudImg;
          }
        }

        const hasCloudData = cloudImageData && cloudImageData.dataUrl;

        // 决定同步方向
        if (hasLocalData && !hasCloudData) {
          // 本地有，云端没有 - 上传
          try {
            const base64Data = localImageData.dataUrl.split(',')[1];
            if (!base64Data) {
              console.warn(`图片 ${imageId} 数据格式无效，跳过上传`);
              continue;
            }

            const imgSize = Math.ceil(base64Data.length * 0.75);
            if (imgSize > MAX_IMAGE_SIZE) {
              console.warn(`图片 ${imageId} 超过大小限制，跳过上传`);
              continue;
            }

            // 确定图片所属的文档
            const targetDoc = localDocContainingImage || docs[0]; // 如果找不到所属文档，使用第一个文档
            if (!targetDoc || !targetDoc.id) {
              console.warn(`图片 ${imageId} 找不到所属文档，跳过上传`);
              continue;
            }

            // 获取或创建云端文档
            let cloudDoc = cloudDocsMap.get(targetDoc.id);
            if (!cloudDoc) {
              // 创建云端文档
              cloudDoc = {
                id: targetDoc.id,
                name: targetDoc.name || '',
                md: targetDoc.md || '',
                images: [],
                updatedAt: Number(targetDoc.updatedAt || 0)
              };
              cloudDocsMap.set(targetDoc.id, cloudDoc);
              cloudDocs.push(cloudDoc);
            }

            // 确保images数组存在
            if (!cloudDoc.images) {
              cloudDoc.images = [];
            }

            // 检查是否已存在
            const existingImg = cloudDoc.images.find(img => img && img.id === imageId);
            if (existingImg) {
              existingImg.dataUrl = localImageData.dataUrl;
            } else {
              // 添加新图片
              cloudDoc.images.push({
                id: imageId,
                name: localImageData.name || imageId,
                mime: localImageData.mime || 'image/png',
                dataUrl: localImageData.dataUrl
              });
            }

            totalUploaded++;
            console.log(`[SYNC] 上传图片 ${imageId} (文档: ${targetDoc.id})`);
          } catch (error) {
            console.error(`[SYNC] 上传图片 ${imageId} 失败:`, error);
          }
        } else if (!hasLocalData && hasCloudData) {
          // 本地没有，云端有 - 下载
          try {
            // 确定图片所属的文档
            const targetDoc = localDocContainingImage || Array.from(cloudDocsMap.values()).find(doc => {
              return doc.images && doc.images.some(img => img && img.id === imageId);
            });

            if (!targetDoc || !targetDoc.id) {
              console.warn(`图片 ${imageId} 找不到所属文档，跳过下载`);
              continue;
            }

            const blob = await window.imageStorage.dataUrlToBlob(cloudImageData.dataUrl);
            await window.imageStorage.saveImage(imageId, blob, {
              name: cloudImageData.name || imageId,
              documentId: targetDoc.id
            });
            totalDownloaded++;
            console.log(`[SYNC] 下载图片 ${imageId} (文档: ${targetDoc.id})`);
          } catch (error) {
            console.error(`[SYNC] 下载图片 ${imageId} 失败:`, error);
          }
        } else if (!hasLocalData && !hasCloudData) {
          // 两边都没有 - 记录警告
          console.warn(`[SYNC] 图片 ${imageId} 在本地和云端都找不到数据`);
        }
        // 如果两边都有数据，则不需要同步
      }

      // 如果有图片需要上传到云端，更新云端文档数据
      if (totalUploaded > 0 && !skipCloudSave) {
        // 使用传入的云端对象缓存，如果没有则重新获取
        const obj = cloudDataCache && cloudDataCache.obj ? cloudDataCache.obj : await fetchOrCreateRecord();
        // 确保所有文档的images数组都已清理
        const cleanedDocs = await Promise.all(cloudDocs.map(doc => cleanDocImagesArray(doc)));
        obj.set('docs', cleanedDocs);
        await obj.save();
        console.log(`[SYNC] 更新云端文档数据，包含${totalUploaded}张新图片`);
      } else if (totalUploaded > 0 && skipCloudSave) {
        console.log(`[SYNC] 跳过上傳图片的云端保存，已在其他地方保存`);
      }

      console.log(`[SYNC] 图片同步完成：上传${totalUploaded}张，下载${totalDownloaded}张`);
      return { uploaded: totalUploaded, downloaded: totalDownloaded, message: '图片同步完成' };
    } catch (error) {
      console.error('[SYNC] 图片同步失败:', error);
      throw new Error(`图片同步失败：${error.message}`);
    }
  }

  /**
   * 将图片数据同步到云端
   * @param {Array} docs - 文档数组
   * @param {Object} cloudObj - 云端对象（可选）
   * @returns {Promise<Object>} 上传结果
   */
  async function syncImagesToCloud(docs, cloudObj = null) {
    if (!isLoggedIn()) {
      console.log('[SYNC] 未登录，跳过图片上传到云端');
      return { uploaded: 0, message: '未登录，跳过图片上传' };
    }

    if (!window.imageStorage) {
      console.warn('[SYNC] 图片存储管理器未初始化，跳过图片上传到云端');
      return { uploaded: 0, message: '图片存储管理器未初始化' };
    }

    try {
      console.log('[SYNC] 开始上传图片到云端...');

      // 从所有文档中提取图片ID
      const allImageIds = new Set();
      for (const doc of docs) {
        if (doc && doc.md) {
          const imageIds = extractImageIdsFromDoc(doc);
          imageIds.forEach(id => allImageIds.add(id));
        }
      }

      if (allImageIds.size === 0) {
        console.log('[SYNC] 没有需要上传的图片');
        return { uploaded: 0, message: '没有需要上传的图片' };
      }

      // 获取本地图片数据
      const localImagesMap = await window.imageStorage.getImagesMap();
      const imagesToUpload = Array.from(allImageIds).filter(id => localImagesMap.has(id));

      if (imagesToUpload.length === 0) {
        console.log('[SYNC] 本地没有找到需要上传的图片');
        return { uploaded: 0, message: '本地没有找到需要上传的图片' };
      }

      // 上传图片，使用传入的云端对象
      const uploadResult = await uploadLocalImages(imagesToUpload, cloudObj);
      console.log(`[SYNC] 成功上传${uploadResult.uploaded}张图片到云端`);
      return uploadResult;
    } catch (error) {
      console.error('[SYNC] 上传图片到云端失败:', error);
      throw new Error(`上传图片到云端失败：${error.message}`);
    }
  }

  // 暴露手动入口（如需）
  window.MW_LC_SYNC = {
    sync: async function () {
      try {
        await bidirectionalSync();
      } catch (error) {
        console.error('[SYNC] 同步入口捕获错误:', error);
        // 确保错误能够显示给用户
        const errorMsg = error.message || '同步失败';
        if (window.showError) {
          window.showError(errorMsg);
        } else {
          alert(errorMsg);
        }
        throw error; // 重新抛出错误，让调用者也能处理
      }
    },
    clear: clearCloud,
    updateStatus: updateSyncStatus,
    syncImagesForDoc: syncImagesForDoc,
    uploadLocalImages: uploadLocalImages,
    downloadCloudImages: downloadCloudImages,
    syncAllImages: syncAllImages,
    syncImagesToCloud: syncImagesToCloud
  };

  // 暴露同步预览对话框函数用于测试国际化 (测试完成后应注释掉)
  // window.showSyncPreviewDialog = showSyncPreviewDialog;

  // 注册语言变化监听器 - 当语言切换时重新更新同步状态
  if (window.i18nManager && window.i18nManager.addLanguageChangeListener) {
    window.i18nManager.addLanguageChangeListener(function (newLanguage) {
      console.log('[LeanCloudSync] Language changed to:', newLanguage, ' - updating sync status');
      updateSyncStatus();
    });
  }

})();
