/**
 * LeanCloud Data 同步（中文模式）
 * 仅在语言为中文时启用 UI；提供：一键同步（智能分析）、清空云数据
 * 改进：支持文件大小检查（单图200KB，总量10M），分类型时间戳记录
 * 字段：docs(json), aiConfig(json), promptTemplates(json), 
 *       docUpdatedAt(number), configUpdatedAt(number), templateUpdatedAt(number)
 */
(function () {
  const LANG_KEY = 'mw_lang';
  const CLASS_NAME = 'MWData';
  let cachedCloudRaw = null;   // 缓存第一次 downloadCloud() 的原生对象

  // 文件大小限制
  const MAX_IMAGE_SIZE = 200 * 1024; // 200KB
  const MAX_TOTAL_SIZE = 10 * 1024 * 1024; // 10M

  function getLang() {
    try { return localStorage.getItem(LANG_KEY) || 'zh'; } catch (_) { return 'zh'; }
  }

  // 新的合并算法：将云端数据合并到本地

  function isLoggedIn() {
    try { return !!(window.AV && AV.User && AV.User.current()); } catch (_) { return false; }
  }

  function getLocalDocs() { try { return (typeof mw_loadDocs === 'function') ? mw_loadDocs() : []; } catch (_) { return []; } }

  // 判断文档是否是自动生成的空文档（没有真实子节点）
  function isAutoGeneratedEmptyDoc(doc) {
    if (!doc) return false;

    // 检查名称是否为默认的"未命名文档"
    const name = doc.name || '';
    if (name !== '未命名文档') return false;

    // 检查内容是否为默认的"# 未命名文档\n"
    const md = doc.md || '';
    if (md.trim() !== '# 未命名文档') return false;

    // 检查是否有图片（空文档不应该有图片）
    if (doc.images && doc.images.length > 0) return false;

    return true;
  }
  function saveLocalDocs(docs) { try { return (typeof mw_saveDocs === 'function') ? mw_saveDocs(docs) : null; } catch (_) { return null; } }

  // 获取AI配置和提示词模板
  function getLocalAIConfig() {
    try {
      const configStr = localStorage.getItem('allAIPlatformConfigs');
      return configStr ? JSON.parse(configStr) : {};
    } catch (_) {
      return {};
    }
  }

  function getLocalPromptTemplates() {
    try {
      const templatesStr = localStorage.getItem('promptTemplates');
      return templatesStr ? JSON.parse(templatesStr) : [];
    } catch (_) {
      return [];
    }
  }

  // 获取本地 myPromptTemplates 数据
  function getLocalMyPromptTemplates() {
    try {
      const templatesStr = localStorage.getItem('myPromptTemplates');
      return templatesStr ? JSON.parse(templatesStr) : [];
    } catch (_) {
      return [];
    }
  }

  // 保存AI配置和提示词模板
  function saveLocalAIConfig(config) {
    try {
      localStorage.setItem('allAIPlatformConfigs', JSON.stringify(config));
      localStorage.setItem('allAIPlatformConfigs_last_modified', Date.now().toString());
      return true;
    } catch (_) {
      return false;
    }
  }

  function saveLocalPromptTemplates(templates) {
    try {
      localStorage.setItem('promptTemplates', JSON.stringify(templates));
      localStorage.setItem('promptTemplates_last_modified', Date.now().toString());
      return true;
    } catch (_) {
      return false;
    }
  }

  // 直接读现成的 hash 与 last_modified，不再自己算
  function getDataHashAndTime(_data, storageKey) {
    const hash = localStorage.getItem(storageKey + '_hash') || '';
    const lastModified = parseInt(localStorage.getItem(storageKey + '_last_modified') || '0');
    return { hash, lastModified };
  }

  // 文件大小检查函数
  function checkFileSize(docs) {
    let totalSize = 0;
    const errors = [];

    for (const doc of (docs || [])) {
      if (!doc) continue;

      // 计算文档文本内容大小（UTF-8编码）
      if (doc.md) {
        const contentSize = new Blob([doc.md]).size;
        totalSize += contentSize;
      }

      // 计算标题大小
      if (doc.name) {
        const titleSize = new Blob([doc.name]).size;
        totalSize += titleSize;
      }

      // 计算备注大小
      if (doc.note) {
        const noteSize = new Blob([doc.note]).size;
        totalSize += noteSize;
      }

      // 检查文档中的图片
      if (doc.md) {
        const imgMatches = doc.md.match(/data:image\/[^;]+;base64,[^"']+/g) || [];
        for (const imgData of imgMatches) {
          const base64Data = imgData.split(',')[1];
          const imgSize = Math.ceil(base64Data.length * 0.75); // base64解码后的大小

          if (imgSize > MAX_IMAGE_SIZE) {
            errors.push(`文档"${doc.name || doc.id}"中的图片超过200KB限制`);
          }
          totalSize += imgSize;
        }
      }

      // 检查备注中的图片
      if (doc.note) {
        const noteImgMatches = doc.note.match(/data:image\/[^;]+;base64,[^"']+/g) || [];
        for (const imgData of noteImgMatches) {
          const base64Data = imgData.split(',')[1];
          const imgSize = Math.ceil(base64Data.length * 0.75);

          if (imgSize > MAX_IMAGE_SIZE) {
            errors.push(`文档"${doc.title || doc.id}"备注中的图片超过200KB限制`);
          }
          totalSize += imgSize;
        }
      }
    }

    if (totalSize > MAX_TOTAL_SIZE) {
      errors.push(`总文件大小超过10M限制（当前${Math.ceil(totalSize / 1024 / 1024)}M）`);
    }

    return {
      valid: errors.length === 0,
      errors: errors,
      totalSize: totalSize
    };
  }

  // 获取文档的时间戳映射表
  function getDocTimestamps(docs) {
    const timestamps = {};
    for (const doc of (docs || [])) {
      if (doc && doc.id) {
        // 对于已删除的文档，使用deletedAt作为时间戳，确保同步逻辑正确
        timestamps[doc.id] = Number(doc.updatedAt || doc.deletedAt || 0);
      }
    }
    return timestamps;
  }

  // ============= 新同步核心：同结构快照 + 三向合并 =============

  // 把云端原始 doc 转成本地格式，并补全缺失字段
  function normalizeCloudDoc(cDoc) {
    return {
      id: cDoc.id,
      name: cDoc.name || '',
      md: cDoc.md || '',
      images: cDoc.images || [], // 添加images数组字段
      updatedAt: Number(cDoc.updatedAt || 0),
      deletedAt: cDoc.deletedAt ? Number(cDoc.deletedAt) : undefined
    };
  }

  // 拉取并组装成与 localFullData 完全同构的对象
  async function fetchCloudFullData() {
    // 优先用缓存，没有再拉
    const cloudRaw = cachedCloudRaw || await downloadCloud();
    if (!cachedCloudRaw) cachedCloudRaw = cloudRaw;
    return {
      docs: (cloudRaw.docs || []).map(normalizeCloudDoc),
      aiConfig: cloudRaw.aiConfig || {},
      aiConfigHash: cloudRaw.aiConfigHash,                // 直接取云端存的哈希
      aiConfigLastModified: Number(cloudRaw.configUpdatedAt || 0),
      promptTemplates: cloudRaw.promptTemplates || [],
      promptTemplatesHash: cloudRaw.promptTemplatesHash,    // 直接取云端存的哈希
      promptTemplatesLastModified: Number(cloudRaw.templateUpdatedAt || 0),
      myPromptTemplates: cloudRaw.myPromptTemplates || [],
      myPromptTemplatesHash: cloudRaw.myPromptTemplatesHash,    // 直接取云端存的哈希
      myPromptTemplatesLastModified: Number(cloudRaw.myPromptTemplateUpdatedAt || 0),
      lastSyncAt: 0                                         // 云端无此字段
    };
  }

  // 三向合并：本地 + 云端 → 目标结构
  function mergeToTarget(local, cloud) {
    const target = {
      docs: [],
      aiConfig: {},
      promptTemplates: [],
      myPromptTemplates: [],
      aiConfigHash: undefined,
      aiConfigLastModified: 0,
      promptTemplatesHash: undefined,
      promptTemplatesLastModified: 0,
      myPromptTemplatesHash: undefined,
      myPromptTemplatesLastModified: 0,
      lastSyncAt: Date.now()
    };

    // 1. 文档数组：按 ID 三向合并（跳过已删除，哈希相同取云端，不同按时间戳）
    const hashDoc = d => {
      const str = (d.name || '') + '\n' + (d.md || '') + '\n' + JSON.stringify(d.images || []);
      let h = 5381;
      for (let i = 0; i < str.length; i++) h = (h << 5) + h + str.charCodeAt(i);
      return h >>> 0;          // 转成正 32 位整数
    };

    const localDocMap = new Map(local.docs.map(d => [d.id, d]));
    const cloudDocMap = new Map(cloud.docs.map(d => [d.id, d]));
    // 只排除云端已删除的 id；本地已删除仍要参与合并，以便把删除同步到云端
    const aliveIds = new Set([
      ...local.docs.map(d => d.id),                       // 本地全部保留
      ...cloud.docs.filter(d => !d.deletedAt).map(d => d.id) // 云端只留未删除
    ]);
    const allIds = aliveIds;

    for (const id of allIds) {
      const ld = localDocMap.get(id);
      const cd = cloudDocMap.get(id);

      if (!ld && cd) {           // 仅云端有
        target.docs.push(cd);
      } else if (ld && !cd) {    // 仅本地有
        target.docs.push(ld);
      } else {                   // 两边都有
        const hashL = hashDoc(ld);
        const hashC = hashDoc(cd);
        if (hashL === hashC) {   // 内容相同，用云端
          target.docs.push(cd);
        } else {                 // 内容不同，按时间戳决胜
          target.docs.push(Number(ld.updatedAt) >= Number(cd.updatedAt) ? ld : cd);
        }
      }
    }

    // 2. AI 配置：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.aiConfigLastModified && cloud.aiConfigLastModified) {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    } else if (local.aiConfigLastModified && !cloud.aiConfigLastModified) {
      target.aiConfig = local.aiConfig;
      target.aiConfigHash = local.aiConfigHash;
      target.aiConfigLastModified = local.aiConfigLastModified;
    } else if (local.aiConfigHash === cloud.aiConfigHash) {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    } else if (local.aiConfigLastModified >= cloud.aiConfigLastModified) {
      target.aiConfig = local.aiConfig;
      target.aiConfigHash = local.aiConfigHash;
      target.aiConfigLastModified = local.aiConfigLastModified;
    } else {
      target.aiConfig = cloud.aiConfig;
      target.aiConfigHash = cloud.aiConfigHash;
      target.aiConfigLastModified = cloud.aiConfigLastModified;
    }

    // 3. 提示词模板：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.promptTemplatesLastModified && cloud.promptTemplatesLastModified) {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    } else if (local.promptTemplatesLastModified && !cloud.promptTemplatesLastModified) {
      target.promptTemplates = local.promptTemplates;
      target.promptTemplatesHash = local.promptTemplatesHash;
      target.promptTemplatesLastModified = local.promptTemplatesLastModified;
    } else if (local.promptTemplatesHash === cloud.promptTemplatesHash) {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    } else if (local.promptTemplatesLastModified >= cloud.promptTemplatesLastModified) {
      target.promptTemplates = local.promptTemplates;
      target.promptTemplatesHash = local.promptTemplatesHash;
      target.promptTemplatesLastModified = local.promptTemplatesLastModified;
    } else {
      target.promptTemplates = cloud.promptTemplates;
      target.promptTemplatesHash = cloud.promptTemplatesHash;
      target.promptTemplatesLastModified = cloud.promptTemplatesLastModified;
    }

    // 4. 我的提示词模板：三向合并（哈希相同用云端，不同谁新用谁）
    if (!local.myPromptTemplatesLastModified && cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesLastModified && !cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = local.myPromptTemplates;
      target.myPromptTemplatesHash = local.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = local.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesHash === cloud.myPromptTemplatesHash) {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    } else if (local.myPromptTemplatesLastModified >= cloud.myPromptTemplatesLastModified) {
      target.myPromptTemplates = local.myPromptTemplates;
      target.myPromptTemplatesHash = local.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = local.myPromptTemplatesLastModified;
    } else {
      target.myPromptTemplates = cloud.myPromptTemplates;
      target.myPromptTemplatesHash = cloud.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloud.myPromptTemplatesLastModified;
    }

    console.log('合并后的目标结构:', target);
    return target;
  }

  // 落地：云端
  async function applyTargetToCloud(target, cloudFullData, cloudObj) {
    const user = AV.User.current();
    if (!user) throw new Error('未登录');

    // 0. 先补回云端已删除记录（本地可能已彻底剔除），得到完整目标
    const targetIds = new Set((target.docs || []).map(d => d.id));
    const mergedDocs = [...(target.docs || [])];
    for (const cd of (cloudFullData ? cloudFullData.docs : [])) {
      if (!targetIds.has(cd.id) && cd.deletedAt) {
        mergedDocs.push(cd);   // 云端独有且已标记删除
      }
    }


    // 1. 用补回后的完整目标与云端对比，若完全一致直接跳过
    if (cloudFullData &&
      target.aiConfigHash === cloudFullData.aiConfigHash &&
      target.promptTemplatesHash === cloudFullData.promptTemplatesHash &&
      target.myPromptTemplatesHash === cloudFullData.myPromptTemplatesHash &&
      JSON.stringify(mergedDocs.map(d => ({ id: d.id, updatedAt: d.updatedAt, deleted: d.deleted, images: d.images || [] }))) ===
      JSON.stringify(cloudFullData.docs.map(d => ({ id: d.id, updatedAt: d.updatedAt, deleted: d.deleted, images: d.images || [] })))) {
      showSuccess('云端与本地一致，无需同步');
      return;   // 无需真正落库
    }


    // 使用传入的云端对象，避免重复下载
    const obj = cloudObj || await fetchOrCreateRecord();
    obj.set('docs', mergedDocs);
    obj.set('aiConfig', target.aiConfig);
    obj.set('aiConfigHash', target.aiConfigHash);
    obj.set('configUpdatedAt', target.aiConfigLastModified);
    obj.set('promptTemplates', target.promptTemplates);
    obj.set('promptTemplatesHash', target.promptTemplatesHash);
    obj.set('templateUpdatedAt', target.promptTemplatesLastModified);
    obj.set('myPromptTemplates', target.myPromptTemplates);
    obj.set('myPromptTemplatesHash', target.myPromptTemplatesHash);
    obj.set('myPromptTemplateUpdatedAt', target.myPromptTemplatesLastModified);
    obj.set('docUpdatedAt', Math.max(...mergedDocs.map(d => Number(d.updatedAt)), 0));
    obj.set('updatedAtMs', Date.now());   // 补上统一时间戳

    await obj.save();
  }




  // 显示冲突确认对话框
  function showConflictDialog(conflicts) {
    if (!conflicts || conflicts.length === 0) return true;

    const conflictList = conflicts.map(conflict =>
      `文档：${conflict.title}\n` +
      `本地修改时间：${new Date(conflict.localTime).toLocaleString()}\n` +
      `云端修改时间：${new Date(conflict.cloudTime).toLocaleString()}\n`
    ).join('\n---\n\n');

    const message = `检测到 ${conflicts.length} 个潜在冲突：\n\n${conflictList}\n` +
      '这些文档在本地和云端都有修改，且时间很接近。\n' +
      '继续同步将按照"谁新用谁"的规则处理。\n\n' +
      '是否继续同步？';

    return confirm(message);
  }

  function showInfo(msg) { try { window.showInfo && window.showInfo(msg); } catch (_) { } }
  function showSuccess(msg) { try { window.showSuccess && window.showSuccess(msg); } catch (_) { } }
  function showError(msg) { try { window.showError && window.showError(msg); } catch (_) { alert(msg); } }
  function applyLangUIOnce() { try { if (typeof window.__mw_applyLangToUI === 'function') window.__mw_applyLangToUI(); } catch (_) { } }

  async function fetchOrCreateRecord() {
    const user = AV.User.current();
    if (!user) throw new Error('未登录');
    const MWData = AV.Object.extend(CLASS_NAME);
    try {
      const query = new AV.Query(MWData);
      query.equalTo('ownerId', user.id);
      const list = await query.find();
      if (list && list.length > 0) return list[0];
    } catch (e) {
      // Class 尚未创建或无 schema：忽略查询错误，直接创建
    }
    const obj = new MWData();
    obj.set('ownerId', user.id);
    obj.set('docs', []);
    obj.set('aiConfig', {});
    obj.set('promptTemplates', []);
    obj.set('myPromptTemplates', []);
    obj.set('docUpdatedAt', Date.now()); // 使用当前时间而不是0
    obj.set('configUpdatedAt', Date.now());
    obj.set('templateUpdatedAt', Date.now());
    obj.set('myPromptTemplateUpdatedAt', Date.now());
    return await obj.save();
  }


  async function downloadCloud() {
    const obj = await fetchOrCreateRecord();
    const docs = obj.get('docs') || [];
    const docUpdatedAt = obj.get('docUpdatedAt') || 0;
    const aiConfig = obj.get('aiConfig') || {};
    const promptTemplates = obj.get('promptTemplates') || [];
    const myPromptTemplates = obj.get('myPromptTemplates') || [];

    const configUpdatedAt = obj.get('configUpdatedAt') || 0;
    const templateUpdatedAt = obj.get('templateUpdatedAt') || 0;
    const myPromptTemplateUpdatedAt = obj.get('myPromptTemplateUpdatedAt') || 0;

    // 新增：补齐上行时会写入的哈希与统一时间戳
    const aiConfigHash = obj.get('aiConfigHash') || undefined;
    const promptTemplatesHash = obj.get('promptTemplatesHash') || undefined;
    const myPromptTemplatesHash = obj.get('myPromptTemplatesHash') || undefined;

    const updatedAtMs = obj.get('updatedAtMs') || 0;

    return {
      obj,
      docs,
      aiConfig,
      promptTemplates,
      myPromptTemplates,
      docUpdatedAt,
      configUpdatedAt,
      templateUpdatedAt,
      myPromptTemplateUpdatedAt,
      aiConfigHash,        // 新增
      promptTemplatesHash, // 新增
      myPromptTemplatesHash, // 新增
      updatedAtMs          // 新增
    };
  }

  // 落地：本地（同步后物理删除已标记文档）
  function applyTargetToLocal(target) {
    // 物理剔除已删除文档
    const aliveDocs = target.docs.filter(d => !d.deletedAt);
    localStorage.setItem('mw_documents', JSON.stringify(aliveDocs));
    // AI 配置
    localStorage.setItem('allAIPlatformConfigs', JSON.stringify(target.aiConfig));
    localStorage.setItem('allAIPlatformConfigs_hash', target.aiConfigHash);
    localStorage.setItem('allAIPlatformConfigs_last_modified', String(target.aiConfigLastModified));
    // 提示词模板
    localStorage.setItem('promptTemplates', JSON.stringify(target.promptTemplates));
    localStorage.setItem('promptTemplates_hash', target.promptTemplatesHash);
    localStorage.setItem('promptTemplates_last_modified', String(target.promptTemplatesLastModified));
    // 我的提示词模板
    localStorage.setItem('myPromptTemplates', JSON.stringify(target.myPromptTemplates));
    localStorage.setItem('myPromptTemplates_hash', target.myPromptTemplatesHash);
    localStorage.setItem('myPromptTemplates_last_modified', String(target.myPromptTemplatesLastModified));
    // 同步时间戳
    localStorage.setItem('mindword_last_sync_at', String(Date.now()));
  }

  // async function uploadCloud(obj, docs) {
  //   obj.set('docs', docs);
  //   obj.set('updatedAtMs', Date.now());
  //   return await obj.save();
  // }

  // 显示同步预览对话框
  async function showSyncPreviewDialog(localFullData, cloudFullData, targetFullData) {
    return new Promise((resolve) => {
      // 创建对话框HTML
      const dialog = document.createElement('div');
      dialog.id = 'sync-preview-dialog';
      dialog.innerHTML = `
        <div style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); z-index: 10000; display: flex; align-items: center; justify-content: center;">
          <div style="background: white; border-radius: 12px; padding: 24px; width: 90%; max-width: 1000px; max-height: 80vh; overflow: hidden; display: flex; flex-direction: column; box-shadow: 0 20px 40px rgba(0,0,0,0.3);">
            <div style="display: flex; align-items: center; margin-bottom: 20px;">
              <h3 style="margin: 0; color: #333; font-size: 20px; font-weight: 600;">🔄 同步预览</h3>
              <div style="margin-left: auto; font-size: 12px; color: #666; background: #f8f9fa; padding: 4px 8px; border-radius: 4px;">
                选择要保留的数据
              </div>
            </div>
            <div style="flex: 1; overflow-y: auto; border: 1px solid #e0e0e0; border-radius: 8px; background: #fafafa;">
              <table style="width: 100%; border-collapse: collapse;">
                <thead style="background: #f5f5f5; position: sticky; top: 0; z-index: 10;">
                  <tr>
                    <th style="padding: 16px; text-align: center; border-bottom: 1px solid #ddd; width: 50%; color: #333; font-weight: 600; font-size: 14px;">
                      <span style="display: inline-flex; align-items: center; gap: 8px;">
                        <span>📁</span>
                        <span>本地数据</span>
                      </span>
                    </th>
                    <th style="padding: 16px; text-align: center; border-bottom: 1px solid #ddd; width: 50%; color: #333; font-weight: 600; font-size: 14px;">
                      <span style="display: inline-flex; align-items: center; gap: 8px;">
                        <span>☁️</span>
                        <span>云端数据</span>
                      </span>
                    </th>
                  </tr>
                </thead>
                <tbody id="sync-preview-tbody">
                </tbody>
              </table>
            </div>
            <div style="margin-top: 20px; text-align: right; display: flex; justify-content: flex-end; align-items: center;">
              <div>
                <button id="sync-preview-cancel" style="margin-right: 12px; padding: 10px 20px; border: 1px solid #ddd; background: white; border-radius: 6px; cursor: pointer; font-weight: 500; transition: all 0.2s;">取消</button>
                <button id="sync-preview-confirm" style="padding: 10px 24px; background: linear-gradient(135deg, #28a745, #20c997); color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: 600; transition: all 0.2s; box-shadow: 0 2px 8px rgba(40, 167, 69, 0.3);">🔄 确定同步</button>
              </div>
            </div>
          </div>
        </div>
      `;

      document.body.appendChild(dialog);

      // 生成对比数据
      const tbody = document.getElementById('sync-preview-tbody');
      const comparisons = generateSyncComparisons(localFullData, cloudFullData, targetFullData);

      comparisons.forEach((item, index) => {
        const row = document.createElement('tr');
        row.style.borderBottom = '1px solid #eee';

        // 如果内容一致，使用统一的淡灰色背景，禁用选择功能
        if (item.isContentSame) {
          row.style.backgroundColor = '#f0f0f0';
          row.style.opacity = '0.8';
        }

        // 状态管理 - 使用数据属性存储当前选择
        row.dataset.choice = item.recommendLocal ? 'local' : 'cloud';

        // 本地数据列
        const localCell = document.createElement('td');
        localCell.style.padding = '8px';
        localCell.style.verticalAlign = 'top';
        localCell.style.position = 'relative';
        localCell.style.cursor = 'pointer';
        localCell.style.transition = 'all 0.2s ease';
        localCell.style.width = '50%';

        const updateLocalCellStyle = () => {
          if (item.isContentSame) {
            // 内容一致时使用统一的淡灰色样式
            localCell.style.backgroundColor = '#e8e8e8';
            localCell.style.border = '1px solid #ccc';
            localCell.style.borderRadius = '6px';
            localCell.style.margin = '2px';
          } else {
            const isSelected = row.dataset.choice === 'local';
            localCell.style.backgroundColor = isSelected ? '#f0f8f0' : '#fafafa';
            localCell.style.border = isSelected ? '2px solid #28a745' : '1px solid #eee';
            localCell.style.borderRadius = '6px';
            localCell.style.margin = '2px';

            // 更新勾选图标显示状态
            const checkMark = localCell.querySelector('.check-mark');
            const cloudCheckMark = cloudCell.querySelector('.check-mark');
            if (checkMark && cloudCheckMark) {
              checkMark.style.display = isSelected ? 'block' : 'none';
              cloudCheckMark.style.display = !isSelected ? 'block' : 'none';
            }
          }
        };

        localCell.innerHTML = `
          <div style="font-weight: bold; color: #333; margin-bottom: 2px; display: flex; align-items: center; justify-content: space-between;">
            <span>${item.local.name}</span>
            <span class="check-mark" style="color: #28a745; font-size: 16px; display: ${item.isContentSame ? 'none' : (row.dataset.choice === 'local' ? 'block' : 'none')};">✓</span>
          </div>
          <div style="font-size: 11px; color: #666; line-height: 1.3;">${item.local.description}</div>
          <div style="font-size: 11px; color: #999; margin-top: 2px;">更新时间: ${item.local.updatedAt}</div>
        `;

        // 点击本地列选择本地 - 内容一致时禁用点击
        localCell.addEventListener('click', () => {
          if (item.isContentSame) return; // 内容一致时不允许切换
          row.dataset.choice = 'local';
          updateLocalCellStyle();
          updateCloudCellStyle();
        });

        // 云端数据列
        const cloudCell = document.createElement('td');
        cloudCell.style.padding = '8px';
        cloudCell.style.verticalAlign = 'top';
        cloudCell.style.position = 'relative';
        cloudCell.style.cursor = 'pointer';
        cloudCell.style.transition = 'all 0.2s ease';
        cloudCell.style.width = '50%';

        const updateCloudCellStyle = () => {
          if (item.isContentSame) {
            // 内容一致时使用统一的淡灰色样式
            cloudCell.style.backgroundColor = '#e8e8e8';
            cloudCell.style.border = '1px solid #ccc';
            cloudCell.style.borderRadius = '6px';
            cloudCell.style.margin = '2px';
          } else {
            const isSelected = row.dataset.choice === 'cloud';
            cloudCell.style.backgroundColor = isSelected ? '#f0f8f0' : '#fafafa';
            cloudCell.style.border = isSelected ? '2px solid #28a745' : '1px solid #eee';
            cloudCell.style.borderRadius = '6px';
            cloudCell.style.margin = '2px';

            // 更新勾选图标显示状态
            const checkMark = cloudCell.querySelector('.check-mark');
            const localCheckMark = localCell.querySelector('.check-mark');
            if (checkMark && localCheckMark) {
              checkMark.style.display = isSelected ? 'block' : 'none';
              localCheckMark.style.display = !isSelected ? 'block' : 'none';
            }
          }
        };

        cloudCell.innerHTML = `
          <div style="font-weight: bold; color: #333; margin-bottom: 2px; display: flex; align-items: center; justify-content: space-between;">
            <span>${item.cloud.name}</span>
            <span class="check-mark" style="color: #28a745; font-size: 16px; display: ${item.isContentSame ? 'none' : (row.dataset.choice === 'cloud' ? 'block' : 'none')};">✓</span>
          </div>
          <div style="font-size: 11px; color: #666; line-height: 1.3;">${item.cloud.description}</div>
          <div style="font-size: 11px; color: #999; margin-top: 2px;">更新时间: ${item.cloud.updatedAt}</div>
        `;

        // 点击云端列选择云端 - 内容一致时禁用点击
        cloudCell.addEventListener('click', () => {
          if (item.isContentSame) return; // 内容一致时不允许切换
          row.dataset.choice = 'cloud';
          updateLocalCellStyle();
          updateCloudCellStyle();
        });

        // 初始化样式
        updateLocalCellStyle();
        updateCloudCellStyle();

        row.appendChild(localCell);
        row.appendChild(cloudCell);
        tbody.appendChild(row);
      });

      // 绑定按钮事件
      document.getElementById('sync-preview-cancel').addEventListener('click', () => {
        document.body.removeChild(dialog);
        resolve(null); // 用户取消
      });

      document.getElementById('sync-preview-confirm').addEventListener('click', () => {
        const choices = {};
        comparisons.forEach((item, index) => {
          // 直接从行数据属性获取选择状态
          const row = document.querySelectorAll('#sync-preview-tbody tr')[index];
          choices[item.key] = row.dataset.choice || (item.recommendLocal ? 'local' : 'cloud');
        });

        document.body.removeChild(dialog);
        resolve(choices); // 返回用户选择
      });
    });
  }

  // 生成同步对比数据
  function generateSyncComparisons(localFullData, cloudFullData, targetFullData) {
    const comparisons = [];

    // 文档对比
    const localDocs = localFullData.docs || [];
    const cloudDocs = cloudFullData.docs || [];

    // 过滤掉自动生成的空文档
    const filteredLocalDocs = localDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));
    const filteredCloudDocs = cloudDocs.filter(doc => !isAutoGeneratedEmptyDoc(doc));

    const localDocMap = new Map(filteredLocalDocs.map(d => [d.id, d]));
    const cloudDocMap = new Map(filteredCloudDocs.map(d => [d.id, d]));

    // 找出所有文档ID（只包含过滤后的文档）
    const allDocIds = new Set([...filteredLocalDocs.map(d => d.id), ...filteredCloudDocs.map(d => d.id)]);

    allDocIds.forEach(docId => {
      const localDoc = localDocMap.get(docId);
      const cloudDoc = cloudDocMap.get(docId);

      if (localDoc && cloudDoc) {
        // 两边都有 - 检查内容是否一致（包含图片数据）
        const isContentSame = localDoc.md === cloudDoc.md && JSON.stringify(localDoc.images || []) === JSON.stringify(cloudDoc.images || []);
        let description = '';
        
        if (isContentSame) {
          description = '<span style="color: #28a745;">内容一致 ✓</span>';
        } else {
          // 检查是否有图片变化
          const localImages = localDoc.images || [];
          const cloudImages = cloudDoc.images || [];
          const imagesChanged = JSON.stringify(localImages) !== JSON.stringify(cloudImages);
          const mdChanged = localDoc.md !== cloudDoc.md;
          
          if (mdChanged && imagesChanged) {
            description = '<span style="color: #dc3545;">内容和图片都已变更</span>';
          } else if (imagesChanged) {
            description = '<span style="color: #ffc107;">图片已变更</span>';
          } else {
            description = '<span style="color: #dc3545;">内容不一致</span>';
          }
        }
        const localTime = new Date(Number(localDoc.updatedAt)).toLocaleString();
        const cloudTime = new Date(Number(cloudDoc.updatedAt)).toLocaleString();
        const recommendLocal = localDoc.updatedAt >= cloudDoc.updatedAt;

        // 检查是否有文档被删除
        const localDeleted = localDoc.deletedAt;
        const cloudDeleted = cloudDoc.deletedAt;

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: localDoc.name || '未命名文档',
            description: localDeleted ? '<span style="color: #dc3545;">本地已删除文档</span>' : description,
            updatedAt: localTime
          },
          cloud: {
            name: cloudDoc.name || '未命名文档',
            description: cloudDeleted ? '<span style="color: #dc3545;">云端已删除文档</span>' : description,
            updatedAt: cloudTime
          },
          recommendLocal: recommendLocal,
          isContentSame: isContentSame && !localDeleted && !cloudDeleted
        });
      } else if (localDoc && !cloudDoc) {
        // 只有本地有 - 判断是新增还是删除
        // 如果本地文档已删除，则跳过这个对比（空对空没有意义）
        if (localDoc.deletedAt) {
          return; // 跳过本地已删除文档
        }

        const isRecentlyUpdated = localDoc.updatedAt > Date.now() - 24 * 60 * 60 * 1000; // 24小时内更新过
        let description = '';

        if (isRecentlyUpdated) {
          description = '<span style="color: #28a745;">本地新增文档</span>';
        } else {
          description = '<span style="color: #28a745;">本地独有文档</span>';
        }

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: localDoc.name || '未命名文档',
            description: description,
            updatedAt: new Date(Number(localDoc.updatedAt)).toLocaleString()
          },
          cloud: {
            name: '(无)',
            description: '云端不存在',
            updatedAt: '-'
          },
          recommendLocal: true
        });
      } else if (!localDoc && cloudDoc) {
        // 只有云端有 - 判断是新增还是删除
        // 如果云端文档已删除，则跳过这个对比（空对空没有意义）
        if (cloudDoc.deletedAt) {
          return; // 跳过云端已删除文档
        }

        const isRecentlyUpdated = cloudDoc.updatedAt > Date.now() - 24 * 60 * 60 * 1000; // 24小时内更新过
        let description = '';

        if (isRecentlyUpdated) {
          description = '<span style="color: #28a745;">云端新增文档</span>';
        } else {
          description = '<span style="color: #28a745;">云端独有文档</span>';
        }

        comparisons.push({
          key: `doc_${docId}`,
          local: {
            name: '(无)',
            description: '本地不存在',
            updatedAt: '-'
          },
          cloud: {
            name: cloudDoc.name || '未命名文档',
            description: description,
            updatedAt: new Date(Number(cloudDoc.updatedAt)).toLocaleString()
          },
          recommendLocal: false
        });
      }
    });

    // AI配置对比
    const localAIConfig = localFullData.aiConfig || {};
    const cloudAIConfig = cloudFullData.aiConfig || {};
    const localAIConfigTime = new Date(localFullData.aiConfigLastModified).toLocaleString();
    const cloudAIConfigTime = new Date(cloudFullData.aiConfigLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isAIConfigSame = localFullData.aiConfigHash === cloudFullData.aiConfigHash;

    // 判断配置是否为空
    const localConfigEmpty = Object.keys(localAIConfig).length === 0;
    const cloudConfigEmpty = Object.keys(cloudAIConfig).length === 0;

    comparisons.push({
      key: 'ai_config',
      local: {
        name: 'AI平台配置',
        description: isAIConfigSame ? `配置一致 ✓ (平台数量: ${Object.keys(localAIConfig).length}个)` :
          localConfigEmpty ? '本地无配置' : `平台数量: ${Object.keys(localAIConfig).length}个`,
        updatedAt: localAIConfigTime
      },
      cloud: {
        name: 'AI平台配置',
        description: isAIConfigSame ? `配置一致 ✓ (平台数量: ${Object.keys(cloudAIConfig).length}个)` :
          cloudConfigEmpty ? '云端无配置' : `平台数量: ${Object.keys(cloudAIConfig).length}个`,
        updatedAt: cloudAIConfigTime
      },
      recommendLocal: localFullData.aiConfigLastModified >= cloudFullData.aiConfigLastModified,
      isContentSame: isAIConfigSame
    });

    // 提示词模板对比
    const localPromptTemplates = localFullData.promptTemplates || [];
    const cloudPromptTemplates = cloudFullData.promptTemplates || [];
    const localPromptTime = new Date(localFullData.promptTemplatesLastModified).toLocaleString();
    const cloudPromptTime = new Date(cloudFullData.promptTemplatesLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isPromptTemplatesSame = localFullData.promptTemplatesHash === cloudFullData.promptTemplatesHash;

    // 判断模板是否为空
    const localTemplatesEmpty = localPromptTemplates.length === 0;
    const cloudTemplatesEmpty = cloudPromptTemplates.length === 0;

    comparisons.push({
      key: 'prompt_templates',
      local: {
        name: '提示词模板',
        description: isPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${localPromptTemplates.length}个)` :
          localTemplatesEmpty ? '本地无模板' : `模板数量: ${localPromptTemplates.length}个`,
        updatedAt: localPromptTime
      },
      cloud: {
        name: '提示词模板',
        description: isPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${cloudPromptTemplates.length}个)` :
          cloudTemplatesEmpty ? '云端无模板' : `模板数量: ${cloudPromptTemplates.length}个`,
        updatedAt: cloudPromptTime
      },
      recommendLocal: localFullData.promptTemplatesLastModified >= cloudFullData.promptTemplatesLastModified,
      isContentSame: isPromptTemplatesSame
    });

    // 我的提示词模板对比
    const localMyPromptTemplates = localFullData.myPromptTemplates || [];
    const cloudMyPromptTemplates = cloudFullData.myPromptTemplates || [];
    const localMyPromptTime = new Date(localFullData.myPromptTemplatesLastModified).toLocaleString();
    const cloudMyPromptTime = new Date(cloudFullData.myPromptTemplatesLastModified).toLocaleString();
    // 使用哈希值快速对比内容一致性
    const isMyPromptTemplatesSame = localFullData.myPromptTemplatesHash === cloudFullData.myPromptTemplatesHash;

    // 判断模板是否为空
    const localMyTemplatesEmpty = localMyPromptTemplates.length === 0;
    const cloudMyTemplatesEmpty = cloudMyPromptTemplates.length === 0;

    comparisons.push({
      key: 'my_prompt_templates',
      local: {
        name: '我的提示词模板',
        description: isMyPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${localMyPromptTemplates.length}个)` :
          localMyTemplatesEmpty ? '本地无模板' : `模板数量: ${localMyPromptTemplates.length}个`,
        updatedAt: localMyPromptTime
      },
      cloud: {
        name: '我的提示词模板',
        description: isMyPromptTemplatesSame ? `模板一致 ✓ (模板数量: ${cloudMyPromptTemplates.length}个)` :
          cloudMyTemplatesEmpty ? '云端无模板' : `模板数量: ${cloudMyPromptTemplates.length}个`,
        updatedAt: cloudMyPromptTime
      },
      recommendLocal: localFullData.myPromptTemplatesLastModified >= cloudFullData.myPromptTemplatesLastModified,
      isContentSame: isMyPromptTemplatesSame
    });

    return comparisons;
  }

  // 根据用户选择重新构建目标数据
  function buildTargetFromChoices(localFullData, cloudFullData, choices) {
    const target = {
      docs: [],
      aiConfig: {},
      promptTemplates: [],
      myPromptTemplates: [],
      aiConfigHash: undefined,
      aiConfigLastModified: 0,
      promptTemplatesHash: undefined,
      promptTemplatesLastModified: 0,
      myPromptTemplatesHash: undefined,
      myPromptTemplatesLastModified: 0,
      lastSyncAt: Date.now()
    };

    // 处理文档选择
    const localDocs = localFullData.docs || [];
    const cloudDocs = cloudFullData.docs || [];
    const localDocMap = new Map(localDocs.map(d => [d.id, d]));
    const cloudDocMap = new Map(cloudDocs.map(d => [d.id, d]));
    const allDocIds = new Set([...localDocs.map(d => d.id), ...cloudDocs.map(d => d.id)]);

    allDocIds.forEach(docId => {
      const choice = choices[`doc_${docId}`];
      
      // 用户明确选择了本地版本
      if (choice === 'local') {
        if (localDocMap.has(docId)) {
          target.docs.push(localDocMap.get(docId));
        }
        // 如果用户选择本地但本地不存在该文档，则不添加（即删除）
      }
      // 用户明确选择了云端版本
      else if (choice === 'cloud') {
        if (cloudDocMap.has(docId)) {
          target.docs.push(cloudDocMap.get(docId));
        }
        // 如果用户选择云端但云端不存在该文档，则不添加（即删除）
      }
      // 用户没有选择，使用推荐逻辑
      else {
        if (localDocMap.has(docId) && cloudDocMap.has(docId)) {
          // 两边都有，选择更新时间较新的
          const localDoc = localDocMap.get(docId);
          const cloudDoc = cloudDocMap.get(docId);
          target.docs.push(localDoc.updatedAt >= cloudDoc.updatedAt ? localDoc : cloudDoc);
        } else if (localDocMap.has(docId)) {
          // 只有本地有，保留本地版本
          target.docs.push(localDocMap.get(docId));
        } else if (cloudDocMap.has(docId)) {
          // 只有云端有，保留云端版本
          target.docs.push(cloudDocMap.get(docId));
        }
      }
    });

    // 处理AI配置选择
    if (choices.ai_config === 'local') {
      target.aiConfig = localFullData.aiConfig || {};
      target.aiConfigHash = localFullData.aiConfigHash;
      target.aiConfigLastModified = localFullData.aiConfigLastModified;
    } else {
      target.aiConfig = cloudFullData.aiConfig || {};
      target.aiConfigHash = cloudFullData.aiConfigHash;
      target.aiConfigLastModified = cloudFullData.aiConfigLastModified;
    }

    // 处理提示词模板选择
    if (choices.prompt_templates === 'local') {
      target.promptTemplates = localFullData.promptTemplates || [];
      target.promptTemplatesHash = localFullData.promptTemplatesHash;
      target.promptTemplatesLastModified = localFullData.promptTemplatesLastModified;
    } else {
      target.promptTemplates = cloudFullData.promptTemplates || [];
      target.promptTemplatesHash = cloudFullData.promptTemplatesHash;
      target.promptTemplatesLastModified = cloudFullData.promptTemplatesLastModified;
    }

    // 处理我的提示词模板选择
    if (choices.my_prompt_templates === 'local') {
      target.myPromptTemplates = localFullData.myPromptTemplates || [];
      target.myPromptTemplatesHash = localFullData.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = localFullData.myPromptTemplatesLastModified;
    } else {
      target.myPromptTemplates = cloudFullData.myPromptTemplates || [];
      target.myPromptTemplatesHash = cloudFullData.myPromptTemplatesHash;
      target.myPromptTemplatesLastModified = cloudFullData.myPromptTemplatesLastModified;
    }

    return target;
  }

  // 新的同步逻辑：按照用户方案实现
  async function bidirectionalSync() {
    try {
      if (getLang() !== 'zh') { showInfo('当前为英文模式，已使用 Cloudflare Worker 同步'); return; }
      if (!isLoggedIn()) { throw new Error('未登录'); }
      showInfo('正在智能同步...');

      // 1. 组装本地完整快照
      const localDocs = getLocalDocs();
      const localAIConfig = getLocalAIConfig();
      const localPromptTemplates = getLocalPromptTemplates();
      const localMyPromptTemplates = getLocalMyPromptTemplates();
      const localFullData = {
        docs: localDocs,
        aiConfig: localAIConfig,
        aiConfigHash: localStorage.getItem('allAIPlatformConfigs_hash') || undefined,
        aiConfigLastModified: Number(localStorage.getItem('allAIPlatformConfigs_last_modified') || 0),
        promptTemplates: localPromptTemplates,
        promptTemplatesHash: localStorage.getItem('promptTemplates_hash') || undefined,
        promptTemplatesLastModified: Number(localStorage.getItem('promptTemplates_last_modified') || 0),
        myPromptTemplates: localMyPromptTemplates,
        myPromptTemplatesHash: localStorage.getItem('myPromptTemplates_hash') || undefined,
        myPromptTemplatesLastModified: Number(localStorage.getItem('myPromptTemplates_last_modified') || 0),
        lastSyncAt: Number(localStorage.getItem('mindword_last_sync_at') || 0)
      };

      // 文件大小检查
      const sizeCheck = checkFileSize(localDocs);
      if (!sizeCheck.valid) {
        throw new Error('文件大小检查失败：' + sizeCheck.errors.join('；'));
      }

      // 2. 拉取云端同结构快照（首次拉取时缓存原生对象）
      cachedCloudRaw = await downloadCloud();
      const cloudFullData = await fetchCloudFullData();

      // 3. 三向合并 → 目标结构
      const targetFullData = mergeToTarget(localFullData, cloudFullData);

      // 4. 显示同步预览对话框，让用户选择保留哪一侧的数据
      const userChoices = await showSyncPreviewDialog(localFullData, cloudFullData, targetFullData);

      // 用户取消同步
      if (!userChoices) {
        showInfo('同步已取消');
        return;
      }

      // 5. 根据用户选择重新构建目标数据
      const finalTargetFullData = buildTargetFromChoices(localFullData, cloudFullData, userChoices);

      // 6. 落地：先写本地，再写云端（确保本地优先）
      applyTargetToLocal(finalTargetFullData);
      await applyTargetToCloud(finalTargetFullData, cloudFullData, cachedCloudRaw.obj);

      // 5. 刷新 UI
      if (typeof mw_renderList === 'function') mw_renderList();

      // 6. 如果当前有正在编辑的文档，刷新数据展示
      if (typeof mw_getActive === 'function' && typeof mw_notifyEditorLoad === 'function') {
        const activeId = mw_getActive();
        if (activeId && typeof mw_loadDocs === 'function') {
          const docs = mw_loadDocs();
          const currentDoc = docs.find(d => d.id === activeId);
          if (currentDoc) {
            // 刷新当前文档到各个面板
            mw_notifyEditorLoad(currentDoc);
            if (typeof mw_notifyPreviewLoad === 'function') mw_notifyPreviewLoad(currentDoc);
            if (typeof mw_notifyMindmapLoad === 'function') mw_notifyMindmapLoad(currentDoc);
            console.log('[SYNC] 已刷新当前编辑文档:', activeId);
          }
        }

        // 检查当前文档是否被删除，如果是则切换到第一个有效文档
        const currentActiveId = mw_getActive();
        if (currentActiveId) {
          const docs = getLocalDocs();
          const currentDoc = docs.find(d => d.id === currentActiveId);
          if (!currentDoc || currentDoc.deletedAt) {
            console.log('[SYNC] 当前文档已被删除，准备切换到第一个有效文档');
            // 切换到第一个未删除的文档
            const firstValidDoc = docs.find(d => !d.deletedAt);
            if (firstValidDoc) {
              mw_setActive(firstValidDoc.id);
              mw_notifyEditorLoad(firstValidDoc);
              mw_notifyPreviewLoad(firstValidDoc);
              mw_notifyMindmapLoad(firstValidDoc);
              console.log('[SYNC] 已切换到第一个有效文档:', firstValidDoc.id);
            } else {
              // 没有有效文档，不自动生成空文档，让用户手动创建
              console.log('[SYNC] 没有有效文档，等待用户手动创建');
            }
          }
        }
      }

      // 7. 同步完成后，如果当前是自动生成的空文档，切换到第一个有效文档
      setTimeout(() => {
        const currentActiveId = mw_getActive();
        if (currentActiveId && typeof mw_loadDocs === 'function') {
          const docs = mw_loadDocs();
          const currentDoc = docs.find(d => d.id === currentActiveId);

          // 如果当前文档是自动生成的空文档，切换到第一个有效文档
          if (currentDoc && isAutoGeneratedEmptyDoc(currentDoc)) {
            console.log('[SYNC] 当前文档是自动生成的空文档，准备切换到第一个有效文档');
            const validDocs = docs.filter(d => !d.deletedAt && !isAutoGeneratedEmptyDoc(d));
            if (validDocs.length > 0) {
              const firstValidDoc = validDocs[0];
              mw_setActive(firstValidDoc.id);
              mw_notifyEditorLoad(firstValidDoc);
              mw_notifyPreviewLoad(firstValidDoc);
              mw_notifyMindmapLoad(firstValidDoc);
              console.log('[SYNC] 已切换到第一个有效文档:', firstValidDoc.id);
            } else {
              console.log('[SYNC] 没有有效文档，保持当前空文档状态');
            }
          }
        }
      }, 200);
      // 缓存同步数据到本地（中文版使用独立缓存键）
      try {
        const docs = getLocalDocs();
        const fileCount = docs ? docs.length : 0;
        localStorage.setItem('mw_cloud_sync_cache_cn', JSON.stringify({
          fileCount: fileCount,
          sizeBytes: sizeCheck.totalSize,
          updatedAt: new Date().toISOString()
        }));
      } catch (_) { }

      showSuccess('同步完成');
      setTimeout(updateSyncStatus, 300);
    } catch (e) {
      showError(e.message || '同步失败');
    }
  }

  async function clearCloud() {
    try {
      if (getLang() !== 'zh') { showInfo('当前为英文模式，请用“清空备份”按钮'); return; }
      if (!isLoggedIn()) { throw new Error('未登录'); }
      if (!confirm('确认清空云端数据？此操作不可撤销')) return;
      const { obj } = await downloadCloud();

      // 清空所有数据
      obj.set('docs', []);
      obj.set('aiConfig', {});
      obj.set('promptTemplates', []);
      obj.set('myPromptTemplates', []);
      obj.set('docUpdatedAt', Date.now());
      obj.set('configUpdatedAt', Date.now());
      obj.set('templateUpdatedAt', Date.now());
      obj.set('myPromptTemplateUpdatedAt', Date.now());

      await obj.save();
      showSuccess('云端数据已清空');
    } catch (e) {
      showError(e.message || '清空失败');
    }
  }

  function initUIBindings() {
    const zhCtrls = document.getElementById('lc-sync-controls');


    // 个人菜单中的按钮
    const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
    const menuClearBtn = document.getElementById('lc-clear-btn-menu');

    // 添加状态显示元素
    if (zhCtrls && !document.getElementById('lc-sync-status')) {
      const statusDiv = document.createElement('div');
      statusDiv.id = 'lc-sync-status';
      statusDiv.style.cssText = 'margin-left: 8px; padding: 4px 8px; background: #f8f9fa; border-radius: 4px;';
      zhCtrls.appendChild(statusDiv);
    }



    // 绑定个人菜单按钮 - 使用addEventListener确保函数可访问
    if (menuSyncBtn) {
      menuSyncBtn.addEventListener('click', bidirectionalSync);
    }
    if (menuClearBtn) {
      menuClearBtn.addEventListener('click', clearCloud);
    }

    // 登录状态或语言变化时切换显示
    function refreshVisible() {
      const authUser = document.getElementById('auth-user');
      const enCtrls = document.getElementById('cloud-sync-controls');
      // 未登录：两组隐藏，避免初次闪现
      if (!authUser || authUser.style.display === 'none') {
        if (enCtrls) enCtrls.style.display = 'none';
        if (zhCtrls) zhCtrls.style.display = 'none';
        return;
      }
      if (getLang() === 'zh') {
        if (enCtrls) enCtrls.style.display = 'none';
        if (zhCtrls) zhCtrls.style.display = 'inline-flex';
      } else {
        if (enCtrls) enCtrls.style.display = 'inline-flex';
        if (zhCtrls) zhCtrls.style.display = 'none';
      }
    }

    document.addEventListener('DOMContentLoaded', refreshVisible);
    window.addEventListener('storage', function (e) {
      if (e.key === LANG_KEY || (e.key && e.key.startsWith('AV/'))) setTimeout(refreshVisible, 50);
    });
    // 提供给外部在认证区变化后刷新
    window.__mw_refreshSyncLangUI = refreshVisible;

    // 初始化状态显示
    setTimeout(updateSyncStatus, 500);
  }

  // 页面就绪后初始化
  document.addEventListener('DOMContentLoaded', function () {
    initUIBindings();
    // 尝试在认证区刷新后应用一次
    setTimeout(applyLangUIOnce, 300);

    // 监听文档变化，自动更新状态
    if (typeof mw_getDocs === 'function') {
      // 监听本地存储变化
      window.addEventListener('storage', function (e) {
        if (e.key && e.key.includes('doc')) {
          setTimeout(updateSyncStatus, 100);
        }
      });

      // 定期更新状态（每30秒）
      setInterval(updateSyncStatus, 30000);
    }

    // 初始化个人菜单状态
    setTimeout(() => {
      updateSyncStatus();
      // 同时更新Cloudflare Worker的个人菜单状态
      if (typeof window.__mw_initCloudSyncUI === 'function') {
        window.__mw_initCloudSyncUI();
      }
    }, 100);
  });

  // 显示文件大小和同步状态
  function updateSyncStatus() {
    try {
      // 根据当前语言选择对应的缓存键
      const currentLang = getLang();
      const cacheKey = currentLang === 'en' ? 'mw_cloud_sync_cache_en' : 'mw_cloud_sync_cache_cn';

      // 首先尝试从本地缓存获取数据
      let cachedData = null;
      try {
        const cached = localStorage.getItem(cacheKey);
        if (cached) {
          cachedData = JSON.parse(cached);
        }
      } catch (_) { }

      // 如果有缓存数据，优先使用缓存数据
      if (cachedData && cachedData.fileCount !== undefined && cachedData.sizeBytes !== undefined) {
        const fileCount = cachedData.fileCount || 0;
        const sizeBytes = cachedData.sizeBytes || 0;
        const totalSizeKB = (sizeBytes / 1024).toFixed(1);
        const updatedAt = cachedData.updatedAt || cachedData.timestamp;

        // 计算相对时间
        let timeText = '';
        if (updatedAt) {
          const date = new Date(updatedAt);
          const now = new Date();
          const diffMs = now - date;
          const diffMins = Math.floor(diffMs / 60000);
          const diffHours = Math.floor(diffMs / 3600000);
          const diffDays = Math.floor(diffMs / 86400000);

          if (diffMins < 1) {
            timeText = '刚刚';
          } else if (diffMins < 60) {
            timeText = `${diffMins}分钟前`;
          } else if (diffHours < 24) {
            timeText = `${diffHours}小时前`;
          } else if (diffDays < 7) {
            timeText = `${diffDays}天前`;
          } else {
            timeText = date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' });
          }
        }

        // 更新状态显示（主界面）
        const statusElement = document.getElementById('lc-sync-status');
        if (statusElement) {
          statusElement.innerHTML = `
            <small style="color: #666; font-size: 11px;">
              文件: ${fileCount}个<br>${totalSizeKB}KB / 10MB${timeText ? '<br>备份: ' + timeText : ''}
            </small>
          `;

          // 根据使用情况改变颜色
          if (sizeBytes > 8 * 1024 * 1024) { // 超过8MB
            statusElement.querySelector('small').style.color = '#e74c3c';
          } else if (sizeBytes > 5 * 1024 * 1024) { // 超过5MB
            statusElement.querySelector('small').style.color = '#f39c12';
          }
        }

        // 更新个人菜单中的状态显示
        const menuStatusElement = document.getElementById('lc-sync-status-menu');
        if (menuStatusElement) {
          menuStatusElement.innerHTML = `文件: ${fileCount}个<br>${totalSizeKB}KB / 10MB${timeText ? '<br>备份: ' + timeText : ''}`;

          // 根据使用情况改变颜色
          if (sizeBytes > 8 * 1024 * 1024) { // 超过8MB
            menuStatusElement.style.color = '#e74c3c';
          } else if (sizeBytes > 5 * 1024 * 1024) { // 超过5MB
            menuStatusElement.style.color = '#f39c12';
          } else {
            menuStatusElement.style.color = '#9ca3af';
          }
        }

        // 更新按钮状态
        const syncBtn = document.getElementById('lc-sync-btn');
        if (syncBtn) {
          syncBtn.disabled = false;
          syncBtn.title = '一键同步';
          syncBtn.style.opacity = '1';
        }

        // 更新个人菜单中的同步按钮状态
        const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
        if (menuSyncBtn) {
          menuSyncBtn.disabled = false;
          menuSyncBtn.title = '一键同步';
          menuSyncBtn.style.opacity = '1';
        }

        return;
      }

      // 如果没有缓存数据，使用原有的本地数据逻辑
      const docs = getLocalDocs();
      // 过滤掉已删除的文档，只统计有效文档
      const validDocs = docs ? docs.filter(doc => !doc.deletedAt) : [];
      const sizeCheck = checkFileSize(validDocs);

      // 更新状态显示（主界面）
      const statusElement = document.getElementById('lc-sync-status');
      if (statusElement) {
        const totalSizeMB = (sizeCheck.totalSize / 1024).toFixed(1);
        const fileCount = validDocs.length;

        statusElement.innerHTML = `
          <small style="color: #666; font-size: 11px;">
            文件: ${fileCount}个<br>${totalSizeMB}KB / 10MB
          </small>
        `;

        // 根据使用情况改变颜色
        if (sizeCheck.totalSize > 8 * 1024 * 1024) { // 超过8MB
          statusElement.querySelector('small').style.color = '#e74c3c';
        } else if (sizeCheck.totalSize > 5 * 1024 * 1024) { // 超过5MB
          statusElement.querySelector('small').style.color = '#f39c12';
        }
      }

      // 更新个人菜单中的状态显示
      const menuStatusElement = document.getElementById('lc-sync-status-menu');
      if (menuStatusElement) {
        const totalSizeMB = (sizeCheck.totalSize / 1024).toFixed(1);
        const fileCount = validDocs.length;

        menuStatusElement.innerHTML = `文件: ${fileCount}个<br>${totalSizeMB}KB / 10MB`;

        // 根据使用情况改变颜色
        if (sizeCheck.totalSize > 8 * 1024 * 1024) { // 超过8MB
          menuStatusElement.style.color = '#e74c3c';
        } else if (sizeCheck.totalSize > 5 * 1024 * 1024) { // 超过5MB
          menuStatusElement.style.color = '#f39c12';
        } else {
          menuStatusElement.style.color = '#9ca3af';
        }
      }

      // 更新按钮状态
      const syncBtn = document.getElementById('lc-sync-btn');
      if (syncBtn) {
        if (!sizeCheck.valid) {
          syncBtn.disabled = true;
          syncBtn.title = '文件大小检查失败：' + sizeCheck.errors.join('；');
          syncBtn.style.opacity = '0.6';
        } else {
          syncBtn.disabled = false;
          syncBtn.title = '一键同步';
          syncBtn.style.opacity = '1';
        }
      }

      // 更新个人菜单中的同步按钮状态
      const menuSyncBtn = document.getElementById('lc-sync-btn-menu');
      if (menuSyncBtn) {
        if (!sizeCheck.valid) {
          menuSyncBtn.disabled = true;
          menuSyncBtn.title = '文件大小检查失败：' + sizeCheck.errors.join('；');
          menuSyncBtn.style.opacity = '0.6';
        } else {
          menuSyncBtn.disabled = false;
          menuSyncBtn.title = '一键同步';
          menuSyncBtn.style.opacity = '1';
        }
      }

    } catch (error) {
      console.warn('更新同步状态失败:', error);
    }
  }

  // 暴露手动入口（如需）
  window.MW_LC_SYNC = { sync: bidirectionalSync, clear: clearCloud, updateStatus: updateSyncStatus };

})();
